use crate::az::rtti::AzRtti;
use crate::az::uuid::Uuid as AzUuid;
use bevy_reflect::{ReflectDeserialize, ReflectSerialize};

#[derive(
    Debug,
    Default,
    Clone,
    Copy,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Hash,
    serde::Serialize,
    serde::Deserialize,
    bevy_reflect::Reflect,
)]
#[repr(u8)]
#[serde(try_from = "u8", into = "u8")]
#[reflect(Serialize, Deserialize)]
pub enum InteractionUIActions {
    #[default]
    Invalid = 0,
    CyclePermissions = 1,
    PickupBuildable = 2,
    RepairBuildable = 3,
    RemoveRespawn = 4,
    ToggleDoor = 5,
    UseQuickslot1 = 6,
    UseQuickslot2 = 7,
    UseQuickslot3 = 8,
    UseQuickslot4 = 9,
    UseQuickslot5 = 10,
    UseQuickslot6 = 11,
    SelectStructureAttachment = 12,
    SetStructureState = 13,
    GatherResource = 14,
    GatherWaterResource = 15,
    ApplyAllResources = 16,
    ApplyResources = 17,
    SetSpawnPoint = 18,
    Dismantle = 19,
    OpenCrafting = 20,
    OpenTradingPost = 21,
    OpenAttachment = 22,
    OpenPrefabRefinery = 23,
    OpenGenerator = 24,
    OpenTerritoryMarker = 25,
    OpenStorage = 26,
    OpenContracts = 27,
    TakeAll = 28,
    ToggleOnOff = 29,
    RevivePlayer = 30,
    OpenPaint = 31,
    OpenLootStorage = 32,
    Trigger = 33,
    AddTerritoryClaimTime = 34,
    OpenInteractScreen = 35,
    OpenStartClaimScreen = 36,
    UpgradeBuildable = 37,
    CancelUpgradeBuildable = 38,
    IncreaseStructureSecurityLevel = 39,
    DecreaseStructureSecurityLevel = 40,
    TakeOverBuildable = 41,
    SetStructureSecurityLevel = 42,
    StructureDeposit = 43,
    StructureWithdraw = 44,
    StructureDepositUnequip = 45,
    StructureWithdrawEquip = 46,
    OpenRead = 47,
    ModifyStatusEffect = 48,
    SetStructureName = 49,
    AddToJournal = 50,
    OpenObjectiveProvider = 51,
    UseTurret = 52,
    InteractWithItemCost = 53,
    OpenTerritoryInterface = 54,
    OpenTerritoryProgression = 55,
    PurchaseClaim = 56,
    HousingPurchase = 57,
    HousingEnter = 58,
    HousingQuickEnter = 59,
    HousingExit = 60,
    OpenRaidSetup = 61,
    OpenTurretSelection = 62,
    OpenConversation = 63,
    PlayInteractionAnimation = 64,
    ObjectiveInteraction = 65,
    OpenArenaMenu = 66,
    TeleportToOtherSideOfDoor = 67,
    UseArenaItem = 68,
    InteractWithHousingItem = 69,
    OpenInnScreen = 70,
    OpenDungeonMenu = 71,
    EnterDungeon = 72,
    BindToCamp = 73,
    ExitDungeon = 74,
    OpenSummoningSelection = 76,
    OpenMap = 77,
    OpenArmory = 78,
    OpenCampSkins = 79,
    OpenEventShop = 80,
    OpenHorseShop = 85,
    OpenWolfShop = 86,
    OpenLionShop = 87,
    PlayCinematicVideo = 81,
    InteractTeleporter = 82,
    TipPerformers = 83,
    EquipGearSet = 84,
}

impl From<InteractionUIActions> for u8 {
    fn from(value: InteractionUIActions) -> Self {
        match value {
            InteractionUIActions::Invalid => 0,
            InteractionUIActions::CyclePermissions => 1,
            InteractionUIActions::PickupBuildable => 2,
            InteractionUIActions::RepairBuildable => 3,
            InteractionUIActions::RemoveRespawn => 4,
            InteractionUIActions::ToggleDoor => 5,
            InteractionUIActions::UseQuickslot1 => 6,
            InteractionUIActions::UseQuickslot2 => 7,
            InteractionUIActions::UseQuickslot3 => 8,
            InteractionUIActions::UseQuickslot4 => 9,
            InteractionUIActions::UseQuickslot5 => 10,
            InteractionUIActions::UseQuickslot6 => 11,
            InteractionUIActions::SelectStructureAttachment => 12,
            InteractionUIActions::SetStructureState => 13,
            InteractionUIActions::GatherResource => 14,
            InteractionUIActions::GatherWaterResource => 15,
            InteractionUIActions::ApplyAllResources => 16,
            InteractionUIActions::ApplyResources => 17,
            InteractionUIActions::SetSpawnPoint => 18,
            InteractionUIActions::Dismantle => 19,
            InteractionUIActions::OpenCrafting => 20,
            InteractionUIActions::OpenTradingPost => 21,
            InteractionUIActions::OpenAttachment => 22,
            InteractionUIActions::OpenPrefabRefinery => 23,
            InteractionUIActions::OpenGenerator => 24,
            InteractionUIActions::OpenTerritoryMarker => 25,
            InteractionUIActions::OpenStorage => 26,
            InteractionUIActions::OpenContracts => 27,
            InteractionUIActions::TakeAll => 28,
            InteractionUIActions::ToggleOnOff => 29,
            InteractionUIActions::RevivePlayer => 30,
            InteractionUIActions::OpenPaint => 31,
            InteractionUIActions::OpenLootStorage => 32,
            InteractionUIActions::Trigger => 33,
            InteractionUIActions::AddTerritoryClaimTime => 34,
            InteractionUIActions::OpenInteractScreen => 35,
            InteractionUIActions::OpenStartClaimScreen => 36,
            InteractionUIActions::UpgradeBuildable => 37,
            InteractionUIActions::CancelUpgradeBuildable => 38,
            InteractionUIActions::IncreaseStructureSecurityLevel => 39,
            InteractionUIActions::DecreaseStructureSecurityLevel => 40,
            InteractionUIActions::TakeOverBuildable => 41,
            InteractionUIActions::SetStructureSecurityLevel => 42,
            InteractionUIActions::StructureDeposit => 43,
            InteractionUIActions::StructureWithdraw => 44,
            InteractionUIActions::StructureDepositUnequip => 45,
            InteractionUIActions::StructureWithdrawEquip => 46,
            InteractionUIActions::OpenRead => 47,
            InteractionUIActions::ModifyStatusEffect => 48,
            InteractionUIActions::SetStructureName => 49,
            InteractionUIActions::AddToJournal => 50,
            InteractionUIActions::OpenObjectiveProvider => 51,
            InteractionUIActions::UseTurret => 52,
            InteractionUIActions::InteractWithItemCost => 53,
            InteractionUIActions::OpenTerritoryInterface => 54,
            InteractionUIActions::OpenTerritoryProgression => 55,
            InteractionUIActions::PurchaseClaim => 56,
            InteractionUIActions::HousingPurchase => 57,
            InteractionUIActions::HousingEnter => 58,
            InteractionUIActions::HousingQuickEnter => 59,
            InteractionUIActions::HousingExit => 60,
            InteractionUIActions::OpenRaidSetup => 61,
            InteractionUIActions::OpenTurretSelection => 62,
            InteractionUIActions::OpenConversation => 63,
            InteractionUIActions::PlayInteractionAnimation => 64,
            InteractionUIActions::ObjectiveInteraction => 65,
            InteractionUIActions::OpenArenaMenu => 66,
            InteractionUIActions::TeleportToOtherSideOfDoor => 67,
            InteractionUIActions::UseArenaItem => 68,
            InteractionUIActions::InteractWithHousingItem => 69,
            InteractionUIActions::OpenInnScreen => 70,
            InteractionUIActions::OpenDungeonMenu => 71,
            InteractionUIActions::EnterDungeon => 72,
            InteractionUIActions::BindToCamp => 73,
            InteractionUIActions::ExitDungeon => 74,
            InteractionUIActions::OpenSummoningSelection => 76,
            InteractionUIActions::OpenMap => 77,
            InteractionUIActions::OpenArmory => 78,
            InteractionUIActions::OpenCampSkins => 79,
            InteractionUIActions::OpenEventShop => 80,
            InteractionUIActions::OpenHorseShop => 85,
            InteractionUIActions::OpenWolfShop => 86,
            InteractionUIActions::OpenLionShop => 87,
            InteractionUIActions::PlayCinematicVideo => 81,
            InteractionUIActions::InteractTeleporter => 82,
            InteractionUIActions::TipPerformers => 83,
            InteractionUIActions::EquipGearSet => 84,
        }
    }
}

impl ::core::convert::TryFrom<u8> for InteractionUIActions {
    type Error = u8;
    fn try_from(value: u8) -> Result<Self, u8> {
        match value {
            0 => Ok(Self::Invalid),
            1 => Ok(Self::CyclePermissions),
            2 => Ok(Self::PickupBuildable),
            3 => Ok(Self::RepairBuildable),
            4 => Ok(Self::RemoveRespawn),
            5 => Ok(Self::ToggleDoor),
            6 => Ok(Self::UseQuickslot1),
            7 => Ok(Self::UseQuickslot2),
            8 => Ok(Self::UseQuickslot3),
            9 => Ok(Self::UseQuickslot4),
            10 => Ok(Self::UseQuickslot5),
            11 => Ok(Self::UseQuickslot6),
            12 => Ok(Self::SelectStructureAttachment),
            13 => Ok(Self::SetStructureState),
            14 => Ok(Self::GatherResource),
            15 => Ok(Self::GatherWaterResource),
            16 => Ok(Self::ApplyAllResources),
            17 => Ok(Self::ApplyResources),
            18 => Ok(Self::SetSpawnPoint),
            19 => Ok(Self::Dismantle),
            20 => Ok(Self::OpenCrafting),
            21 => Ok(Self::OpenTradingPost),
            22 => Ok(Self::OpenAttachment),
            23 => Ok(Self::OpenPrefabRefinery),
            24 => Ok(Self::OpenGenerator),
            25 => Ok(Self::OpenTerritoryMarker),
            26 => Ok(Self::OpenStorage),
            27 => Ok(Self::OpenContracts),
            28 => Ok(Self::TakeAll),
            29 => Ok(Self::ToggleOnOff),
            30 => Ok(Self::RevivePlayer),
            31 => Ok(Self::OpenPaint),
            32 => Ok(Self::OpenLootStorage),
            33 => Ok(Self::Trigger),
            34 => Ok(Self::AddTerritoryClaimTime),
            35 => Ok(Self::OpenInteractScreen),
            36 => Ok(Self::OpenStartClaimScreen),
            37 => Ok(Self::UpgradeBuildable),
            38 => Ok(Self::CancelUpgradeBuildable),
            39 => Ok(Self::IncreaseStructureSecurityLevel),
            40 => Ok(Self::DecreaseStructureSecurityLevel),
            41 => Ok(Self::TakeOverBuildable),
            42 => Ok(Self::SetStructureSecurityLevel),
            43 => Ok(Self::StructureDeposit),
            44 => Ok(Self::StructureWithdraw),
            45 => Ok(Self::StructureDepositUnequip),
            46 => Ok(Self::StructureWithdrawEquip),
            47 => Ok(Self::OpenRead),
            48 => Ok(Self::ModifyStatusEffect),
            49 => Ok(Self::SetStructureName),
            50 => Ok(Self::AddToJournal),
            51 => Ok(Self::OpenObjectiveProvider),
            52 => Ok(Self::UseTurret),
            53 => Ok(Self::InteractWithItemCost),
            54 => Ok(Self::OpenTerritoryInterface),
            55 => Ok(Self::OpenTerritoryProgression),
            56 => Ok(Self::PurchaseClaim),
            57 => Ok(Self::HousingPurchase),
            58 => Ok(Self::HousingEnter),
            59 => Ok(Self::HousingQuickEnter),
            60 => Ok(Self::HousingExit),
            61 => Ok(Self::OpenRaidSetup),
            62 => Ok(Self::OpenTurretSelection),
            63 => Ok(Self::OpenConversation),
            64 => Ok(Self::PlayInteractionAnimation),
            65 => Ok(Self::ObjectiveInteraction),
            66 => Ok(Self::OpenArenaMenu),
            67 => Ok(Self::TeleportToOtherSideOfDoor),
            68 => Ok(Self::UseArenaItem),
            69 => Ok(Self::InteractWithHousingItem),
            70 => Ok(Self::OpenInnScreen),
            71 => Ok(Self::OpenDungeonMenu),
            72 => Ok(Self::EnterDungeon),
            73 => Ok(Self::BindToCamp),
            74 => Ok(Self::ExitDungeon),
            76 => Ok(Self::OpenSummoningSelection),
            77 => Ok(Self::OpenMap),
            78 => Ok(Self::OpenArmory),
            79 => Ok(Self::OpenCampSkins),
            80 => Ok(Self::OpenEventShop),
            85 => Ok(Self::OpenHorseShop),
            86 => Ok(Self::OpenWolfShop),
            87 => Ok(Self::OpenLionShop),
            81 => Ok(Self::PlayCinematicVideo),
            82 => Ok(Self::InteractTeleporter),
            83 => Ok(Self::TipPerformers),
            84 => Ok(Self::EquipGearSet),
            _ => Err(value),
        }
    }
}

impl InteractionUIActions {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Invalid => "INVALID",
            Self::CyclePermissions => "CyclePermissions",
            Self::PickupBuildable => "PickupBuildable",
            Self::RepairBuildable => "RepairBuildable",
            Self::RemoveRespawn => "RemoveRespawn",
            Self::ToggleDoor => "ToggleDoor",
            Self::UseQuickslot1 => "UseQuickslot1",
            Self::UseQuickslot2 => "UseQuickslot2",
            Self::UseQuickslot3 => "UseQuickslot3",
            Self::UseQuickslot4 => "UseQuickslot4",
            Self::UseQuickslot5 => "UseQuickslot5",
            Self::UseQuickslot6 => "UseQuickslot6",
            Self::SelectStructureAttachment => "SelectStructureAttachment",
            Self::SetStructureState => "SetStructureState",
            Self::GatherResource => "GatherResource",
            Self::GatherWaterResource => "GatherWaterResource",
            Self::ApplyAllResources => "ApplyAllResources",
            Self::ApplyResources => "ApplyResources",
            Self::SetSpawnPoint => "SetSpawnPoint",
            Self::Dismantle => "Dismantle",
            Self::OpenCrafting => "OpenCrafting",
            Self::OpenTradingPost => "OpenTradingPost",
            Self::OpenAttachment => "OpenAttachment",
            Self::OpenPrefabRefinery => "OpenPrefabRefinery",
            Self::OpenGenerator => "OpenGenerator",
            Self::OpenTerritoryMarker => "OpenTerritoryMarker",
            Self::OpenStorage => "OpenStorage",
            Self::OpenContracts => "OpenContracts",
            Self::TakeAll => "TakeAll",
            Self::ToggleOnOff => "ToggleOnOff",
            Self::RevivePlayer => "RevivePlayer",
            Self::OpenPaint => "OpenPaint",
            Self::OpenLootStorage => "OpenLootStorage",
            Self::Trigger => "Trigger",
            Self::AddTerritoryClaimTime => "AddTerritoryClaimTime",
            Self::OpenInteractScreen => "OpenInteractScreen",
            Self::OpenStartClaimScreen => "OpenStartClaimScreen",
            Self::UpgradeBuildable => "UpgradeBuildable",
            Self::CancelUpgradeBuildable => "CancelUpgradeBuildable",
            Self::IncreaseStructureSecurityLevel => "IncreaseStructureSecurityLevel",
            Self::DecreaseStructureSecurityLevel => "DecreaseStructureSecurityLevel",
            Self::TakeOverBuildable => "TakeOverBuildable",
            Self::SetStructureSecurityLevel => "SetStructureSecurityLevel",
            Self::StructureDeposit => "StructureDeposit",
            Self::StructureWithdraw => "StructureWithdraw",
            Self::StructureDepositUnequip => "StructureDepositUnequip",
            Self::StructureWithdrawEquip => "StructureWithdrawEquip",
            Self::OpenRead => "OpenRead",
            Self::ModifyStatusEffect => "ModifyStatusEffect",
            Self::SetStructureName => "SetStructureName",
            Self::AddToJournal => "AddToJournal",
            Self::OpenObjectiveProvider => "OpenObjectiveProvider",
            Self::UseTurret => "UseTurret",
            Self::InteractWithItemCost => "InteractWithItemCost",
            Self::OpenTerritoryInterface => "OpenTerritoryInterface",
            Self::OpenTerritoryProgression => "OpenTerritoryProgression",
            Self::PurchaseClaim => "PurchaseClaim",
            Self::HousingPurchase => "HousingPurchase",
            Self::HousingEnter => "HousingEnter",
            Self::HousingQuickEnter => "HousingQuickEnter",
            Self::HousingExit => "HousingExit",
            Self::OpenRaidSetup => "OpenRaidSetup",
            Self::OpenTurretSelection => "OpenTurretSelection",
            Self::OpenConversation => "OpenConversation",
            Self::PlayInteractionAnimation => "PlayInteractionAnimation",
            Self::ObjectiveInteraction => "ObjectiveInteraction",
            Self::OpenArenaMenu => "OpenArenaMenu",
            Self::TeleportToOtherSideOfDoor => "TeleportToOtherSideOfDoor",
            Self::UseArenaItem => "UseArenaItem",
            Self::InteractWithHousingItem => "InteractWithHousingItem",
            Self::OpenInnScreen => "OpenInnScreen",
            Self::OpenDungeonMenu => "OpenDungeonMenu",
            Self::EnterDungeon => "EnterDungeon",
            Self::BindToCamp => "BindToCamp",
            Self::ExitDungeon => "ExitDungeon",
            Self::OpenSummoningSelection => "OpenSummoningSelection",
            Self::OpenMap => "OpenMap",
            Self::OpenArmory => "OpenArmory",
            Self::OpenCampSkins => "OpenCampSkins",
            Self::OpenEventShop => "OpenEventShop",
            Self::OpenHorseShop => "OpenHorseShop",
            Self::OpenWolfShop => "OpenWolfShop",
            Self::OpenLionShop => "OpenLionShop",
            Self::PlayCinematicVideo => "PlayCinematicVideo",
            Self::InteractTeleporter => "InteractTeleporter",
            Self::TipPerformers => "TipPerformers",
            Self::EquipGearSet => "EquipGearSet",
        }
    }
}

impl AsRef<str> for InteractionUIActions {
    fn as_ref(&self) -> &str {
        (*self).as_str()
    }
}

impl<'a> ::core::convert::TryFrom<&'a str> for InteractionUIActions {
    type Error = &'a str;
    fn try_from(value: &'a str) -> Result<Self, &'a str> {
        match value {
            "INVALID" => Ok(Self::Invalid),
            "CyclePermissions" => Ok(Self::CyclePermissions),
            "PickupBuildable" => Ok(Self::PickupBuildable),
            "RepairBuildable" => Ok(Self::RepairBuildable),
            "RemoveRespawn" => Ok(Self::RemoveRespawn),
            "ToggleDoor" => Ok(Self::ToggleDoor),
            "UseQuickslot1" => Ok(Self::UseQuickslot1),
            "UseQuickslot2" => Ok(Self::UseQuickslot2),
            "UseQuickslot3" => Ok(Self::UseQuickslot3),
            "UseQuickslot4" => Ok(Self::UseQuickslot4),
            "UseQuickslot5" => Ok(Self::UseQuickslot5),
            "UseQuickslot6" => Ok(Self::UseQuickslot6),
            "SelectStructureAttachment" => Ok(Self::SelectStructureAttachment),
            "SetStructureState" => Ok(Self::SetStructureState),
            "GatherResource" => Ok(Self::GatherResource),
            "GatherWaterResource" => Ok(Self::GatherWaterResource),
            "ApplyAllResources" => Ok(Self::ApplyAllResources),
            "ApplyResources" => Ok(Self::ApplyResources),
            "SetSpawnPoint" => Ok(Self::SetSpawnPoint),
            "Dismantle" => Ok(Self::Dismantle),
            "OpenCrafting" => Ok(Self::OpenCrafting),
            "OpenTradingPost" => Ok(Self::OpenTradingPost),
            "OpenAttachment" => Ok(Self::OpenAttachment),
            "OpenPrefabRefinery" => Ok(Self::OpenPrefabRefinery),
            "OpenGenerator" => Ok(Self::OpenGenerator),
            "OpenTerritoryMarker" => Ok(Self::OpenTerritoryMarker),
            "OpenStorage" => Ok(Self::OpenStorage),
            "OpenContracts" => Ok(Self::OpenContracts),
            "TakeAll" => Ok(Self::TakeAll),
            "ToggleOnOff" => Ok(Self::ToggleOnOff),
            "RevivePlayer" => Ok(Self::RevivePlayer),
            "OpenPaint" => Ok(Self::OpenPaint),
            "OpenLootStorage" => Ok(Self::OpenLootStorage),
            "Trigger" => Ok(Self::Trigger),
            "AddTerritoryClaimTime" => Ok(Self::AddTerritoryClaimTime),
            "OpenInteractScreen" => Ok(Self::OpenInteractScreen),
            "OpenStartClaimScreen" => Ok(Self::OpenStartClaimScreen),
            "UpgradeBuildable" => Ok(Self::UpgradeBuildable),
            "CancelUpgradeBuildable" => Ok(Self::CancelUpgradeBuildable),
            "IncreaseStructureSecurityLevel" => Ok(Self::IncreaseStructureSecurityLevel),
            "DecreaseStructureSecurityLevel" => Ok(Self::DecreaseStructureSecurityLevel),
            "TakeOverBuildable" => Ok(Self::TakeOverBuildable),
            "SetStructureSecurityLevel" => Ok(Self::SetStructureSecurityLevel),
            "StructureDeposit" => Ok(Self::StructureDeposit),
            "StructureWithdraw" => Ok(Self::StructureWithdraw),
            "StructureDepositUnequip" => Ok(Self::StructureDepositUnequip),
            "StructureWithdrawEquip" => Ok(Self::StructureWithdrawEquip),
            "OpenRead" => Ok(Self::OpenRead),
            "ModifyStatusEffect" => Ok(Self::ModifyStatusEffect),
            "SetStructureName" => Ok(Self::SetStructureName),
            "AddToJournal" => Ok(Self::AddToJournal),
            "OpenObjectiveProvider" => Ok(Self::OpenObjectiveProvider),
            "UseTurret" => Ok(Self::UseTurret),
            "InteractWithItemCost" => Ok(Self::InteractWithItemCost),
            "OpenTerritoryInterface" => Ok(Self::OpenTerritoryInterface),
            "OpenTerritoryProgression" => Ok(Self::OpenTerritoryProgression),
            "PurchaseClaim" => Ok(Self::PurchaseClaim),
            "HousingPurchase" => Ok(Self::HousingPurchase),
            "HousingEnter" => Ok(Self::HousingEnter),
            "HousingQuickEnter" => Ok(Self::HousingQuickEnter),
            "HousingExit" => Ok(Self::HousingExit),
            "OpenRaidSetup" => Ok(Self::OpenRaidSetup),
            "OpenTurretSelection" => Ok(Self::OpenTurretSelection),
            "OpenConversation" => Ok(Self::OpenConversation),
            "PlayInteractionAnimation" => Ok(Self::PlayInteractionAnimation),
            "ObjectiveInteraction" => Ok(Self::ObjectiveInteraction),
            "OpenArenaMenu" => Ok(Self::OpenArenaMenu),
            "TeleportToOtherSideOfDoor" => Ok(Self::TeleportToOtherSideOfDoor),
            "UseArenaItem" => Ok(Self::UseArenaItem),
            "InteractWithHousingItem" => Ok(Self::InteractWithHousingItem),
            "OpenInnScreen" => Ok(Self::OpenInnScreen),
            "OpenDungeonMenu" => Ok(Self::OpenDungeonMenu),
            "EnterDungeon" => Ok(Self::EnterDungeon),
            "BindToCamp" => Ok(Self::BindToCamp),
            "ExitDungeon" => Ok(Self::ExitDungeon),
            "OpenSummoningSelection" => Ok(Self::OpenSummoningSelection),
            "OpenMap" => Ok(Self::OpenMap),
            "OpenArmory" => Ok(Self::OpenArmory),
            "OpenCampSkins" => Ok(Self::OpenCampSkins),
            "OpenEventShop" => Ok(Self::OpenEventShop),
            "OpenHorseShop" => Ok(Self::OpenHorseShop),
            "OpenWolfShop" => Ok(Self::OpenWolfShop),
            "OpenLionShop" => Ok(Self::OpenLionShop),
            "PlayCinematicVideo" => Ok(Self::PlayCinematicVideo),
            "InteractTeleporter" => Ok(Self::InteractTeleporter),
            "TipPerformers" => Ok(Self::TipPerformers),
            "EquipGearSet" => Ok(Self::EquipGearSet),
            _ => Err(value),
        }
    }
}

impl ::core::str::FromStr for InteractionUIActions {
    type Err = ::std::string::String;
    fn from_str(value: &str) -> Result<Self, Self::Err> {
        Self::try_from(value).map_err(str::to_owned)
    }
}

impl ::core::fmt::Display for InteractionUIActions {
    fn fmt(&self, formatter: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        formatter.write_str((*self).as_str())
    }
}

impl AzRtti for InteractionUIActions {
    const NAME: &'static str = "InteractionUIActions";
    const TYPE_ID: AzUuid = AzUuid::from_u128(0xFFA571CE_73A6_4246_A120_440EF0DC493D);
}
