use crate::az::rtti::AzRtti;
use crate::az::uuid::Uuid as AzUuid;
use bevy_reflect::{ReflectDeserialize, ReflectSerialize};

#[derive(
    Debug,
    Default,
    Clone,
    Copy,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Hash,
    serde::Serialize,
    serde::Deserialize,
    bevy_reflect::Reflect,
)]
#[repr(i32)]
#[serde(try_from = "i32", into = "i32")]
#[reflect(Serialize, Deserialize)]
pub enum PaperdollSlotAlias {
    #[default]
    HeadSlot = 0,
    ChestSlot = 1,
    HandsSlot = 2,
    LegsSlot = 3,
    FeetSlot = 4,
    AmuletSlot = 5,
    TokenSlot = 6,
    RingSlot = 7,
    PaintSlot = 8,
    GatherableHandSlot = 9,
    OffHandSlot = 10,
    TwoHandSlot = 11,
    ArrowAmmoSlot = 12,
    CartridgeAmmoSlot = 13,
    QuickSlot1 = 14,
    QuickSlot2 = 15,
    QuickSlot3 = 16,
    QuickSlot4 = 17,
    QuickSlot5 = 18,
    QuickSlot6 = 19,
    BackpackSlot = 20,
    MouthSlot = 21,
    SaddleSlot = 22,
    BridleSlot = 23,
    MainHandOption1 = 24,
    MainHandOption2 = 25,
    MainHandOption3 = 26,
    OffHandOption1 = 27,
    OffHandOption2 = 28,
    OffHandOption3 = 29,
    BagSlot1 = 30,
    BagSlot2 = 31,
    BagSlot3 = 32,
    ChoppingSlot = 33,
    CuttingSlot = 34,
    DressingSlot = 35,
    MiningSlot = 36,
    FishingSlot = 37,
    AzothstaffSlot = 38,
    InstrumentFluteSlot = 39,
    InstrumentGuitarSlot = 40,
    InstrumentMandolinSlot = 41,
    InstrumentUprightbassSlot = 42,
    InstrumentDrumsSlot = 43,
    ThrowableObjectSlot = 44,
    HeartGemSlot = 45,
    MountBuff1 = 46,
    MountBuff2 = 47,
    MountAttachment1 = 48,
    MountAttachment2 = 49,
    ActiveWeapon = 50,
    InactiveWeapon = 51,
    ActiveMainHandWeapon = 52,
    NextMainHandWeapon = 53,
    PrevMainHandWeapon = 54,
    ActiveOffHandWeapon = 55,
    NextOffHandWeapon = 56,
    PrevOffHandWeapon = 57,
    ToolSlot = 58,
    ActiveRuneSlot = 59,
    NumSlots = 60,
}

impl From<PaperdollSlotAlias> for i32 {
    fn from(value: PaperdollSlotAlias) -> Self {
        match value {
            PaperdollSlotAlias::HeadSlot => 0,
            PaperdollSlotAlias::ChestSlot => 1,
            PaperdollSlotAlias::HandsSlot => 2,
            PaperdollSlotAlias::LegsSlot => 3,
            PaperdollSlotAlias::FeetSlot => 4,
            PaperdollSlotAlias::AmuletSlot => 5,
            PaperdollSlotAlias::TokenSlot => 6,
            PaperdollSlotAlias::RingSlot => 7,
            PaperdollSlotAlias::PaintSlot => 8,
            PaperdollSlotAlias::GatherableHandSlot => 9,
            PaperdollSlotAlias::OffHandSlot => 10,
            PaperdollSlotAlias::TwoHandSlot => 11,
            PaperdollSlotAlias::ArrowAmmoSlot => 12,
            PaperdollSlotAlias::CartridgeAmmoSlot => 13,
            PaperdollSlotAlias::QuickSlot1 => 14,
            PaperdollSlotAlias::QuickSlot2 => 15,
            PaperdollSlotAlias::QuickSlot3 => 16,
            PaperdollSlotAlias::QuickSlot4 => 17,
            PaperdollSlotAlias::QuickSlot5 => 18,
            PaperdollSlotAlias::QuickSlot6 => 19,
            PaperdollSlotAlias::BackpackSlot => 20,
            PaperdollSlotAlias::MouthSlot => 21,
            PaperdollSlotAlias::SaddleSlot => 22,
            PaperdollSlotAlias::BridleSlot => 23,
            PaperdollSlotAlias::MainHandOption1 => 24,
            PaperdollSlotAlias::MainHandOption2 => 25,
            PaperdollSlotAlias::MainHandOption3 => 26,
            PaperdollSlotAlias::OffHandOption1 => 27,
            PaperdollSlotAlias::OffHandOption2 => 28,
            PaperdollSlotAlias::OffHandOption3 => 29,
            PaperdollSlotAlias::BagSlot1 => 30,
            PaperdollSlotAlias::BagSlot2 => 31,
            PaperdollSlotAlias::BagSlot3 => 32,
            PaperdollSlotAlias::ChoppingSlot => 33,
            PaperdollSlotAlias::CuttingSlot => 34,
            PaperdollSlotAlias::DressingSlot => 35,
            PaperdollSlotAlias::MiningSlot => 36,
            PaperdollSlotAlias::FishingSlot => 37,
            PaperdollSlotAlias::AzothstaffSlot => 38,
            PaperdollSlotAlias::InstrumentFluteSlot => 39,
            PaperdollSlotAlias::InstrumentGuitarSlot => 40,
            PaperdollSlotAlias::InstrumentMandolinSlot => 41,
            PaperdollSlotAlias::InstrumentUprightbassSlot => 42,
            PaperdollSlotAlias::InstrumentDrumsSlot => 43,
            PaperdollSlotAlias::ThrowableObjectSlot => 44,
            PaperdollSlotAlias::HeartGemSlot => 45,
            PaperdollSlotAlias::MountBuff1 => 46,
            PaperdollSlotAlias::MountBuff2 => 47,
            PaperdollSlotAlias::MountAttachment1 => 48,
            PaperdollSlotAlias::MountAttachment2 => 49,
            PaperdollSlotAlias::ActiveWeapon => 50,
            PaperdollSlotAlias::InactiveWeapon => 51,
            PaperdollSlotAlias::ActiveMainHandWeapon => 52,
            PaperdollSlotAlias::NextMainHandWeapon => 53,
            PaperdollSlotAlias::PrevMainHandWeapon => 54,
            PaperdollSlotAlias::ActiveOffHandWeapon => 55,
            PaperdollSlotAlias::NextOffHandWeapon => 56,
            PaperdollSlotAlias::PrevOffHandWeapon => 57,
            PaperdollSlotAlias::ToolSlot => 58,
            PaperdollSlotAlias::ActiveRuneSlot => 59,
            PaperdollSlotAlias::NumSlots => 60,
        }
    }
}

impl ::core::convert::TryFrom<i32> for PaperdollSlotAlias {
    type Error = i32;
    fn try_from(value: i32) -> Result<Self, i32> {
        match value {
            0 => Ok(Self::HeadSlot),
            1 => Ok(Self::ChestSlot),
            2 => Ok(Self::HandsSlot),
            3 => Ok(Self::LegsSlot),
            4 => Ok(Self::FeetSlot),
            5 => Ok(Self::AmuletSlot),
            6 => Ok(Self::TokenSlot),
            7 => Ok(Self::RingSlot),
            8 => Ok(Self::PaintSlot),
            9 => Ok(Self::GatherableHandSlot),
            10 => Ok(Self::OffHandSlot),
            11 => Ok(Self::TwoHandSlot),
            12 => Ok(Self::ArrowAmmoSlot),
            13 => Ok(Self::CartridgeAmmoSlot),
            14 => Ok(Self::QuickSlot1),
            15 => Ok(Self::QuickSlot2),
            16 => Ok(Self::QuickSlot3),
            17 => Ok(Self::QuickSlot4),
            18 => Ok(Self::QuickSlot5),
            19 => Ok(Self::QuickSlot6),
            20 => Ok(Self::BackpackSlot),
            21 => Ok(Self::MouthSlot),
            22 => Ok(Self::SaddleSlot),
            23 => Ok(Self::BridleSlot),
            24 => Ok(Self::MainHandOption1),
            25 => Ok(Self::MainHandOption2),
            26 => Ok(Self::MainHandOption3),
            27 => Ok(Self::OffHandOption1),
            28 => Ok(Self::OffHandOption2),
            29 => Ok(Self::OffHandOption3),
            30 => Ok(Self::BagSlot1),
            31 => Ok(Self::BagSlot2),
            32 => Ok(Self::BagSlot3),
            33 => Ok(Self::ChoppingSlot),
            34 => Ok(Self::CuttingSlot),
            35 => Ok(Self::DressingSlot),
            36 => Ok(Self::MiningSlot),
            37 => Ok(Self::FishingSlot),
            38 => Ok(Self::AzothstaffSlot),
            39 => Ok(Self::InstrumentFluteSlot),
            40 => Ok(Self::InstrumentGuitarSlot),
            41 => Ok(Self::InstrumentMandolinSlot),
            42 => Ok(Self::InstrumentUprightbassSlot),
            43 => Ok(Self::InstrumentDrumsSlot),
            44 => Ok(Self::ThrowableObjectSlot),
            45 => Ok(Self::HeartGemSlot),
            46 => Ok(Self::MountBuff1),
            47 => Ok(Self::MountBuff2),
            48 => Ok(Self::MountAttachment1),
            49 => Ok(Self::MountAttachment2),
            50 => Ok(Self::ActiveWeapon),
            51 => Ok(Self::InactiveWeapon),
            52 => Ok(Self::ActiveMainHandWeapon),
            53 => Ok(Self::NextMainHandWeapon),
            54 => Ok(Self::PrevMainHandWeapon),
            55 => Ok(Self::ActiveOffHandWeapon),
            56 => Ok(Self::NextOffHandWeapon),
            57 => Ok(Self::PrevOffHandWeapon),
            58 => Ok(Self::ToolSlot),
            59 => Ok(Self::ActiveRuneSlot),
            60 => Ok(Self::NumSlots),
            _ => Err(value),
        }
    }
}

impl PaperdollSlotAlias {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::HeadSlot => "HEAD_SLOT",
            Self::ChestSlot => "CHEST_SLOT",
            Self::HandsSlot => "HANDS_SLOT",
            Self::LegsSlot => "LEGS_SLOT",
            Self::FeetSlot => "FEET_SLOT",
            Self::AmuletSlot => "AMULET_SLOT",
            Self::TokenSlot => "TOKEN_SLOT",
            Self::RingSlot => "RING_SLOT",
            Self::PaintSlot => "PAINT_SLOT",
            Self::GatherableHandSlot => "GATHERABLE_HAND_SLOT",
            Self::OffHandSlot => "OFF_HAND_SLOT",
            Self::TwoHandSlot => "TWO_HAND_SLOT",
            Self::ArrowAmmoSlot => "ARROW_AMMO_SLOT",
            Self::CartridgeAmmoSlot => "CARTRIDGE_AMMO_SLOT",
            Self::QuickSlot1 => "QUICK_SLOT_1",
            Self::QuickSlot2 => "QUICK_SLOT_2",
            Self::QuickSlot3 => "QUICK_SLOT_3",
            Self::QuickSlot4 => "QUICK_SLOT_4",
            Self::QuickSlot5 => "QUICK_SLOT_5",
            Self::QuickSlot6 => "QUICK_SLOT_6",
            Self::BackpackSlot => "BACKPACK_SLOT",
            Self::MouthSlot => "MOUTH_SLOT",
            Self::SaddleSlot => "SADDLE_SLOT",
            Self::BridleSlot => "BRIDLE_SLOT",
            Self::MainHandOption1 => "MAIN_HAND_OPTION_1",
            Self::MainHandOption2 => "MAIN_HAND_OPTION_2",
            Self::MainHandOption3 => "MAIN_HAND_OPTION_3",
            Self::OffHandOption1 => "OFF_HAND_OPTION_1",
            Self::OffHandOption2 => "OFF_HAND_OPTION_2",
            Self::OffHandOption3 => "OFF_HAND_OPTION_3",
            Self::BagSlot1 => "BAG_SLOT_1",
            Self::BagSlot2 => "BAG_SLOT_2",
            Self::BagSlot3 => "BAG_SLOT_3",
            Self::ChoppingSlot => "CHOPPING_SLOT",
            Self::CuttingSlot => "CUTTING_SLOT",
            Self::DressingSlot => "DRESSING_SLOT",
            Self::MiningSlot => "MINING_SLOT",
            Self::FishingSlot => "FISHING_SLOT",
            Self::AzothstaffSlot => "AZOTHSTAFF_SLOT",
            Self::InstrumentFluteSlot => "INSTRUMENT_FLUTE_SLOT",
            Self::InstrumentGuitarSlot => "INSTRUMENT_GUITAR_SLOT",
            Self::InstrumentMandolinSlot => "INSTRUMENT_MANDOLIN_SLOT",
            Self::InstrumentUprightbassSlot => "INSTRUMENT_UPRIGHTBASS_SLOT",
            Self::InstrumentDrumsSlot => "INSTRUMENT_DRUMS_SLOT",
            Self::ThrowableObjectSlot => "THROWABLE_OBJECT_SLOT",
            Self::HeartGemSlot => "HEART_GEM_SLOT",
            Self::MountBuff1 => "MOUNT_BUFF_1",
            Self::MountBuff2 => "MOUNT_BUFF_2",
            Self::MountAttachment1 => "MOUNT_ATTACHMENT_1",
            Self::MountAttachment2 => "MOUNT_ATTACHMENT_2",
            Self::ActiveWeapon => "ACTIVE_WEAPON",
            Self::InactiveWeapon => "INACTIVE_WEAPON",
            Self::ActiveMainHandWeapon => "ACTIVE_MAIN_HAND_WEAPON",
            Self::NextMainHandWeapon => "NEXT_MAIN_HAND_WEAPON",
            Self::PrevMainHandWeapon => "PREV_MAIN_HAND_WEAPON",
            Self::ActiveOffHandWeapon => "ACTIVE_OFF_HAND_WEAPON",
            Self::NextOffHandWeapon => "NEXT_OFF_HAND_WEAPON",
            Self::PrevOffHandWeapon => "PREV_OFF_HAND_WEAPON",
            Self::ToolSlot => "TOOL_SLOT",
            Self::ActiveRuneSlot => "ACTIVE_RUNE_SLOT",
            Self::NumSlots => "NUM_SLOTS",
        }
    }
}

impl AsRef<str> for PaperdollSlotAlias {
    fn as_ref(&self) -> &str {
        (*self).as_str()
    }
}

impl<'a> ::core::convert::TryFrom<&'a str> for PaperdollSlotAlias {
    type Error = &'a str;
    fn try_from(value: &'a str) -> Result<Self, &'a str> {
        match value {
            "HEAD_SLOT" => Ok(Self::HeadSlot),
            "CHEST_SLOT" => Ok(Self::ChestSlot),
            "HANDS_SLOT" => Ok(Self::HandsSlot),
            "LEGS_SLOT" => Ok(Self::LegsSlot),
            "FEET_SLOT" => Ok(Self::FeetSlot),
            "AMULET_SLOT" => Ok(Self::AmuletSlot),
            "TOKEN_SLOT" => Ok(Self::TokenSlot),
            "RING_SLOT" => Ok(Self::RingSlot),
            "PAINT_SLOT" => Ok(Self::PaintSlot),
            "GATHERABLE_HAND_SLOT" => Ok(Self::GatherableHandSlot),
            "OFF_HAND_SLOT" => Ok(Self::OffHandSlot),
            "TWO_HAND_SLOT" => Ok(Self::TwoHandSlot),
            "ARROW_AMMO_SLOT" => Ok(Self::ArrowAmmoSlot),
            "CARTRIDGE_AMMO_SLOT" => Ok(Self::CartridgeAmmoSlot),
            "QUICK_SLOT_1" => Ok(Self::QuickSlot1),
            "QUICK_SLOT_2" => Ok(Self::QuickSlot2),
            "QUICK_SLOT_3" => Ok(Self::QuickSlot3),
            "QUICK_SLOT_4" => Ok(Self::QuickSlot4),
            "QUICK_SLOT_5" => Ok(Self::QuickSlot5),
            "QUICK_SLOT_6" => Ok(Self::QuickSlot6),
            "BACKPACK_SLOT" => Ok(Self::BackpackSlot),
            "MOUTH_SLOT" => Ok(Self::MouthSlot),
            "SADDLE_SLOT" => Ok(Self::SaddleSlot),
            "BRIDLE_SLOT" => Ok(Self::BridleSlot),
            "MAIN_HAND_OPTION_1" => Ok(Self::MainHandOption1),
            "MAIN_HAND_OPTION_2" => Ok(Self::MainHandOption2),
            "MAIN_HAND_OPTION_3" => Ok(Self::MainHandOption3),
            "OFF_HAND_OPTION_1" => Ok(Self::OffHandOption1),
            "OFF_HAND_OPTION_2" => Ok(Self::OffHandOption2),
            "OFF_HAND_OPTION_3" => Ok(Self::OffHandOption3),
            "BAG_SLOT_1" => Ok(Self::BagSlot1),
            "BAG_SLOT_2" => Ok(Self::BagSlot2),
            "BAG_SLOT_3" => Ok(Self::BagSlot3),
            "CHOPPING_SLOT" => Ok(Self::ChoppingSlot),
            "CUTTING_SLOT" => Ok(Self::CuttingSlot),
            "DRESSING_SLOT" => Ok(Self::DressingSlot),
            "MINING_SLOT" => Ok(Self::MiningSlot),
            "FISHING_SLOT" => Ok(Self::FishingSlot),
            "AZOTHSTAFF_SLOT" => Ok(Self::AzothstaffSlot),
            "INSTRUMENT_FLUTE_SLOT" => Ok(Self::InstrumentFluteSlot),
            "INSTRUMENT_GUITAR_SLOT" => Ok(Self::InstrumentGuitarSlot),
            "INSTRUMENT_MANDOLIN_SLOT" => Ok(Self::InstrumentMandolinSlot),
            "INSTRUMENT_UPRIGHTBASS_SLOT" => Ok(Self::InstrumentUprightbassSlot),
            "INSTRUMENT_DRUMS_SLOT" => Ok(Self::InstrumentDrumsSlot),
            "THROWABLE_OBJECT_SLOT" => Ok(Self::ThrowableObjectSlot),
            "HEART_GEM_SLOT" => Ok(Self::HeartGemSlot),
            "MOUNT_BUFF_1" => Ok(Self::MountBuff1),
            "MOUNT_BUFF_2" => Ok(Self::MountBuff2),
            "MOUNT_ATTACHMENT_1" => Ok(Self::MountAttachment1),
            "MOUNT_ATTACHMENT_2" => Ok(Self::MountAttachment2),
            "ACTIVE_WEAPON" => Ok(Self::ActiveWeapon),
            "INACTIVE_WEAPON" => Ok(Self::InactiveWeapon),
            "ACTIVE_MAIN_HAND_WEAPON" => Ok(Self::ActiveMainHandWeapon),
            "NEXT_MAIN_HAND_WEAPON" => Ok(Self::NextMainHandWeapon),
            "PREV_MAIN_HAND_WEAPON" => Ok(Self::PrevMainHandWeapon),
            "ACTIVE_OFF_HAND_WEAPON" => Ok(Self::ActiveOffHandWeapon),
            "NEXT_OFF_HAND_WEAPON" => Ok(Self::NextOffHandWeapon),
            "PREV_OFF_HAND_WEAPON" => Ok(Self::PrevOffHandWeapon),
            "TOOL_SLOT" => Ok(Self::ToolSlot),
            "ACTIVE_RUNE_SLOT" => Ok(Self::ActiveRuneSlot),
            "NUM_SLOTS" => Ok(Self::NumSlots),
            _ => Err(value),
        }
    }
}

impl ::core::str::FromStr for PaperdollSlotAlias {
    type Err = ::std::string::String;
    fn from_str(value: &str) -> Result<Self, Self::Err> {
        Self::try_from(value).map_err(str::to_owned)
    }
}

impl ::core::fmt::Display for PaperdollSlotAlias {
    fn fmt(&self, formatter: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        formatter.write_str((*self).as_str())
    }
}

impl AzRtti for PaperdollSlotAlias {
    const NAME: &'static str = "PaperdollSlotAlias";
    const TYPE_ID: AzUuid = AzUuid::from_u128(0x03DF74AF_A34C_45DB_8CFC_B33BDF78EBF2);
}
