[package]
name = "cry-mannequin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
description = "Streaming parsers for CryAction Mannequin metadata assets"

[lints]
workspace = true

[dependencies]
nw-asset.workspace = true
nw-reflected-types.workspace = true
quick-xml = { workspace = true }
ron = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
