//! The gridmate wire enumeration a crate owes a composing host.
//!
//! `#[derive(ClassDesc)]`, `#[derive(Message)]`, and
//! `#[derive(ReplicatedState)]` no longer register anything. A derive says what
//! a type *is*; it cannot say which host wants it, and a link-time submission
//! answered that by accident — whichever crates the linker happened to keep.
//! The crate that declares the type publishes it instead, by handing
//! `ClassRegistration` / `FragmentRegistration` / `DebugIntrospect` entries to a
//! contribution's registrar.
//!
//! For a hand-written tree the size of the New World runtime that is ~1,900
//! entries, so this pass writes them: it scans each file for the three derives,
//! renders a marked block into the module that declares the types, and chains
//! every module's arrays up its `mod.rs` parents into one crate-root
//! `register`. The block is emitted *in the declaring module* because the
//! entries name types by bare ident — and because `pub(crate)` inside a private
//! nested module is not reachable from the crate root, so a flat crate-root
//! list could not name half of them.
//!
//! Nothing here scans for types at compose time: the rendered arrays *are* the
//! enumeration. A type that is declared and never listed is simply absent from
//! the host, which is what the audit's declared-but-not-enumerated status
//! exists to catch.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use crate::CodegenContext;
use crate::rust::integrate::identity::{ScannedComponent, scan_component_structs};

use super::{RustIntegrationError, collect_rust_files};

/// Opening line of the block this pass owns. Everything between it and
/// [`END`] is rewritten on every run; everything outside is the author's.
const BEGIN: &str = "// gridmate wire registration — generated by nw-serialize-codegen";
const END: &str = "// end gridmate wire registration";

const CLASS: &str = "::gridmate::az::ClassRegistration";
const FRAGMENT: &str = "::gridmate::hub::FragmentRegistration";
const INTROSPECT: &str = "::gridmate::az::DebugIntrospect";

/// Which class-registry constructor a declared type takes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WireKind {
    /// `#[derive(Message)]` — `ClassRegistration::of_message`, plus a debug
    /// introspector. Carries the envelope index and protocol metadata a
    /// class-only entry has none of.
    Message,
    /// `#[derive(ClassDesc)]` without `Message` — `ClassRegistration::of`.
    Class,
}

/// One declared type and the entries it owes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireType {
    pub name: String,
    pub kind: WireKind,
    /// `#[derive(ReplicatedState)]` alongside `ClassDesc`: the type is also a
    /// concrete replication fragment.
    pub fragment: bool,
}

/// A type that derives wire registration and that no site can name.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireSkip {
    pub name: String,
    pub path: PathBuf,
    pub reason: WireSkipReason,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum WireSkipReason {
    /// Generic types have no single registration site: the entry constructors
    /// are monomorphic and the scanner has no argument list to supply.
    Generic,
    /// `ReplicatedState` without `ClassDesc`. `FragmentRegistration::of`
    /// requires `Class`, so the type has no `type_index` to be keyed on. The
    /// old derive skipped these silently; naming them is the point.
    FragmentWithoutClass,
}

impl std::fmt::Display for WireSkipReason {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Generic => f.write_str("generic type"),
            Self::FragmentWithoutClass => f.write_str("ReplicatedState without ClassDesc"),
        }
    }
}

/// One `mod` declaration in a module's own source, resolved to the node it
/// names.
///
/// Declared rather than read off the directory tree, because the two disagree
/// exactly where it matters. `#[path]` moves a file into a module the layout
/// does not imply, and `#[cfg]` decides whether the module exists in *this*
/// compile at all — so a chain built from the file tree calls modules a feature
/// set removed, and a crate that gates its modules on capabilities stops
/// compiling the moment the enumeration lands.
#[derive(Debug, Clone, PartialEq, Eq)]
struct Child {
    /// The name the parent calls it by; `#[path]` decouples this from the file.
    name: String,
    /// Module path of the node this declaration resolves to.
    target: Vec<String>,
    /// The declaration's own `#[cfg(...)]` attributes, verbatim. The chained
    /// call carries them, so the call exists exactly when the module does.
    cfgs: Vec<String>,
}

/// The rewritten source for one module, ready to write.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireFile {
    pub path: PathBuf,
    pub source: String,
    pub classes: usize,
    pub fragments: usize,
    pub introspects: usize,
}

/// What a crate declares and what its emitted blocks enumerate.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct WirePlan {
    pub files: Vec<WireFile>,
    /// Types carrying one of the three derives, by name.
    pub declared: BTreeMap<String, PathBuf>,
    /// Types the rendered blocks name. A declared type outside this set reaches
    /// no host.
    pub enumerated: BTreeSet<String>,
    pub skipped: Vec<WireSkip>,
    /// Enumerated types that claim a wire identity another one already claims.
    pub clashes: Vec<WireClash>,
}

/// Two or more enumerated types claiming one wire identity.
///
/// A composing host catches this at `finalize`, but only the first pair it
/// reaches: fail-fast means a tree with five collisions costs five
/// compile-and-test cycles to uncover, one at a time. The pass sees every
/// declaration at once, so it names all of them before a line is emitted.
///
/// Under the retired `inventory` registration nothing caught it at all — the
/// collision resolved by link order, silently, and whichever type lost simply
/// never decoded.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireClash {
    /// The registry key it collides on: `az-uuid` or `type-index`.
    pub axis: &'static str,
    pub key: String,
    /// The claiming types, in scan order.
    pub types: Vec<String>,
}

impl fmt::Display for WireClash {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            formatter,
            "{} {} claimed by {}",
            self.axis,
            self.key,
            self.types.join(", ")
        )
    }
}

impl WirePlan {
    /// Declared types that no rendered block names, in scan order.
    #[must_use]
    pub fn unenumerated(&self) -> Vec<&str> {
        self.declared
            .keys()
            .filter(|name| !self.enumerated.contains(*name))
            .map(String::as_str)
            .collect()
    }

    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.files.is_empty()
    }
}

/// Scan `root` and render every module's wire enumeration.
///
/// `root` is a crate's `src` directory: the crate root is its `lib.rs` (or
/// `main.rs`), and that is the only module that gets a public `register`.
pub fn plan(root: &Path, context: &CodegenContext) -> Result<WirePlan, RustIntegrationError> {
    let mut paths = Vec::new();
    collect_rust_files(root, &mut paths)?;
    paths.sort();

    let scans = context.runner().try_map(&paths, |path| {
        let text = fs::read_to_string(path).map_err(|source| RustIntegrationError::Read {
            path: path.clone(),
            source,
        })?;
        let scanned = scan_component_structs(&text, path);
        Ok(FileScan {
            path: path.clone(),
            text,
            scanned,
        })
    })?;

    let mut nodes = BTreeMap::<Vec<String>, Node>::new();
    let mut plan = WirePlan::default();
    let mut uuids = BTreeMap::<String, Vec<String>>::new();
    let mut indices = BTreeMap::<String, Vec<String>>::new();
    for scan in &scans {
        let Some(module_path) = module_path(root, &scan.path) else {
            continue;
        };
        let mut types = Vec::new();
        let handwritten = hand_fragments(&scan.text);
        let claimed = identities(&scan.text)
            .into_iter()
            .map(|(name, uuid, index)| (name, (uuid, index)))
            .collect::<BTreeMap<_, _>>();
        for component in &scan.scanned {
            match classify(component) {
                Classified::Wire(mut wire) => {
                    wire.fragment |= handwritten.contains(&wire.name);
                    if let Some((uuid, index)) = claimed.get(&wire.name) {
                        if let Some(uuid) = uuid {
                            uuids
                                .entry(uuid.to_ascii_uppercase())
                                .or_insert_with(Vec::new)
                                .push(wire.name.clone());
                        }
                        if let Some(index) = index {
                            indices
                                .entry(index.clone())
                                .or_insert_with(Vec::new)
                                .push(wire.name.clone());
                        }
                    }
                    plan.declared.insert(wire.name.clone(), scan.path.clone());
                    types.push(wire);
                }
                Classified::Skip(reason) => {
                    plan.declared
                        .insert(component.component_name.clone(), scan.path.clone());
                    plan.skipped.push(WireSkip {
                        name: component.component_name.clone(),
                        path: scan.path.clone(),
                        reason,
                    });
                }
                Classified::None => {}
            }
        }
        let children = declarations(&scan.text, &scan.path, root);
        nodes.insert(
            module_path,
            Node {
                path: scan.path.clone(),
                text: scan.text.clone(),
                types,
                children,
            },
        );
    }

    let carries = carried_registries(&nodes);

    for (module_path, node) in &nodes {
        let carried = carries.get(module_path).copied().unwrap_or_default();
        if !carried.any() {
            // A module that no longer carries wire types must not keep the
            // block it carried last run. This pass owns that region, and a
            // stale enumeration left behind is the exact drift it exists to
            // prevent — it would name types the crate no longer publishes.
            if node.text.contains(BEGIN) {
                plan.files.push(WireFile {
                    path: node.path.clone(),
                    source: strip(&node.text),
                    classes: 0,
                    fragments: 0,
                    introspects: 0,
                });
            }
            continue;
        }
        let block = render(node, module_path.is_empty(), &carried, &carries);
        for wire in &node.types {
            plan.enumerated.insert(wire.name.clone());
        }
        plan.files.push(WireFile {
            path: node.path.clone(),
            source: splice(&node.text, &block),
            classes: node.types.len(),
            fragments: node.types.iter().filter(|wire| wire.fragment).count(),
            introspects: node
                .types
                .iter()
                .filter(|wire| wire.kind == WireKind::Message)
                .count(),
        });
    }

    // Reported for every enumerated type, not only the ones a composition
    // happens to reach first. Two types on one identity is a defect in the
    // declarations, so it is named here rather than left to fail-fast.
    plan.clashes = uuids
        .into_iter()
        .filter(|(_, types)| types.len() > 1)
        .map(|(key, types)| WireClash {
            axis: "az-uuid",
            key,
            types,
        })
        .chain(
            indices
                .into_iter()
                .filter(|(_, types)| types.len() > 1)
                .map(|(key, types)| WireClash {
                    axis: "type-index",
                    key,
                    types,
                }),
        )
        .collect();

    Ok(plan)
}

/// Write every rendered module back over its source file, then format them.
///
/// The rendered block is not what rustfmt would have written — a long turbofish
/// wraps, a one-element array folds, a chained registrar call breaks — so
/// without this step the pass and `cargo fmt --check` disagree about every file
/// the pass owns, and neither is wrong. Formatting here is also what makes the
/// pass idempotent: rustfmt is idempotent, so a second run over an unchanged
/// crate produces no diff instead of oscillating between two spellings.
pub fn apply(plan: &WirePlan) -> Result<(), RustIntegrationError> {
    write(plan)?;
    format(plan.files.iter().map(|file| file.path.as_path()))
}

/// Run rustfmt over the rewritten files.
///
/// Batched, because a process per file over ~200 modules is most of the pass's
/// wall time. The edition is passed explicitly: rustfmt defaults to 2015 and
/// would fail to parse edition-2024 source it is handed directly rather than
/// through Cargo.
fn format<'a>(paths: impl Iterator<Item = &'a Path>) -> Result<(), RustIntegrationError> {
    let paths = paths.collect::<Vec<_>>();
    for batch in paths.chunks(64) {
        let output = std::process::Command::new("rustfmt")
            .arg("--edition")
            .arg("2024")
            .args(batch)
            .output()
            .map_err(RustIntegrationError::Format)?;
        if !output.status.success() {
            return Err(RustIntegrationError::Rustfmt(
                String::from_utf8_lossy(&output.stderr).trim().to_owned(),
            ));
        }
    }
    Ok(())
}

fn write(plan: &WirePlan) -> Result<(), RustIntegrationError> {
    for file in &plan.files {
        fs::write(&file.path, &file.source).map_err(|source| RustIntegrationError::Write {
            path: file.path.clone(),
            source,
        })?;
    }
    Ok(())
}

struct FileScan {
    path: PathBuf,
    text: String,
    scanned: Vec<ScannedComponent>,
}

struct Node {
    path: PathBuf,
    text: String,
    types: Vec<WireType>,
    children: Vec<Child>,
}

enum Classified {
    Wire(WireType),
    Skip(WireSkipReason),
    None,
}

/// Types this file implements `gridmate::hub::Fragment` for by hand.
///
/// `#[derive(ReplicatedState)]` is the usual way a type says it is a concrete
/// replication fragment; it is not the only one. A type whose replication
/// layout the derive cannot express writes the impl itself, and it is exactly
/// as much a fragment for having done so — the hand-written
/// `FragmentRegistration` submit that used to sit beside such an impl is what
/// this pass replaces, so reading only the derive would drop live wire state.
fn hand_fragments(text: &str) -> BTreeSet<String> {
    let mut names = BTreeSet::new();
    for line in text.lines() {
        // A generic impl heads `impl<`, so it never reaches the split, and a
        // generic type has no monomorphic registration site anyway.
        let Some((implemented, target)) = line
            .trim_end()
            .strip_prefix("impl ")
            .and_then(|rest| rest.split_once(" for "))
        else {
            continue;
        };
        let trait_name = implemented.split('<').next().unwrap_or(implemented).trim();
        if trait_name.rsplit("::").next() != Some("Fragment") {
            continue;
        }
        let target = target.trim().trim_end_matches('{').trim();
        if !target.is_empty()
            && target
                .chars()
                .all(|character| character.is_alphanumeric() || character == '_')
        {
            names.insert(target.to_owned());
        }
    }
    names
}

/// What a declared type owes the wire registries, if anything.
///
/// `ClassDesc` is what makes a type a wire type: it carries the native type
/// index every entry is keyed on, and both `ClassRegistration` constructors are
/// bounded on `Class`. Everything else follows from that.
///
/// A bare `#[derive(Message)]` is therefore *not* a declaration here. Bevy's
/// ECS message derive shares the name with gridmate's wire-message derive —
/// there are 115 of them in the New World runtime alone — and only the wire one
/// is written beside a `ClassDesc`. Reading the name alone put ECS events on
/// the protocol, which does not even compile: `of_message` requires `Class`.
/// They are `None` rather than a reported skip because they are not an
/// incomplete wire declaration, they are a different mechanism, and 115
/// permanent lines in the skip report would bury the two shapes that ARE gaps.
/// The wire identity each `pub struct` in one file claims.
///
/// Read from the source rather than from `ScannedComponent`, which carries the
/// derives but not `class_desc(type_index = …)`. Both halves are needed: the
/// class registry keys on the AZ uuid and wire dispatch keys on the envelope
/// index, so two types can collide on either axis independently.
fn identities(text: &str) -> Vec<(String, Option<String>, Option<String>)> {
    let mut found = Vec::new();
    let mut attrs = String::new();
    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("#[") {
            attrs.push_str(trimmed);
            attrs.push('\n');
            continue;
        }
        if let Some(name) = declared_struct(trimmed) {
            let uuid = between(&attrs, "az_type_info(\"", "\"")
                .or_else(|| between(&attrs, "az_rtti(", ")").and_then(|inner| {
                    between(&inner, "\"", "\"").filter(|value| value.len() == 36)
                }));
            let index = between(&attrs, "type_index = ", ")")
                .map(|value| value.trim().to_owned());
            if uuid.is_some() || index.is_some() {
                found.push((name, uuid, index));
            }
        }
        if !trimmed.is_empty() && !trimmed.starts_with("//") {
            attrs.clear();
        }
    }
    found
}

/// The struct a line declares, when it declares one.
fn declared_struct(line: &str) -> Option<String> {
    let rest = line.strip_prefix("pub struct ")?;
    let name = rest
        .split(|c: char| !(c.is_alphanumeric() || c == '_'))
        .next()?;
    (!name.is_empty()).then(|| name.to_owned())
}

/// The text between two markers, when both are present.
fn between(haystack: &str, open: &str, close: &str) -> Option<String> {
    let start = haystack.find(open)? + open.len();
    let end = haystack[start..].find(close)? + start;
    Some(haystack[start..end].to_owned())
}

fn classify(component: &ScannedComponent) -> Classified {
    if !component.has_class_desc_derive {
        return if component.has_replicated_state_derive {
            Classified::Skip(WireSkipReason::FragmentWithoutClass)
        } else {
            Classified::None
        };
    }
    if component.is_generic {
        return Classified::Skip(WireSkipReason::Generic);
    }
    Classified::Wire(WireType {
        name: component.component_name.clone(),
        kind: if component.has_message_derive {
            WireKind::Message
        } else {
            WireKind::Class
        },
        fragment: component.has_replicated_state_derive,
    })
}

/// Module path for a source file, relative to a crate's `src` directory.
///
/// `lib.rs`/`main.rs` are the crate root; `a/b/mod.rs` and `a/b.rs` are both
/// module `a::b`, which is why the two spellings collapse to one path here.
fn module_path(root: &Path, path: &Path) -> Option<Vec<String>> {
    let relative = path.strip_prefix(root).ok()?;
    let mut parts = relative
        .components()
        .map(|part| part.as_os_str().to_str().map(ToOwned::to_owned))
        .collect::<Option<Vec<_>>>()?;
    let last = parts.pop()?;
    match last.strip_suffix(".rs")? {
        "lib" | "main" if parts.is_empty() => Some(Vec::new()),
        "mod" => Some(parts),
        stem => {
            parts.push(stem.to_owned());
            Some(parts)
        }
    }
}

/// The file modules one source declares, in declaration order.
///
/// A line scanner rather than a parse: the three facts it needs — the name, the
/// `#[cfg]`s, the `#[path]` — are all written on the declaration's own lines,
/// and the attribute run above a `mod` item is the only place they can be.
/// Inline `mod name { … }` is deliberately not a declaration here: its types
/// live in this file and are already in this module's own block.
fn declarations(text: &str, file: &Path, root: &Path) -> Vec<Child> {
    let mut children = Vec::new();
    let mut cfgs: Vec<String> = Vec::new();
    let mut declared: Option<String> = None;
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with("//") {
            continue;
        }
        if let Some(attribute) = line.strip_prefix("#[").and_then(|rest| rest.strip_suffix(']')) {
            if attribute.starts_with("cfg(") {
                cfgs.push(line.to_owned());
            } else if let Some(value) = attribute
                .strip_prefix("path")
                .map(str::trim_start)
                .and_then(|value| value.strip_prefix('='))
            {
                declared = Some(value.trim().trim_matches('"').to_owned());
            }
            continue;
        }
        if let Some(name) = module(line)
            && let Some(target) = resolve(&name, declared.as_deref(), file, root)
        {
            children.push(Child {
                name,
                target,
                cfgs: cfgs.clone(),
            });
        }
        cfgs.clear();
        declared = None;
    }
    children
}

/// The module a line declares, when it is a file-module declaration.
fn module(line: &str) -> Option<String> {
    let mut rest = line;
    if let Some(after) = rest.strip_prefix("pub")
        && after.starts_with([' ', '('])
    {
        rest = after.trim_start();
        if rest.starts_with('(') {
            rest = rest.split_once(')')?.1.trim_start();
        }
    }
    let name = rest.strip_prefix("mod ")?.trim().strip_suffix(';')?.trim();
    (!name.is_empty()
        && name
            .chars()
            .all(|character| character.is_alphanumeric() || character == '_'))
    .then(|| name.to_owned())
}

/// The node a declaration names.
///
/// `#[path]` is relative to the directory of the declaring file, which is the
/// language's own rule for a module declared at a file's top level. Without it,
/// a module is `<dir>/<name>.rs` or `<dir>/<name>/mod.rs`, where `<dir>` is the
/// declaring file's own directory for a root or `mod.rs`, and the file's stem
/// beside it otherwise.
fn resolve(name: &str, declared: Option<&str>, file: &Path, root: &Path) -> Option<Vec<String>> {
    let beside = file.parent()?;
    if let Some(declared) = declared {
        return module_path(root, &normalize(&beside.join(declared)));
    }
    let directory = match file.file_stem().and_then(|stem| stem.to_str())? {
        "lib" | "main" | "mod" => beside.to_path_buf(),
        stem => beside.join(stem),
    };
    [
        directory.join(format!("{name}.rs")),
        directory.join(name).join("mod.rs"),
    ]
    .into_iter()
    .find(|candidate| candidate.is_file())
    .and_then(|candidate| module_path(root, &candidate))
}

/// Resolve `.` and `..` lexically, so a `#[path]` that steps out of its own
/// directory still lands on the node the scan collected.
fn normalize(path: &Path) -> PathBuf {
    let mut parts = Vec::new();
    for part in path.components() {
        match part {
            std::path::Component::CurDir => {}
            std::path::Component::ParentDir => {
                parts.pop();
            }
            part => parts.push(part),
        }
    }
    parts.iter().collect()
}

/// Which registries each module's subtree contributes to.
///
/// Computed for the whole tree before rendering, because a module emits a
/// `classes()` only when something under it has one — and its parent must know
/// the same thing before it can chain the call.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
struct Carried {
    classes: bool,
    fragments: bool,
    introspects: bool,
}

impl Carried {
    const fn any(self) -> bool {
        self.classes || self.fragments || self.introspects
    }

    fn merge(self, other: Self) -> Self {
        Self {
            classes: self.classes || other.classes,
            fragments: self.fragments || other.fragments,
            introspects: self.introspects || other.introspects,
        }
    }
}

fn carried_registries(nodes: &BTreeMap<Vec<String>, Node>) -> BTreeMap<Vec<String>, Carried> {
    let mut carries = BTreeMap::<Vec<String>, Carried>::new();
    for path in nodes.keys() {
        carry(nodes, path, &mut carries, &mut BTreeSet::new());
    }
    carries
}

/// One module's answer: its own types plus every module it declares.
///
/// A declaration graph, not the directory tree — `#[path]` lets a module name a
/// file that is not below it — so the walk memoizes and refuses to re-enter a
/// node it is already inside, rather than assuming depth orders the work.
fn carry(
    nodes: &BTreeMap<Vec<String>, Node>,
    path: &[String],
    carries: &mut BTreeMap<Vec<String>, Carried>,
    visiting: &mut BTreeSet<Vec<String>>,
) -> Carried {
    if let Some(carried) = carries.get(path) {
        return *carried;
    }
    let Some(node) = nodes.get(path) else {
        return Carried::default();
    };
    if !visiting.insert(path.to_vec()) {
        return Carried::default();
    }
    let mut carried = Carried {
        classes: !node.types.is_empty(),
        fragments: node.types.iter().any(|wire| wire.fragment),
        introspects: node.types.iter().any(|wire| wire.kind == WireKind::Message),
    };
    for child in &node.children {
        carried = carried.merge(carry(nodes, &child.target, carries, visiting));
    }
    visiting.remove(path);
    carries.insert(path.to_vec(), carried);
    carried
}

fn render(
    node: &Node,
    is_root: bool,
    carried: &Carried,
    carries: &BTreeMap<Vec<String>, Carried>,
) -> String {
    let mut block = String::new();
    block.push_str(BEGIN);
    block.push('\n');

    let contributors = |select: fn(&Carried) -> bool| -> Vec<&Child> {
        node.children
            .iter()
            .filter(|child| carries.get(&child.target).is_some_and(select))
            .collect()
    };

    if carried.classes {
        let entries = node
            .types
            .iter()
            .map(|wire| match wire.kind {
                WireKind::Message => format!("{CLASS}::of_message::<{}>()", wire.name),
                WireKind::Class => format!("{CLASS}::of::<{}>()", wire.name),
            })
            .collect::<Vec<_>>();
        let children = contributors(|carried| carried.classes);
        block.push_str(&function("classes", CLASS, &entries, &children, None));
    }
    if carried.fragments {
        let entries = node
            .types
            .iter()
            .filter(|wire| wire.fragment)
            .map(|wire| format!("{FRAGMENT}::of::<{}>()", wire.name))
            .collect::<Vec<_>>();
        let children = contributors(|carried| carried.fragments);
        block.push_str(&function("fragments", FRAGMENT, &entries, &children, None));
    }
    if carried.introspects {
        let entries = node
            .types
            .iter()
            .filter(|wire| wire.kind == WireKind::Message)
            .map(|wire| format!("{INTROSPECT}::of::<{}>()", wire.name))
            .collect::<Vec<_>>();
        let children = contributors(|carried| carried.introspects);
        block.push_str(&function(
            "introspects",
            INTROSPECT,
            &entries,
            &children,
            Some("#[cfg(debug_assertions)]"),
        ));
    }
    if is_root {
        block.push_str(&root_register(carried));
    }

    block.push_str(END);
    block.push('\n');
    block
}

/// One enumeration function: an array when the module is a leaf contributor, a
/// `Vec` when it also chains children.
fn function(
    name: &str,
    entry: &str,
    entries: &[String],
    children: &[&Child],
    cfg: Option<&str>,
) -> String {
    let mut source = String::new();
    if let Some(cfg) = cfg {
        let _ = writeln!(source, "{cfg}");
    }
    if children.is_empty() {
        let _ = writeln!(
            source,
            "pub(crate) fn {name}() -> [{entry}; {}] {{",
            entries.len()
        );
        let _ = writeln!(source, "    [");
        for line in entries {
            let _ = writeln!(source, "        {line},");
        }
        let _ = writeln!(source, "    ]");
        let _ = writeln!(source, "}}");
        return source;
    }

    let _ = writeln!(source, "pub(crate) fn {name}() -> Vec<{entry}> {{");
    // Every chained call can be conditional, and then no feature set mutates
    // the list. The allow says so at the one line that would otherwise warn,
    // rather than at the module.
    if children.iter().all(|child| !child.cfgs.is_empty()) {
        let _ = writeln!(source, "    #[allow(unused_mut)]");
    }
    if entries.is_empty() {
        let _ = writeln!(source, "    let mut out = Vec::new();");
    } else {
        let _ = writeln!(source, "    let mut out = vec![");
        for line in entries {
            let _ = writeln!(source, "        {line},");
        }
        let _ = writeln!(source, "    ];");
    }
    for child in children {
        for cfg in &child.cfgs {
            let _ = writeln!(source, "    {cfg}");
        }
        let _ = writeln!(
            source,
            "    out.extend(self::{}::{name}());",
            child.name.as_str()
        );
    }
    let _ = writeln!(source, "    out");
    let _ = writeln!(source, "}}");
    source
}

fn root_register(carried: &Carried) -> String {
    let mut source = String::new();
    let _ = writeln!(
        source,
        "/// Register this crate's gridmate wire types into a composing host."
    );
    let _ = writeln!(
        source,
        "pub fn register<D>(ctx: &mut az_gem_contract::GemContext<'_, D>) {{"
    );
    if carried.classes {
        let _ = writeln!(
            source,
            "    ctx.registrar::<{CLASS}>().register_many(classes());"
        );
    }
    if carried.fragments {
        let _ = writeln!(
            source,
            "    ctx.registrar::<{FRAGMENT}>().register_many(fragments());"
        );
    }
    if carried.introspects {
        let _ = writeln!(source, "    #[cfg(debug_assertions)]");
        let _ = writeln!(
            source,
            "    ctx.registrar::<{INTROSPECT}>().register_many(introspects());"
        );
    }
    let _ = writeln!(source, "}}");
    source
}

/// Replace the marked block, or append it.
///
/// Replacement rather than append-only: the pass runs again whenever a type is
/// added, and a second block would be a second answer to which types this
/// module owns.
fn splice(text: &str, block: &str) -> String {
    let Some((begin, end)) = bounds(text) else {
        let mut source = text.to_owned();
        if !source.ends_with('\n') {
            source.push('\n');
        }
        source.push('\n');
        source.push_str(block);
        return source;
    };
    let mut source = text[..begin].to_owned();
    source.push_str(block);
    source.push_str(&text[end..]);
    source
}

/// Remove the marked block and the blank line that introduced it.
fn strip(text: &str) -> String {
    let Some((begin, end)) = bounds(text) else {
        return text.to_owned();
    };
    let mut source = text[..begin].trim_end().to_owned();
    source.push('\n');
    let rest = text[end..].trim_start_matches('\n');
    if !rest.is_empty() {
        source.push('\n');
        source.push_str(rest);
    }
    source
}

/// Byte range of this pass's block, when the source carries one.
fn bounds(text: &str) -> Option<(usize, usize)> {
    let begin = text.find(BEGIN)?;
    let end = text[begin..]
        .find(END)
        .map(|offset| begin + offset + END.len())
        .map_or(text.len(), |end| {
            end + usize::from(text[end..].starts_with('\n'))
        });
    Some((begin, end))
}

#[cfg(test)]
mod tests {
    use std::fs;

    use super::*;

    fn crate_root() -> tempfile::TempDir {
        let temp = tempfile::tempdir().expect("tempdir");
        let src = temp.path();
        fs::create_dir_all(src.join("combat")).expect("create combat module");
        // Shaped like a capability-gated crate: one module a feature admits,
        // one it removes, and a `#[path]` alias that names a file the layout
        // puts somewhere else entirely.
        fs::write(
            src.join("lib.rs"),
            concat!(
                "pub mod bundle;\n",
                "pub mod echo;\n",
                "#[cfg(feature = \"combat\")]\n",
                "pub mod combat;\n",
                "pub mod solo;\n",
                "#[cfg(not(feature = \"combat\"))]\n",
                "#[path = \"combat/damage.rs\"]\n",
                "pub mod aliased;\n",
                "\n",
                "#[derive(ClassDesc, Marshaler)]\n",
                "#[class_desc(type_index = 1)]\n",
                "pub struct RootOnly;\n",
            ),
        )
        .expect("write lib");
        fs::write(
            src.join("solo.rs"),
            concat!(
                "#[derive(ClassDesc, Message, Marshaler)]\n",
                "#[class_desc(type_index = 2)]\n",
                "#[az_type_info(\"1D9E5A21-0000-4000-8000-000000000001\")]\n",
                "pub struct Ping;\n",
                "\n",
                "// Bevy's ECS message derive, which shares the name.\n",
                "#[derive(Debug, Clone, Message)]\n",
                "pub struct Fired;\n",
            ),
        )
        .expect("write solo");
        // A fragment whose replication layout the derive cannot express, so the
        // impl is written by hand.
        fs::write(
            src.join("bundle.rs"),
            concat!(
                "#[derive(ClassDesc, Marshaler)]\n",
                "#[class_desc(type_index = 4)]\n",
                "pub struct Bundle;\n",
                "\n",
                "impl gridmate::hub::Fragment for Bundle {\n",
                "    fn base(&self) -> &gridmate::hub::FragmentBase { &self.base }\n",
                "}\n",
            ),
        )
        .expect("write bundle");
        fs::write(src.join("combat").join("mod.rs"), "pub mod damage;\n")
            .expect("write combat mod");
        // Claims `Ping`'s envelope index and its AZ uuid. Under `inventory`
        // this resolved by link order; a composing host fails on it.
        fs::write(
            src.join("echo.rs"),
            concat!(
                "#[derive(ClassDesc, Message, Marshaler)]\n",
                "#[class_desc(type_index = 2)]\n",
                "#[az_type_info(\"1D9E5A21-0000-4000-8000-000000000001\")]\n",
                "pub struct Echo;\n",
            ),
        )
        .expect("write echo");
        fs::write(
            src.join("combat").join("damage.rs"),
            concat!(
                "#[derive(ClassDesc, ReplicatedState, Marshaler)]\n",
                "#[class_desc(type_index = 3)]\n",
                "pub struct DamageState;\n",
                "\n",
                "#[derive(ReplicatedState, Marshaler)]\n",
                "pub struct Untethered;\n",
                "\n",
                "#[derive(ClassDesc, Marshaler)]\n",
                "pub struct Boxed<T>;\n",
            ),
        )
        .expect("write damage");
        temp
    }

    fn planned(temp: &tempfile::TempDir) -> WirePlan {
        plan(temp.path(), &CodegenContext::inline()).expect("wire plan")
    }

    fn rendered<'a>(plan: &'a WirePlan, name: &str) -> &'a str {
        &plan
            .files
            .iter()
            .find(|file| file.path.ends_with(name))
            .unwrap_or_else(|| panic!("no rendered block for {name}"))
            .source
    }

    #[test]
    fn a_message_takes_the_message_constructor_and_owes_an_introspector() {
        let temp = crate_root();
        let plan = planned(&temp);
        let solo = rendered(&plan, "solo.rs");

        assert!(solo.contains("ClassRegistration::of_message::<Ping>()"));
        assert!(!solo.contains("ClassRegistration::of::<Ping>()"));
        assert!(solo.contains("#[cfg(debug_assertions)]"));
        assert!(solo.contains("DebugIntrospect::of::<Ping>()"));
        assert!(
            !solo.contains("fn fragments"),
            "a module with no fragment carries no fragment function"
        );
    }

    #[test]
    fn a_replicated_state_class_is_both_a_class_and_a_fragment() {
        let temp = crate_root();
        let plan = planned(&temp);
        let damage = rendered(&plan, "damage.rs");

        assert!(damage.contains("ClassRegistration::of::<DamageState>()"));
        assert!(damage.contains("FragmentRegistration::of::<DamageState>()"));
        assert!(
            !damage.contains("DebugIntrospect"),
            "a non-message class owes no introspector"
        );
    }

    /// The two shapes no site can name. The `ReplicatedState`-without-`ClassDesc`
    /// case is the one the old derive dropped in silence.
    #[test]
    fn unnameable_types_are_reported_rather_than_dropped() {
        let temp = crate_root();
        let plan = planned(&temp);

        let mut skips = plan
            .skipped
            .iter()
            .map(|skip| (skip.name.as_str(), skip.reason))
            .collect::<Vec<_>>();
        skips.sort();
        assert_eq!(
            skips,
            vec![
                ("Boxed", WireSkipReason::Generic),
                ("Untethered", WireSkipReason::FragmentWithoutClass),
            ]
        );
        assert_eq!(plan.unenumerated(), vec!["Boxed", "Untethered"]);
    }

    #[test]
    fn every_module_chains_into_one_crate_root_register() {
        let temp = crate_root();
        let plan = planned(&temp);
        let root = rendered(&plan, "lib.rs");
        let combat = rendered(&plan, "mod.rs");

        // A module that owns types and children returns a `Vec`; a leaf
        // returns a length-typed array.
        assert!(root.contains("pub(crate) fn classes() -> Vec<::gridmate::az::ClassRegistration>"));
        assert!(root.contains("out.extend(self::combat::classes());"));
        assert!(root.contains("out.extend(self::solo::classes());"));
        assert!(
            combat.contains("out.extend(self::damage::classes());"),
            "a mod.rs with no types of its own still chains its children"
        );
        assert!(
            rendered(&plan, "damage.rs")
                .contains("pub(crate) fn classes() -> [::gridmate::az::ClassRegistration; 1]")
        );

        // Only the crate root is public, and only registries something
        // contributes to appear.
        assert!(root.contains("pub fn register<D>(ctx: &mut az_gem_contract::GemContext<'_, D>)"));
        assert!(root.contains(
            "ctx.registrar::<::gridmate::hub::FragmentRegistration>().register_many(fragments());"
        ));
        assert!(!combat.contains("pub fn register<D>"));
        assert!(
            !root.contains("out.extend(self::solo::fragments());"),
            "solo contributes no fragment, so the root must not call for one"
        );
    }

    /// A derive is not the only way a type says it is a fragment.
    #[test]
    fn a_hand_written_fragment_impl_enumerates_the_type() {
        let temp = crate_root();
        let plan = planned(&temp);
        let bundle = rendered(&plan, "bundle.rs");

        assert!(bundle.contains("FragmentRegistration::of::<Bundle>()"));
        assert!(bundle.contains("ClassRegistration::of::<Bundle>()"));
        assert!(
            rendered(&plan, "lib.rs").contains("out.extend(self::bundle::fragments());"),
            "the crate root reaches it like any other fragment"
        );
    }

    /// The chain is built from what each module *declares*, not from the file
    /// tree: a feature that removes a module must remove the call to it, and a
    /// `#[path]` module answers to the name its parent gave it.
    #[test]
    fn a_chained_call_carries_the_declaration_that_named_it() {
        let temp = crate_root();
        let plan = planned(&temp);
        let root = rendered(&plan, "lib.rs");

        assert!(
            root.contains("#[cfg(feature = \"combat\")]\n    out.extend(self::combat::classes());"),
            "a gated module is called under its own gate"
        );
        assert!(
            root.contains(
                "#[cfg(not(feature = \"combat\"))]\n    out.extend(self::aliased::classes());"
            ),
            "a `#[path]` module is chained by the name its parent declares"
        );
        assert!(
            !root.contains("out.extend(self::damage::classes());"),
            "the root declares no `damage`; only `combat` and `aliased` reach it"
        );
    }

    /// Two types on one wire identity is a defect in the declarations, and the
    /// pass names every one of them rather than leaving it to a composing
    /// host's fail-fast `finalize` to surface them one cycle at a time.
    #[test]
    fn types_sharing_a_wire_identity_are_all_reported() {
        let temp = crate_root();
        let plan = planned(&temp);

        let axes = plan
            .clashes
            .iter()
            .map(|clash| clash.axis)
            .collect::<BTreeSet<_>>();
        assert!(axes.contains("az-uuid"), "{:?}", plan.clashes);
        assert!(axes.contains("type-index"), "{:?}", plan.clashes);

        for clash in &plan.clashes {
            let mut types = clash.types.clone();
            types.sort();
            assert_eq!(types, vec!["Echo".to_owned(), "Ping".to_owned()]);
        }

        // Reporting a clash is not a reason to stop emitting: the enumeration
        // is still what the crate declares, and the fix belongs in the
        // declarations rather than in the generated block.
        assert!(rendered(&plan, "echo.rs").contains("of_message::<Echo>()"));
    }

    /// Bevy's ECS `Message` derive shares a name with gridmate's wire-message
    /// derive, and only the wire one is written beside a `ClassDesc`.
    #[test]
    fn an_ecs_message_is_not_a_wire_declaration() {
        let temp = crate_root();
        let plan = planned(&temp);

        let solo = rendered(&plan, "solo.rs");
        assert!(solo.contains("pub struct Fired;"), "authored source survives");
        assert!(!solo.contains("::<Fired>()"), "no entry constructor names it");
        assert!(
            solo.contains("[::gridmate::az::ClassRegistration; 1]"),
            "the module's one wire type is still enumerated"
        );
        assert!(
            !plan.declared.contains_key("Fired"),
            "not an incomplete wire declaration but a different mechanism, so \
             it is not reported as a gap either"
        );
        assert!(plan.skipped.iter().all(|skip| skip.name != "Fired"));
    }

    /// The pass owns its block in both directions: a module that stops
    /// carrying wire types loses it, rather than keeping a list of types the
    /// crate no longer publishes.
    #[test]
    fn a_module_that_stops_carrying_types_loses_its_block() {
        let temp = crate_root();
        apply(&planned(&temp)).expect("apply");
        let solo = temp.path().join("solo.rs");
        assert!(fs::read_to_string(&solo).expect("read solo").contains(BEGIN));

        // The wire type goes; the ECS message beside it stays.
        fs::write(&solo, "#[derive(Debug, Clone, Message)]\npub struct Fired;\n")
            .expect("rewrite solo");
        apply(&planned(&temp)).expect("reapply");

        let stripped = fs::read_to_string(&solo).expect("reread solo");
        assert!(!stripped.contains(BEGIN));
        assert!(!stripped.contains(END));
        assert!(stripped.contains("pub struct Fired;"));
        assert!(
            !rendered(&planned(&temp), "lib.rs").contains("self::solo::classes()"),
            "and the root stops calling it"
        );
    }

    #[test]
    fn a_second_run_replaces_the_block_instead_of_appending_one() {
        let temp = crate_root();
        apply(&planned(&temp)).expect("apply");
        let once = fs::read_to_string(temp.path().join("solo.rs")).expect("read solo");

        apply(&planned(&temp)).expect("reapply");
        let twice = fs::read_to_string(temp.path().join("solo.rs")).expect("reread solo");

        assert_eq!(once, twice);
        assert_eq!(twice.matches(BEGIN).count(), 1);
        assert!(
            twice.contains("pub struct Ping;"),
            "authored source survives"
        );
    }
}
