//! The gridmate wire enumeration a crate owes a composing host.
//!
//! `#[derive(ClassDesc)]`, `#[derive(Message)]`, and
//! `#[derive(ReplicatedState)]` no longer register anything. A derive says what
//! a type *is*; it cannot say which host wants it, and a link-time submission
//! answered that by accident — whichever crates the linker happened to keep.
//! The crate that declares the type publishes it instead, by handing
//! `ClassRegistration` / `FragmentRegistration` / `DebugIntrospect` entries to a
//! contribution's registrar.
//!
//! For a hand-written tree the size of the New World runtime that is ~1,900
//! entries, so this pass writes them: it scans each file for the three derives,
//! renders a marked block into the module that declares the types, and chains
//! every module's arrays up its `mod.rs` parents into one crate-root
//! `register`. The block is emitted *in the declaring module* because the
//! entries name types by bare ident — and because `pub(crate)` inside a private
//! nested module is not reachable from the crate root, so a flat crate-root
//! list could not name half of them.
//!
//! Nothing here scans for types at compose time: the rendered arrays *are* the
//! enumeration. A type that is declared and never listed is simply absent from
//! the host, which is what the audit's declared-but-not-enumerated status
//! exists to catch.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use crate::CodegenContext;
use crate::rust::integrate::identity::{ScannedComponent, scan_component_structs};

use super::{RustIntegrationError, collect_rust_files};

/// Opening line of the block this pass owns. Everything between it and
/// [`END`] is rewritten on every run; everything outside is the author's.
const BEGIN: &str = "// gridmate wire registration — generated by nw-serialize-codegen";
const END: &str = "// end gridmate wire registration";

const CLASS: &str = "::gridmate::az::ClassRegistration";
const FRAGMENT: &str = "::gridmate::hub::FragmentRegistration";
const INTROSPECT: &str = "::gridmate::az::DebugIntrospect";

/// Which class-registry constructor a declared type takes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WireKind {
    /// `#[derive(Message)]` — `ClassRegistration::of_message`, plus a debug
    /// introspector. Carries the envelope index and protocol metadata a
    /// class-only entry has none of.
    Message,
    /// `#[derive(ClassDesc)]` without `Message` — `ClassRegistration::of`.
    Class,
}

/// One declared type and the entries it owes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireType {
    pub name: String,
    pub kind: WireKind,
    /// `#[derive(ReplicatedState)]` alongside `ClassDesc`: the type is also a
    /// concrete replication fragment.
    pub fragment: bool,
}

/// A type that derives wire registration and that no site can name.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireSkip {
    pub name: String,
    pub path: PathBuf,
    pub reason: WireSkipReason,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum WireSkipReason {
    /// Generic types have no single registration site: the entry constructors
    /// are monomorphic and the scanner has no argument list to supply.
    Generic,
    /// `ReplicatedState` without `ClassDesc`. `FragmentRegistration::of`
    /// requires `Class`, so the type has no `type_index` to be keyed on. The
    /// old derive skipped these silently; naming them is the point.
    FragmentWithoutClass,
}

impl std::fmt::Display for WireSkipReason {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Generic => f.write_str("generic type"),
            Self::FragmentWithoutClass => f.write_str("ReplicatedState without ClassDesc"),
        }
    }
}

/// The rewritten source for one module, ready to write.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireFile {
    pub path: PathBuf,
    pub source: String,
    pub classes: usize,
    pub fragments: usize,
    pub introspects: usize,
}

/// What a crate declares and what its emitted blocks enumerate.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct WirePlan {
    pub files: Vec<WireFile>,
    /// Types carrying one of the three derives, by name.
    pub declared: BTreeMap<String, PathBuf>,
    /// Types the rendered blocks name. A declared type outside this set reaches
    /// no host.
    pub enumerated: BTreeSet<String>,
    pub skipped: Vec<WireSkip>,
}

impl WirePlan {
    /// Declared types that no rendered block names, in scan order.
    #[must_use]
    pub fn unenumerated(&self) -> Vec<&str> {
        self.declared
            .keys()
            .filter(|name| !self.enumerated.contains(*name))
            .map(String::as_str)
            .collect()
    }

    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.files.is_empty()
    }
}

/// Scan `root` and render every module's wire enumeration.
///
/// `root` is a crate's `src` directory: the crate root is its `lib.rs` (or
/// `main.rs`), and that is the only module that gets a public `register`.
pub fn plan(root: &Path, context: &CodegenContext) -> Result<WirePlan, RustIntegrationError> {
    let mut paths = Vec::new();
    collect_rust_files(root, &mut paths)?;
    paths.sort();

    let scans = context.runner().try_map(&paths, |path| {
        let text = fs::read_to_string(path).map_err(|source| RustIntegrationError::Read {
            path: path.clone(),
            source,
        })?;
        let scanned = scan_component_structs(&text, path);
        Ok(FileScan {
            path: path.clone(),
            text,
            scanned,
        })
    })?;

    let mut nodes = BTreeMap::<Vec<String>, Node>::new();
    let mut plan = WirePlan::default();
    for scan in &scans {
        let Some(module_path) = module_path(root, &scan.path) else {
            continue;
        };
        let mut types = Vec::new();
        for component in &scan.scanned {
            match classify(component) {
                Classified::Wire(wire) => {
                    plan.declared.insert(wire.name.clone(), scan.path.clone());
                    types.push(wire);
                }
                Classified::Skip(reason) => {
                    plan.declared
                        .insert(component.component_name.clone(), scan.path.clone());
                    plan.skipped.push(WireSkip {
                        name: component.component_name.clone(),
                        path: scan.path.clone(),
                        reason,
                    });
                }
                Classified::None => {}
            }
        }
        nodes.insert(
            module_path.clone(),
            Node {
                path: scan.path.clone(),
                module_path,
                text: scan.text.clone(),
                types,
                children: Vec::new(),
            },
        );
    }

    link_children(&mut nodes);
    let carries = carried_registries(&nodes);

    for (module_path, node) in &nodes {
        let Some(carried) = carries.get(module_path) else {
            continue;
        };
        if !carried.any() {
            continue;
        }
        let block = render(node, module_path.is_empty(), carried, &carries);
        for wire in &node.types {
            plan.enumerated.insert(wire.name.clone());
        }
        plan.files.push(WireFile {
            path: node.path.clone(),
            source: splice(&node.text, &block),
            classes: node.types.len(),
            fragments: node.types.iter().filter(|wire| wire.fragment).count(),
            introspects: node
                .types
                .iter()
                .filter(|wire| wire.kind == WireKind::Message)
                .count(),
        });
    }

    Ok(plan)
}

/// Write every rendered module back over its source file.
pub fn apply(plan: &WirePlan) -> Result<(), RustIntegrationError> {
    for file in &plan.files {
        fs::write(&file.path, &file.source).map_err(|source| RustIntegrationError::Write {
            path: file.path.clone(),
            source,
        })?;
    }
    Ok(())
}

struct FileScan {
    path: PathBuf,
    text: String,
    scanned: Vec<ScannedComponent>,
}

struct Node {
    path: PathBuf,
    module_path: Vec<String>,
    text: String,
    types: Vec<WireType>,
    children: Vec<String>,
}

enum Classified {
    Wire(WireType),
    Skip(WireSkipReason),
    None,
}

fn classify(component: &ScannedComponent) -> Classified {
    let declares = component.has_class_desc_derive
        || component.has_message_derive
        || component.has_replicated_state_derive;
    if !declares {
        return Classified::None;
    }
    if component.is_generic {
        return Classified::Skip(WireSkipReason::Generic);
    }
    let kind = if component.has_message_derive {
        WireKind::Message
    } else if component.has_class_desc_derive {
        WireKind::Class
    } else {
        return Classified::Skip(WireSkipReason::FragmentWithoutClass);
    };
    if component.has_replicated_state_derive && !component.has_class_desc_derive {
        return Classified::Skip(WireSkipReason::FragmentWithoutClass);
    }
    Classified::Wire(WireType {
        name: component.component_name.clone(),
        kind,
        fragment: component.has_replicated_state_derive,
    })
}

/// Module path for a source file, relative to a crate's `src` directory.
///
/// `lib.rs`/`main.rs` are the crate root; `a/b/mod.rs` and `a/b.rs` are both
/// module `a::b`, which is why the two spellings collapse to one path here.
fn module_path(root: &Path, path: &Path) -> Option<Vec<String>> {
    let relative = path.strip_prefix(root).ok()?;
    let mut parts = relative
        .components()
        .map(|part| part.as_os_str().to_str().map(ToOwned::to_owned))
        .collect::<Option<Vec<_>>>()?;
    let last = parts.pop()?;
    match last.strip_suffix(".rs")? {
        "lib" | "main" if parts.is_empty() => Some(Vec::new()),
        "mod" => Some(parts),
        stem => {
            parts.push(stem.to_owned());
            Some(parts)
        }
    }
}

fn link_children(nodes: &mut BTreeMap<Vec<String>, Node>) {
    let children = nodes
        .keys()
        .filter(|path| !path.is_empty())
        .filter_map(|path| {
            let (name, parent) = path.split_last()?;
            Some((parent.to_vec(), name.clone()))
        })
        .fold(
            BTreeMap::<Vec<String>, Vec<String>>::new(),
            |mut acc, (parent, name)| {
                acc.entry(parent).or_default().push(name);
                acc
            },
        );
    for (parent, names) in children {
        if let Some(node) = nodes.get_mut(&parent) {
            node.children = names;
        }
    }
}

/// Which registries each module's subtree contributes to.
///
/// Computed for the whole tree before rendering, because a module emits a
/// `classes()` only when something under it has one — and its parent must know
/// the same thing before it can chain the call.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
struct Carried {
    classes: bool,
    fragments: bool,
    introspects: bool,
}

impl Carried {
    const fn any(self) -> bool {
        self.classes || self.fragments || self.introspects
    }

    fn merge(self, other: Self) -> Self {
        Self {
            classes: self.classes || other.classes,
            fragments: self.fragments || other.fragments,
            introspects: self.introspects || other.introspects,
        }
    }
}

fn carried_registries(nodes: &BTreeMap<Vec<String>, Node>) -> BTreeMap<Vec<String>, Carried> {
    let mut carries = BTreeMap::<Vec<String>, Carried>::new();
    // Deepest first: a parent's answer is its own types plus its children's,
    // and every child is longer than its parent.
    let mut paths = nodes.keys().cloned().collect::<Vec<_>>();
    paths.sort_by_key(|path| std::cmp::Reverse(path.len()));
    for path in paths {
        let node = &nodes[&path];
        let mut carried = Carried {
            classes: !node.types.is_empty(),
            fragments: node.types.iter().any(|wire| wire.fragment),
            introspects: node.types.iter().any(|wire| wire.kind == WireKind::Message),
        };
        for child in &node.children {
            let mut child_path = path.clone();
            child_path.push(child.clone());
            if let Some(child_carried) = carries.get(&child_path) {
                carried = carried.merge(*child_carried);
            }
        }
        carries.insert(path, carried);
    }
    carries
}

fn render(
    node: &Node,
    is_root: bool,
    carried: &Carried,
    carries: &BTreeMap<Vec<String>, Carried>,
) -> String {
    let mut block = String::new();
    block.push_str(BEGIN);
    block.push('\n');

    let contributors = |select: fn(&Carried) -> bool| -> Vec<String> {
        node.children
            .iter()
            .filter(|child| {
                let mut child_path = node.module_path.clone();
                child_path.push((*child).clone());
                carries.get(&child_path).is_some_and(select)
            })
            .cloned()
            .collect()
    };

    if carried.classes {
        let entries = node
            .types
            .iter()
            .map(|wire| match wire.kind {
                WireKind::Message => format!("{CLASS}::of_message::<{}>()", wire.name),
                WireKind::Class => format!("{CLASS}::of::<{}>()", wire.name),
            })
            .collect::<Vec<_>>();
        let children = contributors(|carried| carried.classes);
        block.push_str(&function("classes", CLASS, &entries, &children, None));
    }
    if carried.fragments {
        let entries = node
            .types
            .iter()
            .filter(|wire| wire.fragment)
            .map(|wire| format!("{FRAGMENT}::of::<{}>()", wire.name))
            .collect::<Vec<_>>();
        let children = contributors(|carried| carried.fragments);
        block.push_str(&function("fragments", FRAGMENT, &entries, &children, None));
    }
    if carried.introspects {
        let entries = node
            .types
            .iter()
            .filter(|wire| wire.kind == WireKind::Message)
            .map(|wire| format!("{INTROSPECT}::of::<{}>()", wire.name))
            .collect::<Vec<_>>();
        let children = contributors(|carried| carried.introspects);
        block.push_str(&function(
            "introspects",
            INTROSPECT,
            &entries,
            &children,
            Some("#[cfg(debug_assertions)]"),
        ));
    }
    if is_root {
        block.push_str(&root_register(carried));
    }

    block.push_str(END);
    block.push('\n');
    block
}

/// One enumeration function: an array when the module is a leaf contributor, a
/// `Vec` when it also chains children.
fn function(
    name: &str,
    entry: &str,
    entries: &[String],
    children: &[String],
    cfg: Option<&str>,
) -> String {
    let mut source = String::new();
    if let Some(cfg) = cfg {
        let _ = writeln!(source, "{cfg}");
    }
    if children.is_empty() {
        let _ = writeln!(
            source,
            "pub(crate) fn {name}() -> [{entry}; {}] {{",
            entries.len()
        );
        let _ = writeln!(source, "    [");
        for line in entries {
            let _ = writeln!(source, "        {line},");
        }
        let _ = writeln!(source, "    ]");
        let _ = writeln!(source, "}}");
        return source;
    }

    let _ = writeln!(source, "pub(crate) fn {name}() -> Vec<{entry}> {{");
    if entries.is_empty() {
        let _ = writeln!(source, "    let mut out = Vec::new();");
    } else {
        let _ = writeln!(source, "    let mut out = vec![");
        for line in entries {
            let _ = writeln!(source, "        {line},");
        }
        let _ = writeln!(source, "    ];");
    }
    for child in children {
        let _ = writeln!(source, "    out.extend(self::{child}::{name}());");
    }
    let _ = writeln!(source, "    out");
    let _ = writeln!(source, "}}");
    source
}

fn root_register(carried: &Carried) -> String {
    let mut source = String::new();
    let _ = writeln!(
        source,
        "/// Register this crate's gridmate wire types into a composing host."
    );
    let _ = writeln!(
        source,
        "pub fn register<D>(ctx: &mut az_gem_contract::GemContext<'_, D>) {{"
    );
    if carried.classes {
        let _ = writeln!(
            source,
            "    ctx.registrar::<{CLASS}>().register_many(classes());"
        );
    }
    if carried.fragments {
        let _ = writeln!(
            source,
            "    ctx.registrar::<{FRAGMENT}>().register_many(fragments());"
        );
    }
    if carried.introspects {
        let _ = writeln!(source, "    #[cfg(debug_assertions)]");
        let _ = writeln!(
            source,
            "    ctx.registrar::<{INTROSPECT}>().register_many(introspects());"
        );
    }
    let _ = writeln!(source, "}}");
    source
}

/// Replace the marked block, or append it.
///
/// Replacement rather than append-only: the pass runs again whenever a type is
/// added, and a second block would be a second answer to which types this
/// module owns.
fn splice(text: &str, block: &str) -> String {
    let Some(begin) = text.find(BEGIN) else {
        let mut source = text.to_owned();
        if !source.ends_with('\n') {
            source.push('\n');
        }
        source.push('\n');
        source.push_str(block);
        return source;
    };
    let end = text[begin..]
        .find(END)
        .map(|offset| begin + offset + END.len())
        .map_or(text.len(), |end| {
            end + usize::from(text[end..].starts_with('\n'))
        });
    let mut source = text[..begin].to_owned();
    source.push_str(block);
    source.push_str(&text[end..]);
    source
}

#[cfg(test)]
mod tests {
    use std::fs;

    use super::*;

    fn crate_root() -> tempfile::TempDir {
        let temp = tempfile::tempdir().expect("tempdir");
        let src = temp.path();
        fs::create_dir_all(src.join("combat")).expect("create combat module");
        fs::write(
            src.join("lib.rs"),
            "pub mod combat;\npub mod solo;\n\n#[derive(ClassDesc, Marshaler)]\n#[class_desc(type_index = 1)]\npub struct RootOnly;\n",
        )
        .expect("write lib");
        fs::write(
            src.join("solo.rs"),
            "#[derive(ClassDesc, Message, Marshaler)]\n#[class_desc(type_index = 2)]\npub struct Ping;\n",
        )
        .expect("write solo");
        fs::write(src.join("combat").join("mod.rs"), "pub mod damage;\n")
            .expect("write combat mod");
        fs::write(
            src.join("combat").join("damage.rs"),
            concat!(
                "#[derive(ClassDesc, ReplicatedState, Marshaler)]\n",
                "#[class_desc(type_index = 3)]\n",
                "pub struct DamageState;\n",
                "\n",
                "#[derive(ReplicatedState, Marshaler)]\n",
                "pub struct Untethered;\n",
                "\n",
                "#[derive(ClassDesc, Marshaler)]\n",
                "pub struct Boxed<T>;\n",
            ),
        )
        .expect("write damage");
        temp
    }

    fn planned(temp: &tempfile::TempDir) -> WirePlan {
        plan(temp.path(), &CodegenContext::inline()).expect("wire plan")
    }

    fn rendered<'a>(plan: &'a WirePlan, name: &str) -> &'a str {
        &plan
            .files
            .iter()
            .find(|file| file.path.ends_with(name))
            .unwrap_or_else(|| panic!("no rendered block for {name}"))
            .source
    }

    #[test]
    fn a_message_takes_the_message_constructor_and_owes_an_introspector() {
        let temp = crate_root();
        let plan = planned(&temp);
        let solo = rendered(&plan, "solo.rs");

        assert!(solo.contains("ClassRegistration::of_message::<Ping>()"));
        assert!(!solo.contains("ClassRegistration::of::<Ping>()"));
        assert!(solo.contains("#[cfg(debug_assertions)]"));
        assert!(solo.contains("DebugIntrospect::of::<Ping>()"));
        assert!(
            !solo.contains("fn fragments"),
            "a module with no fragment carries no fragment function"
        );
    }

    #[test]
    fn a_replicated_state_class_is_both_a_class_and_a_fragment() {
        let temp = crate_root();
        let plan = planned(&temp);
        let damage = rendered(&plan, "damage.rs");

        assert!(damage.contains("ClassRegistration::of::<DamageState>()"));
        assert!(damage.contains("FragmentRegistration::of::<DamageState>()"));
        assert!(
            !damage.contains("DebugIntrospect"),
            "a non-message class owes no introspector"
        );
    }

    /// The two shapes no site can name. The `ReplicatedState`-without-`ClassDesc`
    /// case is the one the old derive dropped in silence.
    #[test]
    fn unnameable_types_are_reported_rather_than_dropped() {
        let temp = crate_root();
        let plan = planned(&temp);

        let mut skips = plan
            .skipped
            .iter()
            .map(|skip| (skip.name.as_str(), skip.reason))
            .collect::<Vec<_>>();
        skips.sort();
        assert_eq!(
            skips,
            vec![
                ("Boxed", WireSkipReason::Generic),
                ("Untethered", WireSkipReason::FragmentWithoutClass),
            ]
        );
        assert_eq!(plan.unenumerated(), vec!["Boxed", "Untethered"]);
    }

    #[test]
    fn every_module_chains_into_one_crate_root_register() {
        let temp = crate_root();
        let plan = planned(&temp);
        let root = rendered(&plan, "lib.rs");
        let combat = rendered(&plan, "mod.rs");

        // A module that owns types and children returns a `Vec`; a leaf
        // returns a length-typed array.
        assert!(root.contains("pub(crate) fn classes() -> Vec<::gridmate::az::ClassRegistration>"));
        assert!(root.contains("out.extend(self::combat::classes());"));
        assert!(root.contains("out.extend(self::solo::classes());"));
        assert!(
            combat.contains("out.extend(self::damage::classes());"),
            "a mod.rs with no types of its own still chains its children"
        );
        assert!(
            rendered(&plan, "damage.rs")
                .contains("pub(crate) fn classes() -> [::gridmate::az::ClassRegistration; 1]")
        );

        // Only the crate root is public, and only registries something
        // contributes to appear.
        assert!(root.contains("pub fn register<D>(ctx: &mut az_gem_contract::GemContext<'_, D>)"));
        assert!(root.contains(
            "ctx.registrar::<::gridmate::hub::FragmentRegistration>().register_many(fragments());"
        ));
        assert!(!combat.contains("pub fn register<D>"));
        assert!(
            !root.contains("out.extend(self::solo::fragments());"),
            "solo contributes no fragment, so the root must not call for one"
        );
    }

    #[test]
    fn a_second_run_replaces_the_block_instead_of_appending_one() {
        let temp = crate_root();
        apply(&planned(&temp)).expect("apply");
        let once = fs::read_to_string(temp.path().join("solo.rs")).expect("read solo");

        apply(&planned(&temp)).expect("reapply");
        let twice = fs::read_to_string(temp.path().join("solo.rs")).expect("reread solo");

        assert_eq!(once, twice);
        assert_eq!(twice.matches(BEGIN).count(), 1);
        assert!(
            twice.contains("pub struct Ping;"),
            "authored source survives"
        );
    }
}
