[package]
name = "nw-asset"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[features]
default = ["oodle"]
oodle = ["nw-pak/oodle"]

[dependencies]
nw-filesystem.workspace = true
nw-jobs.workspace = true
nw-pak.workspace = true
thiserror.workspace = true
uuid.workspace = true
