use super::*;

pub(super) fn musical_ranking_data_manager_spec() -> NativeManagerSpec {
    let shape = NativeOneTableCrcKeyProjectionManager::new(
        ident("musical_ranking_data"),
        game_table("MusicalRankingTable"),
        game_row_type("MusicalRanking"),
        ident("MusicalRankingData"),
        ident("rankings"),
        ident("rankings_by_grade"),
        ident("grade"),
        ident("grade_id"),
        column("Grade"),
        ident("grade"),
        true,
        false,
        false,
        NativeDuplicateKeyPolicy::FirstWins,
        vec![
            projection_field(
                "minimum_score",
                "MinimumScore",
                "minimum_score",
                NativeProjectionTransform::F32,
            ),
            projection_field(
                "rank_game_event_id",
                "RankGameEventId",
                "rank_game_event_id",
                NativeProjectionTransform::OptionalString,
            ),
            projection_field(
                "rank_game_event_id_crc32",
                "RankGameEventId",
                "rank_game_event_id",
                NativeProjectionTransform::OptionalTrimmedLowercaseCrcString,
            ),
            projection_field(
                "musical_score_mult",
                "MusicalScoreMult",
                "musical_score_mult",
                NativeProjectionTransform::F32,
            ),
        ],
        vec![
            lookup(
                "musical_ranking_from_id",
                "grade",
                NativeCrcIndexLookupParameterKind::IntoCrc32,
            ),
            lookup(
                "musical_ranking",
                "grade",
                NativeCrcIndexLookupParameterKind::AsRefStr,
            ),
        ],
    )
    .expect("validated MusicalRankingDataManager shape")
    .with_source_row_field(ident("source_row"))
    .with_source_row_method(ident("source_row"))
    .with_descending_f32_index(NativeDescendingF32Index::new(
        ident("ranked_indices"),
        ident("minimum_score"),
        ident("ranked_musical_rankings"),
        ident("musical_ranking_for_score"),
        ident("score"),
    ))
    .with_rows_method(ident("rows"))
    .with_len_method(ident("len"))
    .with_is_empty_method(ident("is_empty"));

    manager_spec(
        "Javelin::MusicalRankingDataManager",
        "crate::MusicalRankingDataManager",
        "MusicalRankingTable",
        "MusicalRanking",
        vec![
            "Javelin::MusicalRankingDataManager::MusicalRankingDataManager",
            "Javelin::MusicalRankingDataManager::CacheAllDataTables",
        ],
    )
    .with_shape(NativeManagerShape::one_table_crc_key_projection(shape))
}
