use super::super::*;

pub(super) fn specs() -> Vec<NativeManagerSpec> {
    vec![
        crc_projection(CrcProjectionSpec {
            module: "vitals_modifier_data",
            table_name: "VitalsModifiers",
            row_type_name: "VitalsModifierData",
            data_type: "VitalsModifierData",
            entries_field: "modifiers",
            index_field: "rows_by_crc",
            key_field: "category_id",
            crc_field: "category_id_crc",
            key_column: "CategoryId",
            key_getter: "category_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: true,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "category_damage_mod",
                    "CategoryDamageMod",
                    "category_damage_mod",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "category_health_mod",
                    "CategoryHealthMod",
                    "category_health_mod",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "category_stamina_mod",
                    "CategoryStaminaMod",
                    "category_stamina_mod",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "category_drop_chance_mod",
                    "CategoryDropChanceMod",
                    "category_drop_chance_mod",
                    NativeProjectionTransform::F32,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "vitals_modifier_data_from_id",
                    "category_id",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "vitals_modifier_data",
                    "category_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "vitals_modifier_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("modifiers"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::VitalsModifierDataManager",
            rust_type: "crate::VitalsModifierDataManager",
            ghidra_functions: vec![
                "Javelin::VitalsModifierDataManager::VitalsModifierDataManager",
                "Javelin::VitalsModifierDataManager::CacheAllDataTables",
            ],
        }),
        dynamic_difficulty_data_manager_spec(),
        xml_product_asset_resource_manager_spec(
            "Javelin::CameraSettingsDataManager",
            "crate::CameraSettingsDataManager",
            vec![product_asset_resource(
                "libs/camera/gamecamera.xml",
                "newworld_plugin::assets::camera_settings::GameCameraSettingsAsset",
                "newworld_plugin::assets::camera_settings::GameCameraSettings",
                "game_camera_settings",
                "settings",
                "settings",
            )],
            vec!["Javelin::CameraSettingsDataManager::CameraSettingsDataManager"],
        ),
        product_asset_resource_manager_spec(
            "Javelin::ArmorOffsetDataManager",
            "crate::ArmorOffsetDataManager",
            vec![product_asset_resource(
                "sharedassets/genericassets/items/armoroffsets.aoffdb",
                "newworld_plugin::assets::armor_offset_database::ArmorOffsetDatabaseAsset",
                "newworld_plugin::assets::armor_offset_database::ArmorOffsetDatabase",
                "armor_offset_database",
                "database",
                "database",
            )],
            vec![
                "Javelin::ArmorOffsetDataManager::ArmorOffsetDataManager",
                "Javelin::ArmorOffsetDataManager::LoadArmorOffsetDatabase",
            ],
        ),
        product_asset_resource_manager_spec(
            "Javelin::EquipTypesDataManager",
            "crate::EquipTypesDataManager",
            vec![product_asset_resource(
                "sharedassets/genericassets/items/equiptypesdatabase.equipdb",
                "newworld_plugin::assets::equip_types_database::EquipTypesDatabaseAsset",
                "newworld_plugin::assets::equip_types_database::EquipTypesDatabase",
                "equip_types_database",
                "database",
                "database",
            )],
            vec!["Javelin::EquipTypesDataManager::EquipTypesDataManager"],
        ),
        product_asset_resource_manager_spec(
            "Javelin::GameDebugSettingsManager",
            "crate::GameDebugSettingsManager",
            vec![product_asset_resource(
                "sharedassets/genericassets/debug/gamedebugsettings.gds",
                "newworld_plugin::assets::game_debug_settings::GameDebugSettingsAsset",
                "newworld_plugin::assets::game_debug_settings::GameDebugSettings",
                "game_debug_settings",
                "settings",
                "settings",
            )],
            vec!["Javelin::GameDebugSettingsManager::GameDebugSettingsManager"],
        ),
        product_asset_resource_manager_spec(
            "Javelin::UiDataManager",
            "crate::UiDataManager",
            vec![product_asset_resource(
                "sharedassets/genericassets/ui/uidatabase.uidb",
                "newworld_plugin::assets::ui_database::UiDatabaseAsset",
                "newworld_plugin::assets::ui_database::UiDatabase",
                "ui_database",
                "database",
                "database",
            )],
            vec![
                "Javelin::UiDataManager::UiDataManager",
                "Javelin::UiDataManager::CacheAllData",
            ],
        ),
        player_data_manager_spec(),
        crc_projection(CrcProjectionSpec {
            module: "player_milestone_modal_data",
            table_name: "PlayerMilestoneModals",
            row_type_name: "PlayerMilestoneModalStaticData",
            data_type: "PlayerMilestoneModalData",
            entries_field: "modals",
            index_field: "modals_by_crc",
            key_field: "player_milestone_modal_id",
            crc_field: "player_milestone_modal_id_crc",
            key_column: "PlayerMilestoneModalId",
            key_getter: "player_milestone_modal_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "modal_screen_state",
                    "ModalScreenState",
                    "modal_screen_state",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "modal_milestone_conditional",
                    "ModalMilestoneConditional",
                    "modal_milestone_conditional",
                    NativeProjectionTransform::String,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "player_milestone_modal_data",
                    "modal_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "player_milestone_modal_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "player_milestone_modal_data_from_id",
                    "modal_id",
                    NativeCrcIndexLookupParameterKind::IntoCrc32,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::PlayerMilestoneModalDataManager",
            rust_type: "crate::PlayerMilestoneModalDataManager",
            ghidra_functions: vec![
                "Javelin::PlayerMilestoneModalDataManager::PlayerMilestoneModalDataManager",
                "Javelin::PlayerMilestoneModalDataManager::CacheAllDataTables",
            ],
        }),
        crest_part_data_manager_spec(),
        social_data_manager_spec(),
        crc_projection(CrcProjectionSpec {
            module: "crafting_category_data",
            table_name: "CraftingCategories",
            row_type_name: "CraftingCategoryData",
            data_type: "CraftingCategoryData",
            entries_field: "categories",
            index_field: "categories_by_crc",
            key_field: "category_id",
            crc_field: "category_id_crc",
            key_column: "CategoryID",
            key_getter: "category_id",
            skip_empty_key: false,
            trim_key: false,
            reject_zero_crc: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::Overwrite,
            source_row_field: None,
            source_row_method: None,
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "image_path",
                    "ImagePath",
                    "image_path",
                    NativeProjectionTransform::OptionalStringDefaultEmpty,
                ),
                projection_field(
                    "display_text",
                    "DisplayText",
                    "display_text",
                    NativeProjectionTransform::OptionalStringDefaultEmpty,
                ),
                projection_field(
                    "description",
                    "Description",
                    "description",
                    NativeProjectionTransform::OptionalStringDefaultEmpty,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "crafting_category_data_from_id",
                    "category_id",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "crafting_category_data",
                    "category_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "crafting_category_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: None,
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::CraftingCategoryDataManager",
            rust_type: "crate::CraftingCategoryDataManager",
            ghidra_functions: vec![
                "Javelin::CraftingCategoryDataManager::CacheAllDataTables",
                "Javelin::CraftingCategoryDataManager::GetCraftingCategoryData",
            ],
        }),
        crc_projection(CrcProjectionSpec {
            module: "diverted_loot_data",
            table_name: "DivertedLootMaster",
            row_type_name: "DivertedLootData",
            data_type: "DivertedLootData",
            entries_field: "rows",
            index_field: "rows_by_crc",
            key_field: "key",
            crc_field: "id",
            key_column: "Id",
            key_getter: "id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: true,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("diverted_loot_data_for_source_row"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "count_to_next_level",
                    "CountToNextLevel",
                    "count_to_next_level",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "timeframe_seconds",
                    "TimeframeSeconds",
                    "timeframe_seconds",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "yellow_diverted_loot_modifier",
                    "YellowDivertedLootModifier",
                    "yellow_diverted_loot_modifier",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "red_diverted_loot_modifier",
                    "RedDivertedLootModifier",
                    "red_diverted_loot_modifier",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "yellow_xp_multiplier",
                    "YellowXpMultiplier",
                    "yellow_xp_multiplier",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "red_xp_multiplier",
                    "RedXpMultiplier",
                    "red_xp_multiplier",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "green_notification_loc_tag",
                    "GreenNotificationLocTag",
                    "green_notification_loc_tag",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "yellow_notification_loc_tag",
                    "YellowNotificationLocTag",
                    "yellow_notification_loc_tag",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "red_notification_loc_tag",
                    "RedNotificationLocTag",
                    "red_notification_loc_tag",
                    NativeProjectionTransform::String,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "diverted_loot_data_from_id",
                    "id",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "diverted_loot_data",
                    "id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "diverted_loot_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::DivertedLootDataManager",
            rust_type: "crate::DivertedLootDataManager",
            ghidra_functions: vec![
                "Javelin::DivertedLootDataManager::DivertedLootDataManager",
                "Javelin::DivertedLootDataManager::CacheAllDataTables",
            ],
        }),
        encumbrance_data_manager_spec(),
        one_table_string_projection(StringProjectionSpec {
            module: "hunter_sight_data",
            table_name: "HunterSight",
            row_type_name: "HunterSightData",
            data_type: "HunterSightData",
            map_field: "hunter_sight",
            key_field: "sight_id",
            key_column: "SightID",
            key_getter: "sight_id",
            skip_empty_key: true,
            duplicate_key_policy: NativeDuplicateKeyPolicy::Overwrite,
            fields: vec![
                projection_field(
                    "status_effect_to_listen_for",
                    "StatusEffectToListenFor",
                    "status_effect_to_listen_for",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "sight_category_flag",
                    "SightCategoryFlag",
                    "sight_category_flag",
                    NativeProjectionTransform::PlusJoinedList,
                ),
            ],
            lookup_methods: vec![
                string_lookup(
                    "hunter_sight_data",
                    "sight_id",
                    NativeStringLookupParameterKind::StrRef,
                    NativeStringLookupTarget::Key,
                ),
                string_lookup(
                    "hunter_sight_data_by_key",
                    "sight_id",
                    NativeStringLookupParameterKind::StrRef,
                    NativeStringLookupTarget::Key,
                ),
                string_lookup(
                    "hunter_sight_data_for_status_effect",
                    "status_effect_id",
                    NativeStringLookupParameterKind::StrRef,
                    NativeStringLookupTarget::Field(ident("status_effect_to_listen_for")),
                ),
                string_lookup(
                    "hunter_sight_data_for_status_effect_key",
                    "status_effect_id",
                    NativeStringLookupParameterKind::StrRef,
                    NativeStringLookupTarget::Field(ident("status_effect_to_listen_for")),
                ),
            ],
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::HunterSightDataManager",
            rust_type: "crate::HunterSightDataManager",
            ghidra_functions: vec![
                "Javelin::HunterSightDataManager::HunterSightDataManager",
                "Javelin::HunterSightDataManager::CacheHunterSightDataTables",
                "Javelin::HunterSightDataManager::GetHunterSightData",
            ],
        }),
        crc_projection(CrcProjectionSpec {
            module: "influence_tower_data",
            table_name: "FactionControl_Towers",
            row_type_name: "InfluenceTowerDefinitions",
            data_type: "StaticInfluenceTowerData",
            entries_field: "influence_towers",
            index_field: "rows_by_crc",
            key_field: "tower_id",
            crc_field: "tower_crc",
            key_column: "TowerID",
            key_getter: "tower_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: true,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: None,
            row_filters: Vec::new(),
            fields: vec![
                projection_field("name", "Name", "name", NativeProjectionTransform::String),
                projection_field(
                    "description",
                    "Description",
                    "description",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "capture_time_secs",
                    "CaptureTimeInSeconds",
                    "capture_time_in_seconds",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "minimum_capture_time_secs",
                    "CaptureTimeMinimum",
                    "capture_time_minimum",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "capture_max_player_delta",
                    "CaptureMaxPlayerDelta",
                    "capture_max_player_delta",
                    NativeProjectionTransform::NonZeroU32,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "influence_tower_data_from_id",
                    "tower_id",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "influence_tower_data",
                    "tower_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "influence_tower_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("influence_towers"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::InfluenceTowerDataManager",
            rust_type: "crate::InfluenceTowerDataManager",
            ghidra_functions: vec![
                "Javelin::InfluenceTowerDataManager::InfluenceTowerDataManager",
                "Javelin::InfluenceTowerDataManager::CacheAllDataTables",
            ],
        }),
        crc_projection(CrcProjectionSpec {
            module: "house_type_data",
            table_name: "HouseTypes",
            row_type_name: "HouseTypeData",
            data_type: "HouseTypeData",
            entries_field: "house_types",
            index_field: "rows_by_crc",
            key_field: "house_type_id",
            crc_field: "house_type_crc",
            key_column: "HouseTypeID",
            key_getter: "house_type_id",
            skip_empty_key: true,
            trim_key: true,
            reject_zero_crc: true,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: None,
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "cost",
                    "Cost",
                    "cost",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "fast_travel_cooldown_secs",
                    "Fast Travel Cooldown Time (Minutes)",
                    "fast_travel_cooldown_time_minutes",
                    NativeProjectionTransform::F32MinutesToSeconds,
                ),
                projection_field(
                    "territory_standing_required_level",
                    "Territory Standing Required Level",
                    "territory_standing_required_level",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "max_total_housing_items_without_perks",
                    "Max Number Total Housing Items without Perks",
                    "max_number_total_housing_items_without_perks",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "localization_tag",
                    "Localization Tag",
                    "localization_tag",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "housing_tag_limits",
                    "Housing Tag Limits",
                    "housing_tag_limits",
                    NativeProjectionTransform::NonEmptyStringList,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "house_type_data_from_id",
                    "house_type_id",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "house_type_data",
                    "house_type_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "house_type_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("house_types"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::HouseTypeDataManager",
            rust_type: "crate::HouseTypeDataManager",
            ghidra_functions: vec![
                "Javelin::HouseTypeDataManager::HouseTypeDataManager",
                "Javelin::HouseTypeDataManager::CacheAllDataTables",
            ],
        }),
        crc_projection(CrcProjectionSpec {
            module: "mana_data",
            table_name: "ManaCosts_Player",
            row_type_name: "ManaData",
            data_type: "ManaData",
            entries_field: "rows",
            index_field: "rows_by_crc",
            key_field: "cost_id",
            crc_field: "cost_id_crc32",
            key_column: "CostID",
            key_getter: "cost_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: true,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "mana_cost",
                    "ManaCost",
                    "mana_cost",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "dev_helper_legend",
                    "DevHelper_Legend",
                    "dev_helper_legend",
                    NativeProjectionTransform::OptionalString,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "mana_data_from_id",
                    "cost_id",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "mana_data",
                    "cost_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "mana_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::ManaDataManager",
            rust_type: "crate::ManaDataManager",
            ghidra_functions: vec![
                "Javelin::ManaDataManager::ManaDataManager",
                "Javelin::ManaDataManager::CacheAllDataTables",
            ],
        }),
    ]
}
