use super::super::*;

pub(super) fn specs() -> Vec<NativeManagerSpec> {
    vec![
        ability_data_manager_spec(),
        objectives_data_manager_spec(),
        contribution_data_manager_spec(),
        buff_bucket_data_manager_spec(),
        structure_data_manager_spec(),
        reusable_scoreboard_data_manager_spec(),
        mount_hit_volume_data_manager_spec(),
        affix_data_manager_spec(),
        character_attribute_data_manager_spec(),
        elemental_mutation_perks_static_data_manager_spec(),
        flexible_mission_board_data_manager_spec(),
        crc_projection(CrcProjectionSpec {
            module: "achievement_data",
            table_name: "AchievementDataTable",
            row_type_name: "AchievementData",
            data_type: "AchievementData",
            entries_field: "achievements",
            index_field: "rows_by_crc",
            key_field: "achievement_id",
            crc_field: "achievement_id_crc",
            key_column: "AchievementID",
            key_getter: "achievement_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::Error,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            row_filters: Vec::new(),
            fields: vec![
                capped_u16_projection_field(
                    "achievement_index",
                    "AchievementIndex",
                    "achievement_index",
                    32_000,
                ),
                projection_field(
                    "category",
                    "Category",
                    "category",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "game_event_id",
                    "GameEventId",
                    "game_event_id",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "is_deprecated",
                    "Is Deprecated",
                    "is_deprecated",
                    NativeProjectionTransform::OptionalString,
                ),
            ],
            secondary_indexes: vec![secondary_u16_index(
                "rows_by_bit_index",
                "achievement_index",
                NativeDuplicateKeyPolicy::Error,
                vec![secondary_u16_lookup(
                    "achievement_data_by_bit_index",
                    "bit_index",
                )],
            )],
            lookup_methods: vec![
                lookup(
                    "achievement_data_from_id",
                    "achievement_id",
                    NativeCrcIndexLookupParameterKind::IntoCrc32,
                ),
                lookup(
                    "achievement_data",
                    "achievement_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "achievement_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::AchievementDataManager",
            rust_type: "crate::AchievementDataManager",
            ghidra_functions: vec!["Javelin::AchievementDataManager::GetAchievementData"],
        }),
        crc_projection(CrcProjectionSpec {
            module: "economy_tracker_data",
            table_name: "EconomyTrackers",
            row_type_name: "EconomyTrackerData",
            data_type: "EconomyTrackerData",
            entries_field: "rows",
            index_field: "rows_by_crc",
            key_field: "economy_tracker_key",
            crc_field: "economy_tracker_id",
            key_column: "EconomyTrackerID",
            key_getter: "economy_tracker_id",
            skip_empty_key: false,
            trim_key: false,
            reject_zero_crc: true,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("economy_tracker_data_for_source_row"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "alarm_type",
                    "AlarmType",
                    "alarm_type",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "threshold_config1",
                    "ThresholdConfig1",
                    "threshold_config1",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "metric_name1",
                    "MetricName1",
                    "metric_name1",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "enable_metric1",
                    "EnableMetric1",
                    "enable_metric1",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "threshold_config2",
                    "ThresholdConfig2",
                    "threshold_config2",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "metric_name2",
                    "MetricName2",
                    "metric_name2",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "enable_metric2",
                    "EnableMetric2",
                    "enable_metric2",
                    NativeProjectionTransform::Bool,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "economy_tracker_data_from_id",
                    "economy_tracker_id",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "economy_tracker_data",
                    "economy_tracker_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "economy_tracker_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::EconomyTrackerDataManager",
            rust_type: "crate::EconomyTrackerDataManager",
            ghidra_functions: vec!["Javelin::EconomyTrackerDataManager::FindGameSystemDataByKey"],
        }),
        crc_projection(CrcProjectionSpec {
            module: "diminishing_returns_data",
            table_name: "DiminishingReturnsTable",
            row_type_name: "DiminishingReturnsData",
            data_type: "DiminishingReturnsData",
            entries_field: "rows",
            index_field: "rows_by_id",
            key_field: "damage_type_key",
            crc_field: "damage_type_id",
            key_column: "DamageTypeId",
            key_getter: "damage_type_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: true,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("diminishing_returns_data_for_source_row"),
            row_filters: vec![
                f32_less_than_or_equal_zero_filter("NegativeStartValue", "negative_start_value"),
                i32_less_than_or_equal_zero_filter("LowerLimit", "lower_limit"),
                f32_greater_than_or_equal_zero_filter("PositiveStartValue", "positive_start_value"),
                f32_greater_than_or_equal_zero_filter("DiminishmentRate", "diminishment_rate"),
            ],
            fields: vec![
                projection_field(
                    "negative_start_value",
                    "NegativeStartValue",
                    "negative_start_value",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "lower_limit",
                    "LowerLimit",
                    "lower_limit",
                    NativeProjectionTransform::I32,
                ),
                projection_field(
                    "positive_start_value",
                    "PositiveStartValue",
                    "positive_start_value",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "upper_limit",
                    "UpperLimit",
                    "upper_limit",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "diminishment_rate",
                    "DiminishmentRate",
                    "diminishment_rate",
                    NativeProjectionTransform::F32,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "diminishing_returns_data_from_id",
                    "damage_type_id",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "diminishing_returns_data",
                    "damage_type_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "diminishing_returns_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::DiminishingReturnsDataManager",
            rust_type: "crate::DiminishingReturnsDataManager",
            ghidra_functions: vec![
                "Javelin::DiminishingReturnsDataManager::DiminishingReturnsDataManager",
                "Javelin::DiminishingReturnsDataManager::CacheAllDataTables",
            ],
        }),
        crc_projection(CrcProjectionSpec {
            module: "loot_tag_preset_data",
            table_name: "LootTagPresets",
            row_type_name: "LootTagPresetData",
            data_type: "LootTagPresetData",
            entries_field: "rows",
            index_field: "rows_by_crc",
            key_field: "preset_key",
            crc_field: "preset_id",
            key_column: "LootTagPresetID",
            key_getter: "loot_tag_preset_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: true,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("loot_tag_preset_data_for_source_row"),
            row_filters: Vec::new(),
            fields: vec![projection_field(
                "loot_tags",
                "LootTags",
                "loot_tags",
                NativeProjectionTransform::LowercaseCrcStringList,
            )],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "loot_tag_preset_data_from_id",
                    "loot_tag_preset_id",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "loot_tag_preset_data",
                    "loot_tag_preset_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "loot_tag_preset_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::LootTagPresetDataManager",
            rust_type: "crate::LootTagPresetDataManager",
            ghidra_functions: vec![
                "Javelin::LootTagPresetDataManager::LootTagPresetDataManager",
                "Javelin::LootTagPresetDataManager::CacheAllDataTables",
            ],
        }),
        numeric_projection(NumericProjectionSpec {
            module: "pvp_rank_data",
            table_name: "PvPXP",
            row_type_name: "PvPRankData",
            data_type: "StaticPvpRankData",
            entries_field: "rows",
            index_field: "rows_by_rank",
            key_field: "rank",
            key_column: "Level",
            key_getter: "level",
            key_type: NativeNumericKeyType::U16,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("pvp_rank_data_for_source_row"),
            fields: vec![
                projection_field(
                    "display_name",
                    "DisplayName",
                    "display_name",
                    NativeProjectionTransform::OptionalStringDefaultEmpty,
                ),
                projection_field(
                    "stage1_xp",
                    "Stage1XP",
                    "stage1_xp",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "stage2_xp",
                    "Stage2XP",
                    "stage2_xp",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "stage3_xp",
                    "Stage3XP",
                    "stage3_xp",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "skip_stage1_salt",
                    "SkipStage1Salt",
                    "skip_stage1_salt",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "skip_stage2_salt",
                    "SkipStage2Salt",
                    "skip_stage2_salt",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "skip_stage3_salt",
                    "SkipStage3Salt",
                    "skip_stage3_salt",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "azoth_salt_reward",
                    "AzothSaltReward",
                    "azoth_salt_reward",
                    NativeProjectionTransform::U32,
                ),
                projection_field(
                    "game_event_id",
                    "GameEventId",
                    "game_event_id",
                    NativeProjectionTransform::OptionalLowercaseCrcStringDefaultZero,
                ),
                projection_field(
                    "border_tier",
                    "BorderTier",
                    "border_tier",
                    NativeProjectionTransform::U32,
                ),
                projection_field(
                    "reward_description",
                    "RewardDescription",
                    "reward_description",
                    NativeProjectionTransform::OptionalStringDefaultEmpty,
                ),
            ],
            lookup_methods: vec![numeric_lookup(
                "pvp_rank_data",
                "rank",
                NativeNumericLookupParameterKind::U16,
            )],
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::PvpRankDataManager",
            rust_type: "crate::PvpRankDataManager",
            ghidra_functions: vec![
                "Javelin::PvpRankDataManager::PvpRankDataManager",
                "Javelin::PvpRankDataManager::CacheAllDataTables",
            ],
        }),
        validation_crc_projection(
            CrcProjectionSpec {
                module: "archetype_data",
                table_name: "ArchetypeDataTable",
                row_type_name: "ArchetypeData",
                data_type: "ArchetypeData",
                entries_field: "archetypes",
                index_field: "archetypes_by_id",
                key_field: "archetype_id",
                crc_field: "archetype_id_crc",
                key_column: "ArchetypeId",
                key_getter: "archetype_id",
                skip_empty_key: true,
                trim_key: false,
                reject_zero_crc: false,
                duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
                source_row_field: None,
                source_row_method: None,
                row_filters: Vec::new(),
                fields: vec![
                    foreign_key_target_field(
                        "backstory_id",
                        "BackstoryId",
                        "backstory_id",
                        NativeProjectionTransform::ForeignKeyTargetKey,
                        "Backstory",
                        "BackstoryDefinition",
                        "BackstoryId",
                        "backstory_id",
                    ),
                    foreign_key_target_field(
                        "backstory_id_crc",
                        "BackstoryId",
                        "backstory_id",
                        NativeProjectionTransform::ForeignKeyTargetLowercaseCrc,
                        "Backstory",
                        "BackstoryDefinition",
                        "BackstoryId",
                        "backstory_id",
                    ),
                    projection_field(
                        "ftue_loot_bag_game_event",
                        "FTUELootBagGameEvent",
                        "ftue_loot_bag_game_event",
                        NativeProjectionTransform::OptionalString,
                    ),
                    projection_field(
                        "consumable_item_list",
                        "ConsumableItemList",
                        "consumable_item_list",
                        NativeProjectionTransform::String,
                    ),
                ],
                secondary_indexes: Vec::new(),
                lookup_methods: vec![
                    lookup(
                        "archetype_data",
                        "archetype_id",
                        NativeCrcIndexLookupParameterKind::StrRef,
                    ),
                    lookup(
                        "archetype_data_by_key",
                        "key",
                        NativeCrcIndexLookupParameterKind::StrRef,
                    ),
                ],
                ids_method: None,
                rows_method: Some("rows"),
                len_method: Some("len"),
                is_empty_method: Some("is_empty"),
                ghidra_class: "Javelin::ArchetypeDataManager",
                rust_type: "crate::ArchetypeDataManager",
                ghidra_functions: vec![
                    "Javelin::ArchetypeDataManager::ArchetypeDataManager",
                    "Javelin::ArchetypeDataManager::CacheAllDataTables",
                ],
            },
            NativeSchemaProjectionFields::all_non_key(),
        ),
        pvp_balance(PvpBalanceSpec {
            module: "arena_pvp_balance_data",
            table_name: "ArenaPvpBalanceTable",
            row_type_name: "ArenaBalanceData",
            lookup_methods: vec![
                lookup(
                    "arena_pvp_balance_data_from_id",
                    "balance_target",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "arena_pvp_balance_data",
                    "balance_target",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "arena_pvp_balance_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ghidra_class: "Javelin::ArenaPvpBalanceDataManager",
            rust_type: "crate::ArenaPvpBalanceDataManager",
            ghidra_functions: vec![
                "Javelin::ArenaPvpBalanceDataManager::ArenaPvpBalanceDataManager",
                "Javelin::ArenaPvpBalanceDataManager::CacheAllDataTables",
            ],
        }),
        pvp_balance(PvpBalanceSpec {
            module: "capture_the_flag_pvp_balance_data",
            table_name: "CaptureTheFlagPvpBalanceTable",
            row_type_name: "CaptureTheFlagBalanceData",
            lookup_methods: vec![
                lookup(
                    "capture_the_flag_pvp_balance_data_from_id",
                    "balance_target",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "capture_the_flag_pvp_balance_data",
                    "balance_target",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "capture_the_flag_pvp_balance_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ghidra_class: "Javelin::CaptureTheFlagPvpBalanceDataManager",
            rust_type: "crate::CaptureTheFlagPvpBalanceDataManager",
            ghidra_functions: vec![
                "Javelin::CaptureTheFlagPvpBalanceDataManager::CaptureTheFlagPvpBalanceDataManager",
                "Javelin::CaptureTheFlagPvpBalanceDataManager::CacheAllDataTables",
            ],
        }),
        categorical_progression_data_manager_spec(),
        table_family_numeric_projection(TableFamilyNumericProjectionSpec {
            module: "categorical_progression_rank_data",
            tables: categorical_progression_rank_data_tables(),
            tables_type: "CategoricalProgressionRankDataTables",
            table_type: "CategoricalProgressionRankDataTable",
            handle_type: "CategoricalProgressionRankDataHandle",
            row_alias: "CategoricalProgressionRankDataRow",
            data_type: "CategoricalProgressionRankData",
            entries_field: "ranks",
            index_field: "rows_by_rank",
            key_field: "rank",
            key_column: "Rank",
            key_getter: "rank",
            key_type: NativeNumericKeyType::U16,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_handle_field: None,
            source_handle_method: None,
            fields: Vec::new(),
            lookup_methods: vec![numeric_lookup(
                "categorical_progression_rank_data_from_rank",
                "rank",
                NativeNumericLookupParameterKind::U16,
            )],
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::CategoricalProgressionRankDataManager",
            rust_type: "crate::CategoricalProgressionRankDataManager",
            ghidra_functions: vec![
                "Javelin::CategoricalProgressionRankDataManager::CategoricalProgressionRankDataManager",
                "Javelin::CategoricalProgressionRankDataManager::CacheAllDataTables",
            ],
        }),
        crc_projection(CrcProjectionSpec {
            module: "cooldown_data",
            table_name: "Cooldowns_Player",
            row_type_name: "CooldownData",
            data_type: "StaticCooldownData",
            entries_field: "rows",
            index_field: "rows_by_ability_id",
            key_field: "ability_id",
            crc_field: "ability_id_crc",
            key_column: "AbilityID",
            key_getter: "ability_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: true,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("row_at"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field("time", "Time", "time", NativeProjectionTransform::F32),
                projection_field(
                    "min_time",
                    "MinTime",
                    "min_time",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "weapon_tag",
                    "WeaponTag",
                    "weapon_tag",
                    NativeProjectionTransform::String,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![lookup(
                "by_ability_id",
                "ability_id",
                NativeCrcIndexLookupParameterKind::AsRefStr,
            )],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::CooldownsPlayerManager",
            rust_type: "crate::CooldownsPlayerManager",
            ghidra_functions: Vec::new(),
        }),
        level_disparity_data_manager_spec(),
        leaderboard_rewards_data_manager_spec(),
        expansion_data_manager_spec(),
        territory_progression_data_manager_spec(),
        item_skin_data_manager_spec(),
        spell_data_manager_spec(),
        lore_data_manager_spec(),
        timeline_registry_manager_spec(),
        costume_change_data_manager_spec(),
        cutscene_camera_data_manager_spec(),
        darkness_data_manager_spec(),
        difficulty_scaling_data_manager_spec(),
    ]
}
