use super::super::*;

pub(super) fn specs() -> Vec<NativeManagerSpec> {
    vec![
        crc_projection_with_foreign_key_target_inputs(CrcProjectionSpec {
            module: "game_mode_scheduler_data",
            table_name: "GameModeScheduler",
            row_type_name: "GameModeSchedulerStaticData",
            data_type: "GameModeSchedulerData",
            entries_field: "schedules",
            index_field: "schedules_by_crc",
            key_field: "game_mode_key",
            crc_field: "game_mode_id",
            key_column: "GameModeId",
            key_getter: "game_mode_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: true,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("game_mode_scheduler_data_for_source_row"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "category_key",
                    "Category",
                    "category",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "category",
                    "Category",
                    "category",
                    NativeProjectionTransform::LowercaseCrcString,
                ),
                foreign_key_target_field(
                    "quest_active_achievement_id",
                    "QuestActiveAchievementId",
                    "quest_active_achievement_id",
                    NativeProjectionTransform::ForeignKeyTargetLowercaseCrc,
                    "AchievementDataTable",
                    "AchievementData",
                    "AchievementID",
                    "achievement_id",
                ),
                foreign_key_target_field(
                    "quest_completion_achievement_id",
                    "QuestCompletionAchievementId",
                    "quest_completion_achievement_id",
                    NativeProjectionTransform::ForeignKeyTargetLowercaseCrc,
                    "AchievementDataTable",
                    "AchievementData",
                    "AchievementID",
                    "achievement_id",
                ),
                foreign_key_target_field(
                    "scheduled_gm_entry_achievement_id",
                    "ScheduledGMEntryAchievementId",
                    "scheduled_gm_entry_achievement_id",
                    NativeProjectionTransform::ForeignKeyTargetLowercaseCrc,
                    "AchievementDataTable",
                    "AchievementData",
                    "AchievementID",
                    "achievement_id",
                ),
                foreign_key_target_field(
                    "scheduled_gm_completion_achievement_id",
                    "ScheduledGMCompletionAchievementId",
                    "scheduled_gm_completion_achievement_id",
                    NativeProjectionTransform::ForeignKeyTargetLowercaseCrc,
                    "AchievementDataTable",
                    "AchievementData",
                    "AchievementID",
                    "achievement_id",
                ),
                projection_field(
                    "scheduled_gm_completion_game_event_key",
                    "ScheduledGMCompletionGameEvent",
                    "scheduled_gm_completion_game_event",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "scheduled_gm_completion_game_event",
                    "ScheduledGMCompletionGameEvent",
                    "scheduled_gm_completion_game_event",
                    NativeProjectionTransform::LowercaseCrcString,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "game_mode_scheduler_data_from_id",
                    "game_mode_id",
                    NativeCrcIndexLookupParameterKind::IntoCrc32,
                ),
                lookup(
                    "game_mode_scheduler_data",
                    "game_mode_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "game_mode_scheduler_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("schedules"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::GameModeSchedulerDataManager",
            rust_type: "crate::GameModeSchedulerDataManager",
            ghidra_functions: vec![
                "Javelin::GameModeSchedulerDataManager::GameModeSchedulerDataManager",
                "Javelin::GameModeSchedulerDataManager::CacheAllDataTables",
            ],
        }),
        one_table_crc(OneTableCrcSpec {
            module: "world_event_category_data",
            table_name: "WorldEventCategories",
            row_type_name: "WorldEventCategoryData",
            row_alias: "WorldEventCategoryData",
            table_field: "table",
            key_column: "CategoryId",
            key_getter: "category_id",
            row_key_method: None,
            row_crc_method: Some("category_id_crc"),
            hash_policy: NativeCrcHashPolicy::Lowercase,
            reject_zero_crc: true,
            lookup_methods: vec![
                lookup(
                    "world_event_category_data_by_crc32",
                    "category_id",
                    NativeCrcIndexLookupParameterKind::IntoCrc32,
                ),
                lookup(
                    "world_event_category_data",
                    "category_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            source_row_method: Some("source_row"),
            rows_method: Some("categories"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::WorldEventCategoriesDataManager",
            rust_type: "crate::WorldEventCategoryDataManager",
            ghidra_functions: vec![
                "Javelin::WorldEventCategoriesDataManager::WorldEventCategoriesDataManager",
                "Javelin::WorldEventCategoriesDataManager::CacheAllDataTables",
            ],
        }),
        owned_string(OwnedStringSpec {
            module: "achievement_meta_data",
            table_name: "AchievementMetaDataTable",
            row_type_name: "AchievementMetaData",
            row_alias: "AchievementMetaDataRow",
            table_field: "table",
            indexes_field: "achievement_meta_data",
            indexed_type: "IndexedAchievementMetaData",
            indexes_type: "AchievementMetaDataIndexes",
            indexed_key_field: "achievement_meta_data_id",
            key_column: "AchievementMetaDataId",
            key_getter: "achievement_meta_data_id",
            skip_empty_key: true,
            duplicate_manager_label: "AchievementMetaDataManager",
            duplicate_key_label: "AchievementMetaDataId",
            lookup_methods: vec![
                lookup(
                    "achievement_meta_data",
                    "achievement_meta_data_id",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
                lookup(
                    "achievement_meta_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
            ],
            ghidra_class: "Javelin::AchievementMetaDataManager",
            rust_type: "crate::AchievementMetaDataManager",
            ghidra_functions: vec![
                "Javelin::AchievementMetaDataManager::AchievementMetaDataManager",
                "Javelin::AchievementMetaDataManager::CacheAllDataTables",
            ],
            ..OwnedStringSpec::default()
        }),
        owned_string(OwnedStringSpec {
            module: "faction_data",
            table_name: "Factions",
            row_type_name: "FactionData",
            row_alias: "FactionDataRow",
            table_field: "table",
            indexes_field: "factions",
            indexed_type: "IndexedFaction",
            indexes_type: "FactionIndexes",
            indexed_key_field: "faction_type",
            key_column: "FactionType",
            key_getter: "faction_type",
            skip_empty_key: true,
            duplicate_manager_label: "FactionDataManager",
            duplicate_key_label: "FactionType",
            lookup_methods: vec![
                lookup(
                    "faction",
                    "faction_type",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
                lookup(
                    "faction_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
            ],
            ghidra_class: "Javelin::FactionDataManager",
            rust_type: "crate::FactionDataManager",
            ghidra_functions: vec!["Javelin::FactionDataManager::FactionDataManager"],
            ..OwnedStringSpec::default()
        }),
        one_table_crc(OneTableCrcSpec {
            module: "faction_status_effect_data",
            table_name: "FactionStatusEffect",
            row_type_name: "FactionStatusEffectData",
            row_alias: "FactionStatusEffectData",
            table_field: "status_effects",
            key_column: "FactionStatusEffectID",
            key_getter: "faction_status_effect_id",
            row_key_method: Some("status_effect_key"),
            row_crc_method: Some("status_effect_crc"),
            reject_zero_crc: true,
            lookup_methods: vec![
                lookup(
                    "faction_status_effect_data_from_id",
                    "status_effect_id",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "faction_status_effect_data",
                    "status_effect_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "faction_status_effect_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            rows_method: Some("status_effects"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::FactionStatusEffectDataManager",
            rust_type: "crate::FactionStatusEffectDataManager",
            ghidra_functions: vec![
                "Javelin::FactionStatusEffectDataManager::FactionStatusEffectDataManager",
                "Javelin::FactionStatusEffectDataManager::CacheAllDataTables",
            ],
            ..OneTableCrcSpec::default()
        }),
        table_family_crc(TableFamilyCrcSpec {
            module: "game_event_data",
            tables_type: "GameEventDataTables",
            table_type: "GameEventDataTable",
            handle_type: "GameEventDataHandle",
            table_family_name: "GameEventData",
            row_type_name: "GameEventData",
            row_alias: "GameEventData",
            key_column: "EventID",
            key_getter: "event_id",
            row_crc_method: Some("event_id_crc32"),
            reject_zero_crc: false,
            lookup_methods: vec![
                lookup(
                    "game_event_data_from_id",
                    "event_id",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "game_event_data",
                    "event_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "game_event_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            source_handle_method: Some(("source_row", "handle")),
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::GameEventDataManager",
            rust_type: "crate::GameEventDataManager",
            ghidra_functions: vec![
                "Javelin::GameEventDataManager::GameEventDataManager",
                "Javelin::GameEventDataManager::CacheAllDataTables",
            ],
            ..TableFamilyCrcSpec::default()
        }),
        owned_string(OwnedStringSpec {
            module: "resource_item_data",
            table_name: "ResourceItemDefinitions",
            row_type_name: "ResourceItemDefinitions",
            row_alias: "ResourceItemDataRow",
            table_field: "table",
            indexes_field: "resources",
            indexed_type: "IndexedResourceItem",
            indexes_type: "ResourceItemIndexes",
            indexed_key_field: "resource_id",
            key_column: "ResourceID",
            key_getter: "resource_id",
            duplicate_manager_label: "ResourceItemDataManager",
            duplicate_key_label: "ResourceID",
            lookup_methods: vec![
                lookup(
                    "resource_item",
                    "resource_id",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
                lookup(
                    "resource_item_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
            ],
            ghidra_class: "Javelin::ResourceItemDataManager",
            rust_type: "crate::ResourceItemDataManager",
            ghidra_functions: vec!["Javelin::ResourceItemDataManager::ResourceItemDataManager"],
            ..OwnedStringSpec::default()
        }),
        table_family_owned_string(TableFamilyOwnedStringSpec {
            module: "perk_data",
            tables: perk_data_tables(),
            table_type: "PerkDataTable",
            handle_type: "PerkDataHandle",
            row_alias: "PerkDataRow",
            tables_field: "tables",
            indexes_field: "perks",
            indexed_type: "IndexedPerk",
            indexes_type: "PerkIndexes",
            indexed_key_field: "perk_id",
            indexed_source_field: "source",
            key_column: "PerkID",
            key_getter: "perk_id",
            skip_empty_key: true,
            ascii_case_insensitive: true,
            duplicate_manager_label: "PerkDataManager",
            duplicate_key_label: "PerkID",
            lookup_methods: vec![
                lookup("perk", "perk_id", NativeCrcIndexLookupParameterKind::StrRef),
                lookup(
                    "perk_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
                lookup(
                    "perk_from_id",
                    "perk_id",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
            ],
            ids_method: Some("perk_ids"),
            ghidra_class: "Javelin::PerkDataManager",
            rust_type: "crate::PerkDataManager",
            ghidra_functions: vec!["Javelin::PerkDataManager::PerkDataManager"],
            ..TableFamilyOwnedStringSpec::default()
        }),
        owned_string(OwnedStringSpec {
            module: "perk_exclusive_label_data",
            table_name: "PerkExclusiveLabels",
            row_type_name: "PerkExclusiveLabelData",
            row_alias: "PerkExclusiveLabelDataRow",
            table_field: "table",
            indexes_field: "labels",
            indexed_type: "IndexedPerkExclusiveLabel",
            indexes_type: "PerkExclusiveLabelIndexes",
            indexed_key_field: "label_id",
            key_column: "ExclusiveLabelID",
            key_getter: "exclusive_label_id",
            ascii_case_insensitive: true,
            duplicate_manager_label: "PerkExclusiveLabelDataManager",
            duplicate_key_label: "ExclusiveLabelID",
            lookup_methods: vec![
                lookup(
                    "exclusive_label",
                    "exclusive_label_id",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
                lookup(
                    "exclusive_label_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
                lookup(
                    "exclusive_label_from_id",
                    "exclusive_label_id",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
            ],
            source_row_method: Some("exclusive_label_at"),
            ids_method: Some("exclusive_label_ids"),
            ghidra_class: "Javelin::PerkExclusiveLabelDataManager",
            rust_type: "crate::PerkExclusiveLabelDataManager",
            ghidra_functions: vec![
                "Javelin::PerkExclusiveLabelDataManager::PerkExclusiveLabelDataManager",
            ],
            ..OwnedStringSpec::default()
        }),
        owned_string(OwnedStringSpec {
            module: "charm_filter_data",
            table_name: "CharmFilters",
            row_type_name: "CharmFilterData",
            row_alias: "CharmFilterDataRow",
            table_field: "table",
            indexes_field: "charm_filters",
            indexed_type: "IndexedCharmFilter",
            indexes_type: "CharmFilterIndexes",
            indexed_key_field: "filter_id",
            key_column: "FilterId",
            key_getter: "filter_id",
            skip_empty_key: true,
            duplicate_manager_label: "CharmFilterDataManager",
            duplicate_key_label: "FilterId",
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            lookup_methods: vec![
                lookup(
                    "charm_filter_data",
                    "filter_id",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
                lookup(
                    "charm_filter_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
            ],
            ghidra_class: "Javelin::CharmFilterDataManager",
            rust_type: "crate::CharmFilterDataManager",
            ghidra_functions: vec![
                "Javelin::CharmFilterDataManager::CharmFilterDataManager",
                "Javelin::CharmFilterDataManager::CacheAllDataTables",
            ],
            ..OwnedStringSpec::default()
        }),
        owned_string(OwnedStringSpec {
            module: "cinematic_video_static_data",
            table_name: "CinematicVideo",
            row_type_name: "CinematicVideoStaticData",
            row_alias: "CinematicVideoStaticDataRow",
            table_field: "table",
            indexes_field: "cinematic_videos",
            indexed_type: "IndexedCinematicVideo",
            indexes_type: "CinematicVideoIndexes",
            indexed_key_field: "cinematic_video_id",
            key_column: "CinematicVideoId",
            key_getter: "cinematic_video_id",
            skip_empty_key: true,
            duplicate_manager_label: "CinematicVideoStaticDataManager",
            duplicate_key_label: "CinematicVideoId",
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            lookup_methods: vec![
                lookup(
                    "cinematic_video_data",
                    "cinematic_video_id",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
                lookup(
                    "cinematic_video_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
            ],
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::CinematicVideoStaticDataManager",
            rust_type: "crate::CinematicVideoStaticDataManager",
            ghidra_functions: vec![
                "Javelin::CinematicVideoStaticDataManager::CinematicVideoStaticDataManager",
                "Javelin::CinematicVideoStaticDataManager::CacheAllDataTables",
            ],
            ..OwnedStringSpec::default()
        }),
        owned_string(OwnedStringSpec {
            module: "collectible_static_data",
            table_name: "Collectibles",
            row_type_name: "CollectibleStaticData",
            row_alias: "CollectibleStaticDataRow",
            table_field: "table",
            indexes_field: "collectibles",
            indexed_type: "IndexedCollectible",
            indexes_type: "CollectibleIndexes",
            indexed_key_field: "collectible_id",
            key_column: "CollectibleId",
            key_getter: "collectible_id",
            skip_empty_key: true,
            duplicate_manager_label: "CollectibleStaticDataManager",
            duplicate_key_label: "CollectibleId",
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            lookup_methods: vec![
                lookup(
                    "collectible_data",
                    "collectible_id",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
                lookup(
                    "collectible_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
            ],
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::CollectibleStaticDataManager",
            rust_type: "crate::CollectibleStaticDataManager",
            ghidra_functions: vec![
                "Javelin::CollectibleStaticDataManager::CollectibleStaticDataManager",
                "Javelin::CollectibleStaticDataManager::CacheAllDataTables",
            ],
            ..OwnedStringSpec::default()
        }),
        owned_string(OwnedStringSpec {
            module: "armor_item_data",
            table_name: "ArmorItemDefinitions",
            row_type_name: "ArmorItemDefinitions",
            row_alias: "ArmorItemDataRow",
            table_field: "table",
            indexes_field: "armor_items",
            indexed_type: "IndexedArmorItem",
            indexes_type: "ArmorItemIndexes",
            indexed_key_field: "weapon_id",
            key_column: "WeaponID",
            key_getter: "weapon_id",
            skip_empty_key: true,
            duplicate_manager_label: "ArmorItemDataManager",
            duplicate_key_label: "WeaponID",
            lookup_methods: vec![
                lookup(
                    "armor_item",
                    "weapon_id",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
                lookup(
                    "armor_item_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
            ],
            ghidra_class: "Javelin::ArmorItemDataManager",
            rust_type: "crate::ArmorItemDataManager",
            ghidra_functions: vec!["Javelin::ArmorItemDataManager::ArmorItemDataManager"],
            ..OwnedStringSpec::default()
        }),
        owned_string(OwnedStringSpec {
            module: "dye_item_data",
            table_name: "DyeItemDefinitions",
            row_type_name: "DyeItemDefinitions",
            row_alias: "DyeItemDataRow",
            table_field: "table",
            indexes_field: "dye_items",
            indexed_type: "IndexedDyeItem",
            indexes_type: "DyeItemIndexes",
            indexed_key_field: "dye_item_id",
            key_column: "DyeItemId",
            key_getter: "dye_item_id",
            skip_empty_key: true,
            duplicate_manager_label: "DyeItemDataManager",
            duplicate_key_label: "DyeItemId",
            lookup_methods: vec![
                lookup(
                    "dye_item",
                    "dye_item_id",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
                lookup(
                    "dye_item_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
            ],
            ghidra_class: "Javelin::DyeItemDataManager",
            rust_type: "crate::DyeItemDataManager",
            ghidra_functions: vec!["Javelin::DyeItemDataManager::DyeItemDataManager"],
            ..OwnedStringSpec::default()
        }),
        owned_string(OwnedStringSpec {
            module: "consumable_item_data",
            table_name: "ConsumableItemDefinitions",
            row_type_name: "ConsumableItemDefinitions",
            row_alias: "ConsumableItemDataRow",
            table_field: "table",
            indexes_field: "consumable_items",
            indexed_type: "IndexedConsumableItem",
            indexes_type: "ConsumableItemIndexes",
            indexed_key_field: "consumable_id",
            key_column: "ConsumableID",
            key_getter: "consumable_id",
            skip_empty_key: true,
            duplicate_manager_label: "ConsumableItemDataManager",
            duplicate_key_label: "ConsumableID",
            lookup_methods: vec![
                lookup(
                    "consumable_item",
                    "consumable_id",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
                lookup(
                    "consumable_item_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
            ],
            ghidra_class: "Javelin::ConsumableItemDataManager",
            rust_type: "crate::ConsumableItemDataManager",
            ghidra_functions: vec![
                "Javelin::ConsumableItemDataManager::ConsumableItemDataManager",
                "Javelin::ConsumableItemDataManager::CacheAllDataTables",
            ],
            ..OwnedStringSpec::default()
        }),
        owned_string(OwnedStringSpec {
            module: "weapon_effect_data",
            table_name: "WeaponEffects",
            row_type_name: "WeaponEffectData",
            row_alias: "WeaponEffectDataRow",
            table_field: "table",
            indexes_field: "weapon_effects",
            indexed_type: "IndexedWeaponEffect",
            indexes_type: "WeaponEffectIndexes",
            indexed_key_field: "weapon_effect_id",
            key_column: "WeaponEffectId",
            key_getter: "weapon_effect_id",
            skip_empty_key: true,
            duplicate_manager_label: "WeaponEffectDataManager",
            duplicate_key_label: "WeaponEffectId",
            lookup_methods: vec![
                lookup(
                    "weapon_effect",
                    "weapon_effect_id",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
                lookup(
                    "weapon_effect_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
            ],
            ghidra_class: "Javelin::WeaponEffectDataManager",
            rust_type: "crate::WeaponEffectDataManager",
            ghidra_functions: vec![
                "Javelin::WeaponEffectDataManager::WeaponEffectDataManager",
                "Javelin::WeaponEffectDataManager::CacheAllDataTables",
            ],
            ..OwnedStringSpec::default()
        }),
        particle_data_manager_spec(),
        particle_priority_override_data_manager_spec(),
        player_tutorials_condition_data_manager_spec(),
        player_tutorials_content_data_manager_spec(),
        player_tutorials_data_manager_spec(),
        progression_pool_data_manager_spec(),
        mission_data_manager_spec(),
        table_family_crc_projection(TableFamilyCrcProjectionSpec {
            module: "mission_weights_data",
            table_module: None,
            tables: vec![
                TableFamilyTableSpec {
                    variant: "FlexibleMissionWeights".to_owned(),
                    table_name: "FlexibleMissionWeights",
                    row_type_name: "MissionWeightsData",
                },
                TableFamilyTableSpec {
                    variant: "MissionWeights".to_owned(),
                    table_name: "MissionWeights",
                    row_type_name: "MissionWeightsData",
                },
            ],
            tables_type: "MissionWeightsDataTables",
            table_type: "MissionWeightsDataTable",
            handle_type: "MissionWeightsDataHandle",
            row_alias: "MissionWeightsDataRow",
            data_type: "StaticMissionWeightsData",
            entries_field: "rows",
            index_field: "rows_by_mission_weight_crc",
            key_field: "mission_weight_id",
            crc_field: "mission_weight_crc",
            key_column: "MissionWeightId",
            key_getter: "mission_weight_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_handle_field: None,
            source_handle_method: None,
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "slot_number",
                    "SlotNumber",
                    "slot_number",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "bucket_id",
                    "Bucket",
                    "bucket",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "bucket_crc",
                    "Bucket",
                    "bucket",
                    NativeProjectionTransform::LowercaseCrcString,
                ),
                typed_projection_field(
                    "mission_goal_type",
                    "MissionGoalType",
                    "mission_goal_type",
                    NativeProjectionTransform::EnumStringSkipInvalid,
                    "gamedata::semantic::MissionGoalType",
                ),
                projection_field(
                    "weight",
                    "Weight",
                    "weight",
                    NativeProjectionTransform::NonZeroU32,
                ),
            ],
            table_indexes: Vec::new(),
            field_lookup_methods: Vec::new(),
            store_key_text: true,
            lookup_methods: vec![
                lookup(
                    "mission_weight_data",
                    "mission_weight_id",
                    NativeCrcIndexLookupParameterKind::IntoCrc32,
                ),
                lookup(
                    "mission_weight_data_by_key",
                    "mission_weight_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: Some("mission_weight_ids"),
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::MissionWeightsDataManager",
            rust_type: "crate::MissionWeightsDataManager",
            ghidra_functions: vec![
                "Javelin::MissionWeightsDataManager::MissionWeightsDataManager",
                "Javelin::MissionWeightsDataManager::CacheAllDataTables",
            ],
        }),
    ]
}
