use super::super::*;

pub(super) fn specs() -> Vec<NativeManagerSpec> {
    vec![
        crc_projection(CrcProjectionSpec {
            module: "fishing_pole_data",
            table_name: "FishingPolesMastersheet",
            row_type_name: "FishingPolesData",
            data_type: "FishingPoleData",
            entries_field: "poles",
            index_field: "poles_by_crc",
            key_field: "id",
            crc_field: "id_crc32",
            key_column: "Id",
            key_getter: "id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "cast_distance_range",
                    "CastDistanceRange",
                    "cast_distance_range",
                    NativeProjectionTransform::F32RangeInclusive,
                ),
                projection_field(
                    "fish_rarity_roll_modifier",
                    "FishRarityRollModifier",
                    "fish_rarity_roll_modifier",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "fish_size_roll_modifier",
                    "FishSizeRollModifier",
                    "fish_size_roll_modifier",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "summer_fish_rarity_roll_modifier",
                    "SummerFishRarityRollModifier",
                    "summer_fish_rarity_roll_modifier",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "fish_reel_time_seconds",
                    "FishReelTimeSeconds",
                    "fish_reel_time_seconds",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "line_tension_gain_per_second",
                    "LineTensionGainPerSecond",
                    "line_tension_gain_per_second",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "line_tension_recover_per_second",
                    "LineTensionRecoverPerSecond",
                    "line_tension_recover_per_second",
                    NativeProjectionTransform::F32,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "fishing_pole",
                    "id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "fishing_pole_from_id",
                    "id",
                    NativeCrcIndexLookupParameterKind::IntoCrc32,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::FishingPoleDataManager",
            rust_type: "crate::FishingPoleDataManager",
            ghidra_functions: vec![
                "Javelin::FishingPoleDataManager::FishingPoleDataManager",
                "Javelin::FishingPoleDataManager::CacheAllDataTables",
            ],
        }),
        crc_projection(CrcProjectionSpec {
            module: "fishing_hotspot_data",
            table_name: "FishingHotspotsMastersheet",
            row_type_name: "FishingHotspotsData",
            data_type: "FishingHotspotData",
            entries_field: "hotspots",
            index_field: "hotspots_by_crc",
            key_field: "id",
            crc_field: "id_crc32",
            key_column: "Id",
            key_getter: "id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "display_name",
                    "DisplayName",
                    "display_name",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "fish_rarity_roll_modifier",
                    "FishRarityRollModifier",
                    "fish_rarity_roll_modifier",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "fish_size_roll_modifier",
                    "FishSizeRollModifier",
                    "fish_size_roll_modifier",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "summer_fish_rarity_roll_modifier",
                    "SummerFishRarityRollModifier",
                    "summer_fish_rarity_roll_modifier",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "loot_table_id",
                    "LootTableId",
                    "loot_table_id",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "loot_tag",
                    "LootTag",
                    "loot_tag",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "required_level",
                    "RequiredLevel",
                    "required_level",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "time_to_nibble_seconds_range",
                    "TimeToNibbleSecondsRange",
                    "time_to_nibble_seconds_range",
                    NativeProjectionTransform::F32RangeInclusive,
                ),
                projection_field(
                    "time_to_bite_seconds_range",
                    "TimeToBiteSecondsRange",
                    "time_to_bite_seconds_range",
                    NativeProjectionTransform::F32RangeInclusive,
                ),
                projection_field(
                    "notes",
                    "Notes",
                    "notes",
                    NativeProjectionTransform::OptionalString,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "fishing_hotspot",
                    "id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "fishing_hotspot_from_id",
                    "id",
                    NativeCrcIndexLookupParameterKind::IntoCrc32,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::FishingHotspotDataManager",
            rust_type: "crate::FishingHotspotDataManager",
            ghidra_functions: vec![
                "Javelin::FishingHotspotDataManager::FishingHotspotDataManager",
                "Javelin::FishingHotspotDataManager::CacheAllDataTables",
            ],
        }),
        crc_projection(CrcProjectionSpec {
            module: "fishing_catchable_data",
            table_name: "FishingCatchablesMastersheet",
            row_type_name: "FishingCatchablesData",
            data_type: "FishingCatchableData",
            entries_field: "catchables",
            index_field: "catchables_by_crc",
            key_field: "id",
            crc_field: "id_crc32",
            key_column: "Id",
            key_getter: "id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "fish_size",
                    "FishSize",
                    "fish_size",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "fish_weight_range",
                    "FishWeightRange",
                    "fish_weight_range",
                    NativeProjectionTransform::F32RangeInclusive,
                ),
                projection_field(
                    "fish_length_range",
                    "FishLengthRange",
                    "fish_length_range",
                    NativeProjectionTransform::F32RangeInclusive,
                ),
                projection_field(
                    "fishing_xp",
                    "FishingXP",
                    "fishing_xp",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "fish_distance_swam_away_per_second",
                    "FishDistanceSwamAwayPerSecond",
                    "fish_distance_swam_away_per_second",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "line_tension_gain_per_second_multiplier",
                    "LineTensionGainPerSecondMultiplier",
                    "line_tension_gain_per_second_multiplier",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "fish_behaviors",
                    "FishBehaviors",
                    "fish_behaviors",
                    NativeProjectionTransform::CrcList,
                ),
                projection_field(
                    "zoom_camera_on_success",
                    "ZoomCameraOnSuccess",
                    "zoom_camera_on_success",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "fish_character_definition_path",
                    "FishCharacterDefinitionPath",
                    "fish_character_definition_path",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "fish_scale",
                    "FishScale",
                    "fish_scale",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "reward_game_event_id",
                    "RewardGameEventId",
                    "reward_game_event_id",
                    NativeProjectionTransform::OptionalString,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "fishing_catchable",
                    "id",
                    NativeCrcIndexLookupParameterKind::IntoCrc32,
                ),
                lookup(
                    "fishing_catchable_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::FishingCatchableDataManager",
            rust_type: "crate::FishingCatchableDataManager",
            ghidra_functions: vec![
                "Javelin::FishingCatchableDataManager::FishingCatchableDataManager",
                "Javelin::FishingCatchableDataManager::CacheAllDataTables",
            ],
        }),
        enum_projection(EnumProjectionSpec {
            module: "musical_instrument_slot_data",
            table_name: "MusicalInstrumentSlotTable",
            row_type_name: "MusicalInstrumentSlot",
            data_type: "MusicalInstrumentSlotData",
            entries_field: "slots",
            index_field: "slots_by_type",
            key_field: "slot_type",
            key_column: "PaperdollId",
            key_getter: "paperdoll_id",
            key_type: "newworld_plugin::game_data::PaperdollSlotTypes",
            key_type_alias: Some("PaperdollSlotType"),
            table_view_alias: Some("MusicalInstrumentSlotTableView"),
            expose_table_constructor: true,
            invalid_key_variants: Vec::new(),
            skip_empty_key: true,
            trim_key: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            fields: vec![
                projection_field(
                    "paperdoll_id",
                    "PaperdollId",
                    "paperdoll_id",
                    NativeProjectionTransform::String,
                ),
                projection_field("name", "Name", "name", NativeProjectionTransform::String),
                projection_field(
                    "clef_icon_path",
                    "ClefIconPath",
                    "clef_icon_path",
                    NativeProjectionTransform::String,
                ),
            ],
            lookup_methods: vec![enum_lookup(
                "musical_instrument_slot",
                "slot",
                NativeEnumLookupParameterKind::Enum,
            )],
            secondary_crc_index: None,
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::MusicalInstrumentSlotDataManager",
            rust_type: "crate::MusicalInstrumentSlotDataManager",
            ghidra_functions: vec![
                "Javelin::MusicalInstrumentSlotDataManager::MusicalInstrumentSlotDataManager",
                "Javelin::MusicalInstrumentSlotDataManager::CacheAllDataTables",
            ],
        }),
        crc_projection(CrcProjectionSpec {
            module: "status_effect_category_data",
            table_name: "StatusEffectCategories",
            row_type_name: "StatusEffectCategoryData",
            data_type: "StatusEffectCategoryData",
            entries_field: "categories",
            index_field: "categories_by_crc",
            key_field: "status_effect_category_id",
            crc_field: "status_effect_category_id_crc",
            key_column: "StatusEffectCategoryID",
            key_getter: "status_effect_category_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: true,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "duration_diminishing_mod",
                    "DurationDiminishingMod",
                    "duration_diminishing_mod",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "duration_mod_min",
                    "DurationModMin",
                    "duration_mod_min",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "duration_mod_max",
                    "DurationModMax",
                    "duration_mod_max",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "potency_diminishing_mod",
                    "PotencyDiminishingMod",
                    "potency_diminishing_mod",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "potency_mod_min",
                    "PotencyModMin",
                    "potency_mod_min",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "potency_mod_max",
                    "PotencyModMax",
                    "potency_mod_max",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "value_limits",
                    "ValueLimits",
                    "value_limits",
                    NativeProjectionTransform::OptionalStringList,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "status_effect_category_data_from_id",
                    "category_id",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "status_effect_category_data",
                    "category_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "status_effect_category_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("categories"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::StatusEffectCategoryDataManager",
            rust_type: "crate::StatusEffectCategoryDataManager",
            ghidra_functions: vec![
                "Javelin::StatusEffectCategoryDataManager::StatusEffectCategoryDataManager",
                "Javelin::StatusEffectCategoryDataManager::CacheAllDataTables",
            ],
        }),
        crc_projection(CrcProjectionSpec {
            module: "currency_exchange_data",
            table_name: "CurrencyExchange",
            row_type_name: "CurrencyExchangeData",
            data_type: "CurrencyExchangeData",
            entries_field: "exchanges",
            index_field: "rows_by_crc",
            key_field: "conversion_id",
            crc_field: "conversion_crc",
            key_column: "ConversionID",
            key_getter: "conversion_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: None,
            source_row_method: None,
            row_filters: vec![string_not_equal_to_column_filter(
                "FromCurrencyId",
                "from_currency_id",
                "to_currency_id",
            )],
            fields: vec![
                projection_field(
                    "from_currency_id",
                    "FromCurrencyId",
                    "from_currency_id",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "from_currency_crc",
                    "FromCurrencyId",
                    "from_currency_id",
                    NativeProjectionTransform::LowercaseCrcString,
                ),
                projection_field(
                    "from_currency_is_categorical_progression",
                    "FromCurrencyIsCategoricalProgression",
                    "from_currency_is_categorical_progression",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "from_currency_quantity",
                    "FromCurrencyQuantity",
                    "from_currency_quantity",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "to_currency_id",
                    "ToCurrencyId",
                    "to_currency_id",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "to_currency_crc",
                    "ToCurrencyId",
                    "to_currency_id",
                    NativeProjectionTransform::LowercaseCrcString,
                ),
                projection_field(
                    "to_currency_is_categorical_progression",
                    "ToCurrencyIsCategoricalProgression",
                    "to_currency_is_categorical_progression",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "to_currency_quantity",
                    "ToCurrencyQuantity",
                    "to_currency_quantity",
                    NativeProjectionTransform::NonZeroU32,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "currency_exchange_data_from_id",
                    "conversion_id",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "currency_exchange_data",
                    "conversion_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "currency_exchange_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::CurrencyExchangeDataManager",
            rust_type: "crate::CurrencyExchangeDataManager",
            ghidra_functions: vec![
                "Javelin::CurrencyExchangeDataManager::CurrencyExchangeDataManager",
                "Javelin::CurrencyExchangeDataManager::CacheAllDataTables",
            ],
        }),
        crc_projection(CrcProjectionSpec {
            module: "leaderboard_data",
            table_name: "LeaderboardDataTable",
            row_type_name: "LeaderboardData",
            data_type: "StaticLeaderboardData",
            entries_field: "leaderboards",
            index_field: "leaderboards_by_id",
            key_field: "leaderboard_id",
            crc_field: "leaderboard_id_crc",
            key_column: "LeaderboardId",
            key_getter: "leaderboard_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            row_filters: vec![bool_must_be_true_filter("IsEnabled", "is_enabled")],
            fields: vec![
                projection_field(
                    "leaderboard_definition_id",
                    "LeaderboardDefinitionId",
                    "leaderboard_definition_id",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "faction_leaderboard_definition_id",
                    "FactionLeaderboardDefinitionId",
                    "faction_leaderboard_definition_id",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "category",
                    "Category",
                    "category",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "display_name",
                    "DisplayName",
                    "display_name",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "game_mode_crc",
                    "GameMode",
                    "game_mode",
                    NativeProjectionTransform::OptionalLowercaseCrcString,
                ),
                projection_field(
                    "character_leaderboard",
                    "CharacterLeaderboard",
                    "character_leaderboard",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "group_leaderboard",
                    "GroupLeaderboard",
                    "group_leaderboard",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "company_leaderboard",
                    "CompanyLeaderboard",
                    "company_leaderboard",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "faction_leaderboard",
                    "FactionLeaderboard",
                    "faction_leaderboard",
                    NativeProjectionTransform::Bool,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "leaderboard_data_from_id",
                    "leaderboard_id",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "leaderboard_data",
                    "leaderboard_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "leaderboard_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: Some("leaderboard_ids"),
            rows_method: Some("leaderboards"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::LeaderboardDataManager",
            rust_type: "crate::LeaderboardDataManager",
            ghidra_functions: vec![
                "Javelin::LeaderboardDataManager::LeaderboardDataManager",
                "Javelin::LeaderboardDataManager::CacheAllDataTables",
            ],
        }),
        crc_projection(CrcProjectionSpec {
            module: "leaderboard_stat_data",
            table_name: "LeaderboardStatDataTable",
            row_type_name: "LeaderboardStatData",
            data_type: "StaticLeaderboardStatData",
            entries_field: "stats",
            index_field: "stats_by_id",
            key_field: "leaderboard_stat_id",
            crc_field: "leaderboard_stat_id_crc",
            key_column: "LeaderboardStatId",
            key_getter: "leaderboard_stat_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "service_stat_id",
                    "ServiceStatId",
                    "service_stat_id",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "categorical_progression_crc",
                    "CategoricalProgressionId",
                    "categorical_progression_id",
                    NativeProjectionTransform::OptionalLowercaseCrcString,
                ),
                projection_field(
                    "game_mode_crc",
                    "GameMode",
                    "game_mode",
                    NativeProjectionTransform::OptionalLowercaseCrcString,
                ),
                projection_field(
                    "personal_best",
                    "PersonalBest",
                    "personal_best",
                    NativeProjectionTransform::OptionalString,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "leaderboard_stat_data_from_id",
                    "leaderboard_stat_id",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "leaderboard_stat_data",
                    "leaderboard_stat_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "leaderboard_stat_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: Some("leaderboard_stat_ids"),
            rows_method: Some("stats"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::LeaderboardStatDataManager",
            rust_type: "crate::LeaderboardStatDataManager",
            ghidra_functions: vec![
                "Javelin::LeaderboardStatDataManager::LeaderboardStatDataManager",
                "Javelin::LeaderboardStatDataManager::CacheAllDataTables",
            ],
        }),
        table_family_crc_projection(TableFamilyCrcProjectionSpec {
            module: "conversation_state_data",
            table_module: None,
            tables: inputs::manager_table_family_specs("crate::ConversationStateDataManager"),
            tables_type: "ConversationStateDataTables",
            table_type: "ConversationStateDataTable",
            handle_type: "ConversationStateDataHandle",
            row_alias: "ConversationStateDataRow",
            data_type: "StaticConversationStateData",
            entries_field: "states",
            index_field: "states_by_id",
            key_field: "conversation_state_id",
            crc_field: "conversation_state_id_crc",
            key_column: "ConversationStateId",
            key_getter: "conversation_state_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            source_row_by_crc_method: None,
            source_handle_field: None,
            source_handle_method: None,
            row_filters: Vec::new(),
            fields: Vec::new(),
            table_indexes: Vec::new(),
            field_lookup_methods: Vec::new(),
            store_key_text: true,
            lookup_methods: vec![
                lookup(
                    "conversation_state_data_from_id",
                    "conversation_state_id",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "conversation_state_data",
                    "conversation_state_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "conversation_state_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: Some("conversation_state_ids"),
            rows_method: Some("states"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::ConversationStateDataManager",
            rust_type: "crate::ConversationStateDataManager",
            ghidra_functions: vec![
                "Javelin::ConversationStateDataManager::ConversationStateDataManager",
                "Javelin::ConversationStateDataManager::CacheAllDataTables",
            ],
        }),
        table_family_crc_projection(TableFamilyCrcProjectionSpec {
            module: "conversation_topic_data",
            table_module: None,
            tables: inputs::manager_table_family_specs("crate::ConversationTopicDataManager"),
            tables_type: "ConversationTopicDataTables",
            table_type: "ConversationTopicDataTable",
            handle_type: "ConversationTopicDataHandle",
            row_alias: "ConversationTopicDataRow",
            data_type: "StaticConversationTopicData",
            entries_field: "topics",
            index_field: "topics_by_id",
            key_field: "conversation_topic_id",
            crc_field: "conversation_topic_id_crc",
            key_column: "ConversationTopicId",
            key_getter: "conversation_topic_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            source_row_by_crc_method: None,
            source_handle_field: None,
            source_handle_method: None,
            row_filters: Vec::new(),
            fields: Vec::new(),
            table_indexes: Vec::new(),
            field_lookup_methods: Vec::new(),
            store_key_text: true,
            lookup_methods: vec![
                lookup(
                    "conversation_topic_data_from_id",
                    "conversation_topic_id",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "conversation_topic_data",
                    "conversation_topic_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "conversation_topic_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: Some("conversation_topic_ids"),
            rows_method: Some("topics"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::ConversationTopicDataManager",
            rust_type: "crate::ConversationTopicDataManager",
            ghidra_functions: vec![
                "Javelin::ConversationTopicDataManager::ConversationTopicDataManager",
                "Javelin::ConversationTopicDataManager::CacheAllDataTables",
            ],
        }),
        vitals_base_data_manager_spec(),
        variation_data_manager_spec(),
        vitals_data_manager_spec(),
        numeric_projection(NumericProjectionSpec {
            module: "vitals_level_data",
            table_name: "VitalsLevels",
            row_type_name: "VitalsLevelData",
            data_type: "VitalsLevelData",
            entries_field: "levels",
            index_field: "rows_by_level",
            key_field: "level",
            key_column: "Level",
            key_getter: "level",
            key_type: NativeNumericKeyType::NonZeroU32,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            fields: vec![
                projection_field(
                    "gear_score",
                    "GearScore",
                    "gear_score",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "base_damage",
                    "BaseDamage",
                    "base_damage",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "base_max_health",
                    "BaseMaxHealth",
                    "base_max_health",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "initial_health",
                    "InitialHealth",
                    "initial_health",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "physical_armor_rating",
                    "PhysicalArmorRating",
                    "physical_armor_rating",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "elemental_armor_rating",
                    "ElementalArmorRating",
                    "elemental_armor_rating",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "loot_gs_bonus",
                    "LootGSBonus",
                    "loot_gs_bonus",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "loot_gs_bonus_chance",
                    "LootGSBonusChance",
                    "loot_gs_bonus_chance",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "container_loot_gs_floor",
                    "ContainerLootGSFloor",
                    "container_loot_gs_floor",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "ai_loot_gs_ceiling",
                    "AILootGSCeiling",
                    "ai_loot_gs_ceiling",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "solo_damage",
                    "Solo Damage",
                    "solo_damage",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "solo_health",
                    "Solo Health",
                    "solo_health",
                    NativeProjectionTransform::OptionalString,
                ),
            ],
            lookup_methods: vec![numeric_lookup(
                "vitals_level_data",
                "level",
                NativeNumericLookupParameterKind::NonZeroU32,
            )],
            rows_method: Some("levels"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::VitalsLevelDataManager",
            rust_type: "crate::VitalsLevelDataManager",
            ghidra_functions: vec![
                "Javelin::VitalsLevelDataManager::VitalsLevelDataManager",
                "Javelin::VitalsLevelDataManager::CacheAllDataTables",
            ],
        }),
    ]
}
