use super::super::*;

pub(super) fn specs() -> Vec<NativeManagerSpec> {
    vec![
        crc_projection(CrcProjectionSpec {
            module: "loot_limit_data",
            table_name: "LootLimits",
            row_type_name: "LootLimitData",
            data_type: "LootLimitData",
            entries_field: "loot_limits",
            index_field: "rows_by_crc",
            key_field: "loot_limit_id",
            crc_field: "loot_limit_crc",
            key_column: "LootLimitID",
            key_getter: "loot_limit_id",
            skip_empty_key: true,
            trim_key: true,
            reject_zero_crc: true,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: None,
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "is_replicated",
                    "IsReplicated",
                    "is_replicated",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "min_limit_seconds",
                    "MinLimitSeconds",
                    "min_limit_seconds",
                    NativeProjectionTransform::U32,
                ),
                projection_field(
                    "max_limit_seconds",
                    "MaxLimitSeconds",
                    "max_limit_seconds",
                    NativeProjectionTransform::U32,
                ),
                projection_field(
                    "count_limit",
                    "CountLimit",
                    "count_limit",
                    NativeProjectionTransform::U32,
                ),
                projection_field(
                    "min_limit_mult",
                    "MinLimitMult",
                    "min_limit_mult",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "max_limit_mult",
                    "MaxLimitMult",
                    "max_limit_mult",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "limit_expire_seconds",
                    "LimitExpireSeconds",
                    "limit_expire_seconds",
                    NativeProjectionTransform::U32,
                ),
                projection_field(
                    "loot_tag_value_per_count",
                    "LootTagValuePerCount",
                    "loot_tag_value_per_count",
                    NativeProjectionTransform::U32,
                ),
                projection_field(
                    "loot_tag_value_override_at_limit",
                    "LootTagValueOverrideAtLimit",
                    "loot_tag_value_override_at_limit",
                    NativeProjectionTransform::U32,
                ),
                projection_field(
                    "limit_notification_loc_tag",
                    "LimitNotificationLocTag",
                    "limit_notification_loc_tag",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "achievement_at_limit_row",
                    "AchievementAtLimit",
                    "achievement_at_limit",
                    NativeProjectionTransform::OptionalForeignKeyRow,
                ),
                projection_field(
                    "is_achievement_bound",
                    "IsAchievementBound",
                    "is_achievement_bound",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "pity_ticker_odds_mod",
                    "PityTickerOddsMod",
                    "pity_ticker_odds_mod",
                    NativeProjectionTransform::F32,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "loot_limit_data_from_id",
                    "loot_limit_id",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "loot_limit_data",
                    "loot_limit_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "loot_limit_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: Some("loot_limit_ids"),
            rows_method: Some("loot_limits"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::LootLimitDataManager",
            rust_type: "crate::LootLimitDataManager",
            ghidra_functions: vec![
                "Javelin::LootLimitDataManager::LootLimitDataManager",
                "Javelin::LootLimitDataManager::CacheAllDataTables",
            ],
        }),
        crc_projection(CrcProjectionSpec {
            module: "weapon_tier_data",
            table_name: "WeaponTiersTable",
            row_type_name: "WeaponTiersData",
            data_type: "WeaponTierData",
            entries_field: "rows",
            index_field: "rows_by_tier_id",
            key_field: "tier_key",
            crc_field: "tier_id",
            key_column: "Tier",
            key_getter: "tier",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: true,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("weapon_tier_data_for_source_row"),
            row_filters: vec![f32_greater_than_or_equal_zero_filter(
                "ScalingStart",
                "scaling_start",
            )],
            fields: vec![
                projection_field(
                    "scaling_start",
                    "ScalingStart",
                    "scaling_start",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "display_name",
                    "DisplayName",
                    "display_name",
                    NativeProjectionTransform::NonEmptyString,
                ),
                projection_field(
                    "display_name_crc",
                    "DisplayName",
                    "display_name",
                    NativeProjectionTransform::LowercaseCrcString,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "weapon_tier_data_from_id",
                    "tier_id",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "weapon_tier_data",
                    "tier_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "weapon_tier_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::WeaponTierDataManager",
            rust_type: "crate::WeaponTierDataManager",
            ghidra_functions: vec![
                "Javelin::WeaponTierDataManager::WeaponTierDataManager",
                "Javelin::WeaponTierDataManager::CacheAllDataTables",
            ],
        }),
        crc_projection(CrcProjectionSpec {
            module: "weapon_accessory_data",
            table_name: "WeaponAccessoryDefinitions",
            row_type_name: "WeaponAccessoryDefinitions",
            data_type: "WeaponAccessoryData",
            entries_field: "rows",
            index_field: "rows_by_weapon_id",
            key_field: "weapon_key",
            crc_field: "weapon_id",
            key_column: "WeaponID",
            key_getter: "weapon_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: true,
            duplicate_key_policy: NativeDuplicateKeyPolicy::Error,
            source_row_field: Some("source_row"),
            source_row_method: Some("weapon_accessory_for_source_row"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field("id", "ID", "id", NativeProjectionTransform::NonZeroU32),
                projection_field(
                    "prefab_path",
                    "PrefabPath",
                    "prefab_path",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "mesh_override",
                    "MeshOverride",
                    "mesh_override",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "skin_override1",
                    "SkinOverride1",
                    "skin_override1",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "material_override1",
                    "MaterialOverride1",
                    "material_override1",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "skin_override2",
                    "SkinOverride2",
                    "skin_override2",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "material_override2",
                    "MaterialOverride2",
                    "material_override2",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "skin_override3",
                    "SkinOverride3",
                    "skin_override3",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "material_override3",
                    "MaterialOverride3",
                    "material_override3",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "skin_override4",
                    "SkinOverride4",
                    "skin_override4",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "material_override4",
                    "MaterialOverride4",
                    "material_override4",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "equip_type",
                    "EquipType",
                    "equip_type",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "sheath_mode",
                    "SheathMode",
                    "sheath_mode",
                    NativeProjectionTransform::String,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "weapon_accessory_from_id",
                    "weapon_id",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "weapon_accessory",
                    "weapon_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "weapon_accessory_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::WeaponAccessoryDataManager",
            rust_type: "crate::WeaponAccessoryDataManager",
            ghidra_functions: vec![
                "Javelin::WeaponAccessoryDataManager::WeaponAccessoryDataManager",
                "Javelin::WeaponAccessoryDataManager::FUN_7ff6050d0360",
            ],
        }),
        crc_projection(CrcProjectionSpec {
            module: "throwable_item_data",
            table_name: "ThrowableItemDefinitions",
            row_type_name: "ThrowableItemDefinitions",
            data_type: "ThrowableItemData",
            entries_field: "throwable_items",
            index_field: "rows_by_crc",
            key_field: "throwable_id",
            crc_field: "throwable_id_crc",
            key_column: "ThrowableId",
            key_getter: "throwable_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::Error,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "activation_time",
                    "ActivationTime",
                    "activation_time",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "spawn_slice_on_activate",
                    "SpawnSliceOnActivate",
                    "spawn_slice_on_activate",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "activation_slice_path",
                    "ActivationSlicePath",
                    "activation_slice_path",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "gatherable_slice_path",
                    "GatherableSlicePath",
                    "gatherable_slice_path",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "spell_name",
                    "SpellName",
                    "spell_name",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "attachment_name",
                    "AttachmentName",
                    "attachment_name",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "warning_time",
                    "WarningTime",
                    "warning_time",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "attachment_slice_path",
                    "AttachmentSlicePath",
                    "attachment_slice_path",
                    NativeProjectionTransform::String,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "throwable_item_from_id",
                    "throwable_id",
                    NativeCrcIndexLookupParameterKind::IntoCrc32,
                ),
                lookup(
                    "throwable_item",
                    "throwable_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "throwable_item_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::ThrowableItemDataManager",
            rust_type: "crate::ThrowableItemDataManager",
            ghidra_functions: vec![
                "Javelin::ThrowableItemDataManager::ThrowableItemDataManager",
                "Javelin::ThrowableItemDataManager::FUN_7ff6050cf280",
            ],
        }),
        crc_projection(CrcProjectionSpec {
            module: "interaction_animation_data",
            table_name: "InteractionAnimations",
            row_type_name: "InteractionAnimationData",
            data_type: "InteractionAnimationData",
            entries_field: "animations",
            index_field: "rows_by_crc",
            key_field: "interaction_animation_id",
            crc_field: "interaction_animation_id_crc",
            key_column: "InteractionAnimationID",
            key_getter: "interaction_animation_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: true,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "player_mannequin_fragment_start_interaction",
                    "PlayerMannequinFragmentStartInteraction",
                    "player_mannequin_fragment_start_interaction",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "interactable_timeline_start_interaction",
                    "InteractableTimelineStartInteraction",
                    "interactable_timeline_start_interaction",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "interactable_timeline_end_interaction",
                    "InteractableTimelineEndInteraction",
                    "interactable_timeline_end_interaction",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "notes",
                    "Notes",
                    "notes",
                    NativeProjectionTransform::StringList,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "interaction_animation_from_id",
                    "id",
                    NativeCrcIndexLookupParameterKind::IntoCrc32,
                ),
                lookup(
                    "interaction_animation",
                    "id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("animations"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::InteractionAnimationDataManager",
            rust_type: "crate::InteractionAnimationDataManager",
            ghidra_functions: vec![
                "Javelin::InteractionAnimationDataManager::InteractionAnimationDataManager",
                "Javelin::InteractionAnimationDataManager::CacheAllDataTables",
            ],
        }),
        crc_projection(CrcProjectionSpec {
            module: "curse_mutation_static_data",
            table_name: "CurseMutation",
            row_type_name: "CurseMutationStaticData",
            data_type: "CurseMutationStaticData",
            entries_field: "curse_mutations",
            index_field: "curse_mutations_by_id",
            key_field: "curse_mutation_key",
            crc_field: "curse_mutation_id",
            key_column: "CurseMutationId",
            key_getter: "curse_mutation_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: true,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("curse_mutation_data_for_source_row"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "curse_minor",
                    "CurseMinor",
                    "curse_minor",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "curse_major",
                    "CurseMajor",
                    "curse_major",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "global_affliction_row",
                    "GlobalAffliction",
                    "global_affliction",
                    NativeProjectionTransform::OptionalForeignKeyRow,
                ),
                projection_field("name", "Name", "name", NativeProjectionTransform::String),
                projection_field(
                    "description",
                    "Description",
                    "description",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "icon_path",
                    "IconPath",
                    "icon_path",
                    NativeProjectionTransform::String,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "curse_mutation_data_from_id",
                    "curse_mutation_id",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "curse_mutation_data",
                    "curse_mutation_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "curse_mutation_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::CurseMutationStaticDataManager",
            rust_type: "crate::CurseMutationStaticDataManager",
            ghidra_functions: vec![
                "Javelin::CurseMutationStaticDataManager::CurseMutationStaticDataManager",
                "Javelin::CurseMutationStaticDataManager::CacheAllDataTables",
                "Javelin::CurseMutationStaticDataManager::FindGameSystemDataByKey",
            ],
        }),
        pvp_balance(PvpBalanceSpec {
            module: "duel_pvp_balance_data",
            table_name: "DuelPvpBalanceTable",
            row_type_name: "DuelBalanceData",
            lookup_methods: vec![
                lookup(
                    "duel_pvp_balance_data_from_id",
                    "balance_target",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "duel_pvp_balance_data",
                    "balance_target",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "duel_pvp_balance_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ghidra_class: "Javelin::DuelPvpBalanceDataManager",
            rust_type: "crate::DuelPvpBalanceDataManager",
            ghidra_functions: vec![
                "Javelin::DuelPvpBalanceDataManager::DuelPvpBalanceDataManager",
                "Javelin::DuelPvpBalanceDataManager::CacheAllDataTables",
            ],
        }),
        pvp_balance(PvpBalanceSpec {
            module: "ffa_zone_pvp_balance_data",
            table_name: "FFAZonePvpBalanceTable",
            row_type_name: "FFAZoneBalanceData",
            lookup_methods: vec![
                lookup(
                    "ffa_zone_pvp_balance_data_from_id",
                    "balance_target",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "ffa_zone_pvp_balance_data",
                    "balance_target",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "ffa_zone_pvp_balance_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ghidra_class: "Javelin::FFAZonePvpBalanceDataManager",
            rust_type: "crate::FFAZonePvpBalanceDataManager",
            ghidra_functions: vec![
                "Javelin::FFAZonePvpBalanceDataManager::FFAZonePvpBalanceDataManager",
                "Javelin::FFAZonePvpBalanceDataManager::CacheAllDataTables",
            ],
        }),
        pvp_balance(PvpBalanceSpec {
            module: "open_world_pvp_balance_data",
            table_name: "OpenWorldPvpBalanceTable",
            row_type_name: "OpenWorldBalanceData",
            lookup_methods: vec![
                lookup(
                    "open_world_pvp_balance_data_from_id",
                    "balance_target",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "open_world_pvp_balance_data",
                    "balance_target",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "open_world_pvp_balance_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ghidra_class: "Javelin::OpenWorldPvpBalanceDataManager",
            rust_type: "crate::OpenWorldPvpBalanceDataManager",
            ghidra_functions: vec![
                "Javelin::OpenWorldPvpBalanceDataManager::OpenWorldPvpBalanceDataManager",
                "Javelin::OpenWorldPvpBalanceDataManager::CacheAllDataTables",
            ],
        }),
        pvp_balance(PvpBalanceSpec {
            module: "opr_pvp_balance_data",
            table_name: "OutpostRushPvpBalanceTable",
            row_type_name: "OutpostRushBalanceData",
            lookup_methods: vec![
                lookup(
                    "opr_pvp_balance_data_from_id",
                    "balance_target",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "opr_pvp_balance_data",
                    "balance_target",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "opr_pvp_balance_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ghidra_class: "Javelin::OprPvpBalanceDataManager",
            rust_type: "crate::OprPvpBalanceDataManager",
            ghidra_functions: vec![
                "Javelin::OprPvpBalanceDataManager::OprPvpBalanceDataManager",
                "Javelin::OprPvpBalanceDataManager::CacheAllDataTables",
            ],
        }),
        pvp_balance(PvpBalanceSpec {
            module: "outpost_rush_no_perks_pvp_balance_data",
            table_name: "OutpostRush_NoPerksPvpBalanceTable",
            row_type_name: "OutpostRush_NoPerksBalanceData",
            lookup_methods: vec![
                lookup(
                    "outpost_rush_no_perks_pvp_balance_data_from_id",
                    "balance_target",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "outpost_rush_no_perks_pvp_balance_data",
                    "balance_target",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "outpost_rush_no_perks_pvp_balance_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ghidra_class: "Javelin::OutPostRush_NoPerksPvpBalanceDataManager",
            rust_type: "crate::OutPostRushNoPerksPvpBalanceDataManager",
            ghidra_functions: vec![
                "Javelin::OutPostRush_NoPerksPvpBalanceDataManager::OutPostRush_NoPerksPvpBalanceDataManager",
                "Javelin::OutPostRush_NoPerksPvpBalanceDataManager::CacheAllDataTables",
            ],
        }),
        pvp_balance(PvpBalanceSpec {
            module: "war_pvp_balance_data",
            table_name: "WarPvpBalanceTable",
            row_type_name: "WarBalanceData",
            lookup_methods: vec![
                lookup(
                    "war_pvp_balance_data_from_id",
                    "balance_target",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "war_pvp_balance_data",
                    "balance_target",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "war_pvp_balance_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ghidra_class: "Javelin::WarPvpBalanceDataManager",
            rust_type: "crate::WarPvpBalanceDataManager",
            ghidra_functions: vec![
                "Javelin::WarPvpBalanceDataManager::WarPvpBalanceDataManager",
                "Javelin::WarPvpBalanceDataManager::CacheAllDataTables",
            ],
        }),
    ]
}
