use super::super::*;

pub(super) fn specs() -> Vec<NativeManagerSpec> {
    vec![
        damage_data_manager_spec(),
        crc_projection(CrcProjectionSpec {
            module: "pug_activity_info_data",
            table_name: "PUGActivityInfo",
            row_type_name: "PUGActivityInfo",
            data_type: "PugActivityInfoData",
            entries_field: "rows",
            index_field: "rows_by_game_mode_id",
            key_field: "game_mode_key",
            crc_field: "game_mode_id",
            key_column: "GameModeId",
            key_getter: "game_mode_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("pug_activity_info_for_source_row"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field("name", "Name", "name", NativeProjectionTransform::String),
                projection_field(
                    "description",
                    "Description",
                    "description",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "icon_path",
                    "IconPath",
                    "icon_path",
                    NativeProjectionTransform::String,
                ),
                projection_field("is_pvp", "IsPvp", "is_pvp", NativeProjectionTransform::Bool),
                projection_field(
                    "min_group_size",
                    "MinGroupSize",
                    "min_group_size",
                    NativeProjectionTransform::U32,
                ),
                projection_field(
                    "max_group_size",
                    "MaxGroupSize",
                    "max_group_size",
                    NativeProjectionTransform::U32,
                ),
                projection_field(
                    "require_azoth_staff",
                    "RequireAzothStaff",
                    "require_azoth_staff",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "require_local_group",
                    "RequireLocalGroup",
                    "require_local_group",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "require_raid_group",
                    "RequireRaidGroup",
                    "require_raid_group",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "icon_path_small",
                    "IconPathSmall",
                    "icon_path_small",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "panel_icon_path",
                    "PanelIconPath",
                    "panel_icon_path",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "panel_name",
                    "PanelName",
                    "panel_name",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "panel_sub_text",
                    "PanelSubText",
                    "panel_sub_text",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "panel_description",
                    "PanelDescription",
                    "panel_description",
                    NativeProjectionTransform::OptionalString,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "pug_activity_info",
                    "game_mode_id",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "pug_activity_info_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::PugActivityInfoDataManager",
            rust_type: "crate::PugActivityInfoDataManager",
            ghidra_functions: vec![
                "Javelin::PugActivityInfoDataManager::PugActivityInfoDataManager",
                "Javelin::PugActivityInfoDataManager::CacheAllDataTables",
            ],
        }),
        crc_projection(CrcProjectionSpec {
            module: "pug_rewards_data",
            table_name: "PUGRewards",
            row_type_name: "PUGRewardData",
            data_type: "PugRewardData",
            entries_field: "rows",
            index_field: "rows_by_incentive_id",
            key_field: "incentive_key",
            crc_field: "incentive_id",
            key_column: "IncentiveID",
            key_getter: "incentive_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("pug_reward_data_for_source_row"),
            row_filters: vec![bool_true_when_present_filter("IsDisabled", "is_disabled")],
            fields: vec![
                projection_field(
                    "activity_types",
                    "ActivityTypes",
                    "activity_types",
                    NativeProjectionTransform::CrcList,
                ),
                projection_field(
                    "incentive_type",
                    "IncentiveType",
                    "incentive_type",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "role",
                    "Role",
                    "role",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "reward_below_max_lvl_game_event",
                    "RewardBelowMaxLvl_GameEvent",
                    "reward_below_max_lvl_game_event",
                    NativeProjectionTransform::LowercaseCrcString,
                ),
                projection_field(
                    "reward_below_max_lvl_game_event_key",
                    "RewardBelowMaxLvl_GameEvent",
                    "reward_below_max_lvl_game_event",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "reward_at_max_lvl_game_event",
                    "RewardAtMaxLvl_GameEvent",
                    "reward_at_max_lvl_game_event",
                    NativeProjectionTransform::LowercaseCrcString,
                ),
                projection_field(
                    "reward_at_max_lvl_game_event_key",
                    "RewardAtMaxLvl_GameEvent",
                    "reward_at_max_lvl_game_event",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "daily_limit",
                    "DailyLimit",
                    "daily_limit",
                    NativeProjectionTransform::U32,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "pug_reward_data",
                    "incentive_id",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "pug_reward_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::PugRewardsDataManager",
            rust_type: "crate::PugRewardsDataManager",
            ghidra_functions: vec![
                "Javelin::PugRewardsDataManager::PugRewardsDataManager",
                "Javelin::PugRewardsDataManager::CacheAllDataTables",
            ],
        }),
        numeric_projection(NumericProjectionSpec {
            module: "reward_data",
            table_name: "Rewards",
            row_type_name: "RewardData",
            data_type: "RewardData",
            entries_field: "rows",
            index_field: "rows_by_level",
            key_field: "level",
            key_column: "Level",
            key_getter: "level",
            key_type: NativeNumericKeyType::NonZeroU32,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("reward_data_for_source_row"),
            fields: vec![
                projection_field(
                    "kill_experience",
                    "KillExperience",
                    "kill_experience",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "kill_currency",
                    "KillCurrency",
                    "kill_currency",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "kill_azoth",
                    "KillAzoth",
                    "kill_azoth",
                    NativeProjectionTransform::U32,
                ),
                projection_field(
                    "quest_experience",
                    "QuestExperience",
                    "quest_experience",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "quest_currency",
                    "QuestCurrency",
                    "quest_currency",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "quest_azoth",
                    "QuestAzoth",
                    "quest_azoth",
                    NativeProjectionTransform::U32,
                ),
                projection_field(
                    "darkness_major",
                    "DarknessMajor",
                    "darkness_major",
                    NativeProjectionTransform::U32,
                ),
                projection_field(
                    "darkness_minor",
                    "Darkness Minor",
                    "darkness_minor",
                    NativeProjectionTransform::U32,
                ),
                projection_field(
                    "war_experience",
                    "WarExperience",
                    "war_experience",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "war_currency",
                    "WarCurrency",
                    "war_currency",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "war_azoth",
                    "WarAzoth",
                    "war_azoth",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "war_faction_tokens",
                    "WarFactionTokens",
                    "war_faction_tokens",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "war_azoth_salt",
                    "WarAzothSalt",
                    "war_azoth_salt",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "war_pvp_xp",
                    "WarPvpXp",
                    "war_pvp_xp",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "war_faction_reputation",
                    "WarFactionReputation",
                    "war_faction_reputation",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "war_territory_standing",
                    "WarTerritoryStanding",
                    "war_territory_standing",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "kill_progression_currency",
                    "KillProgressionCurrency",
                    "kill_progression_currency",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "kill_experience_dungeon_boss",
                    "KillExperienceDungeonBoss",
                    "kill_experience_dungeon_boss",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "kill_currency_dungeon_boss",
                    "KillCurrencyDungeonBoss",
                    "kill_currency_dungeon_boss",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "kill_experience_dungeon_mini_boss",
                    "KillExperienceDungeonMiniBoss",
                    "kill_experience_dungeon_mini_boss",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "kill_currency_dungeon_mini_boss",
                    "KillCurrencyDungeonMiniBoss",
                    "kill_currency_dungeon_mini_boss",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "seasons_xp",
                    "SeasonsXp",
                    "seasons_xp",
                    NativeProjectionTransform::NonZeroU32,
                ),
            ],
            lookup_methods: vec![numeric_lookup(
                "reward_data",
                "level",
                NativeNumericLookupParameterKind::NonZeroU32,
            )],
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::RewardDataManager",
            rust_type: "crate::RewardDataManager",
            ghidra_functions: vec![
                "Javelin::RewardDataManager::RewardDataManager",
                "Javelin::RewardDataManager::CacheAllDataTables",
            ],
        }),
        crc_projection(CrcProjectionSpec {
            module: "reward_modifier_data",
            table_name: "RewardModifiers",
            row_type_name: "RewardModifierData",
            data_type: "RewardModifierData",
            entries_field: "rows",
            index_field: "rows_by_modifier_id",
            key_field: "modifier_key",
            crc_field: "modifier_id",
            key_column: "Modifiers",
            key_getter: "modifiers",
            skip_empty_key: false,
            trim_key: false,
            reject_zero_crc: true,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("reward_modifier_data_for_source_row"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "experience",
                    "Experience",
                    "experience",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "currency",
                    "Currency",
                    "currency",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "currency_reward_chance",
                    "CurrencyRewardChance",
                    "currency_reward_chance",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "territory_standing",
                    "TerritoryStanding",
                    "territory_standing",
                    NativeProjectionTransform::F32,
                ),
                projection_field("azoth", "Azoth", "azoth", NativeProjectionTransform::F32),
                projection_field(
                    "loot_drop_modifier",
                    "LootDropModifier",
                    "loot_drop_modifier",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "faction_reputation_modifier",
                    "FactionReputationModifier",
                    "faction_reputation_modifier",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "faction_token_modifier",
                    "FactionTokenModifier",
                    "faction_token_modifier",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "progression_currency_amount",
                    "ProgressionCurrencyAmount",
                    "progression_currency_amount",
                    NativeProjectionTransform::OptionalF32,
                ),
                projection_field(
                    "azoth_salt_modifier",
                    "AzothSaltModifier",
                    "azoth_salt_modifier",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "pvp_xp_modifier",
                    "PvpXpModifier",
                    "pvp_xp_modifier",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "seasons_xp_modifier",
                    "SeasonsXpModifier",
                    "seasons_xp_modifier",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "found_in",
                    "Found in",
                    "found_in",
                    NativeProjectionTransform::StringList,
                ),
                projection_field(
                    "display_name",
                    "DisplayName",
                    "display_name",
                    NativeProjectionTransform::OptionalString,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "reward_modifier_data",
                    "modifier_id",
                    NativeCrcIndexLookupParameterKind::IntoCrc32,
                ),
                lookup(
                    "reward_modifier_data_by_key",
                    "modifier_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::RewardModifierDataManager",
            rust_type: "crate::RewardModifierDataManager",
            ghidra_functions: vec![
                "Javelin::RewardModifierDataManager::RewardModifierDataManager",
                "Javelin::RewardModifierDataManager::CacheAllDataTables",
            ],
        }),
        reward_milestone_data_manager_spec(),
        enum_projection(EnumProjectionSpec {
            module: "stat_multiplier_data",
            table_name: "StatMultiplierTable",
            row_type_name: "StatMultiplierData",
            data_type: "StaticStatMultiplierData",
            entries_field: "rows",
            index_field: "rows_by_type",
            key_field: "multiplier_type",
            key_column: "ID",
            key_getter: "id",
            key_type: "gamedata::semantic::StatMultiplierType",
            key_type_alias: None,
            table_view_alias: None,
            expose_table_constructor: false,
            invalid_key_variants: vec!["Invalid", "StatMultiplierEnd"],
            skip_empty_key: true,
            trim_key: true,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            fields: vec![
                projection_field(
                    "max",
                    "Max",
                    "max",
                    NativeProjectionTransform::F32UpperBound10000ZeroIsDefault,
                ),
                referenced_projection_field(
                    "min",
                    "Min",
                    "min",
                    NativeProjectionTransform::F32LowerBound10000CappedToField,
                    "max",
                ),
            ],
            lookup_methods: vec![enum_lookup(
                "stat_multiplier_data",
                "multiplier_type",
                NativeEnumLookupParameterKind::Enum,
            )],
            secondary_crc_index: None,
            ids_method: Some("multiplier_types"),
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::StatMultiplierDataManager",
            rust_type: "crate::StatMultiplierDataManager",
            ghidra_functions: vec![
                "Javelin::StatMultiplierDataManager::StatMultiplierDataManager",
                "Javelin::StatMultiplierDataManager::CacheAllDataTables",
            ],
        }),
        enum_projection(EnumProjectionSpec {
            module: "faction_control_data",
            table_name: "FactionControl_Buffs",
            row_type_name: "FactionControlBuffDefinitions",
            data_type: "FactionControlData",
            entries_field: "rows",
            index_field: "rows_by_type",
            key_field: "buff_type",
            key_column: "FactionControlBuffID",
            key_getter: "faction_control_buff_id",
            key_type: "gamedata::semantic::BuffType",
            key_type_alias: None,
            table_view_alias: None,
            expose_table_constructor: false,
            invalid_key_variants: vec!["NumBuffs"],
            skip_empty_key: true,
            trim_key: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            fields: vec![
                projection_field(
                    "is_territory_buff",
                    "IsTerritoryBuff",
                    "is_territory_buff",
                    NativeProjectionTransform::Bool,
                ),
                projection_field("value", "Value", "value", NativeProjectionTransform::F32),
                projection_field(
                    "name",
                    "Name",
                    "name",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "description",
                    "Description",
                    "description",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "comments",
                    "Comments",
                    "comments",
                    NativeProjectionTransform::StringList,
                ),
            ],
            lookup_methods: vec![
                enum_lookup(
                    "faction_control_data",
                    "buff_type",
                    NativeEnumLookupParameterKind::Enum,
                ),
                enum_lookup(
                    "faction_control_data_by_id",
                    "buff_id",
                    NativeEnumLookupParameterKind::AsRefStr,
                ),
                enum_lookup(
                    "faction_control_data_by_key",
                    "key",
                    NativeEnumLookupParameterKind::AsRefStr,
                ),
            ],
            secondary_crc_index: None,
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::FactionControlDataManager",
            rust_type: "crate::FactionControlDataManager",
            ghidra_functions: vec![
                "Javelin::FactionControlDataManager::FactionControlDataManager",
                "Javelin::FactionControlDataManager::CacheAllDataTables",
            ],
        }),
        enum_projection(EnumProjectionSpec {
            module: "fishing_water_data",
            table_name: "FishingWaterMastersheet",
            row_type_name: "FishingWaterData",
            data_type: "FishingWaterData",
            entries_field: "waters",
            index_field: "waters_by_type",
            key_field: "water_type",
            key_column: "Id",
            key_getter: "id",
            key_type: "gamedata::semantic::FishingWaterType",
            key_type_alias: Some("FishingWaterType"),
            table_view_alias: None,
            expose_table_constructor: false,
            invalid_key_variants: Vec::new(),
            skip_empty_key: true,
            trim_key: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            fields: vec![
                projection_field("id", "Id", "id", NativeProjectionTransform::String),
                projection_field(
                    "time_to_nibble_seconds_range",
                    "TimeToNibbleSecondsRange",
                    "time_to_nibble_seconds_range",
                    NativeProjectionTransform::F32RangeInclusive,
                ),
                projection_field(
                    "time_to_bite_seconds_range",
                    "TimeToBiteSecondsRange",
                    "time_to_bite_seconds_range",
                    NativeProjectionTransform::F32RangeInclusive,
                ),
            ],
            lookup_methods: vec![
                enum_lookup(
                    "fishing_water",
                    "water_type",
                    NativeEnumLookupParameterKind::Enum,
                ),
                enum_lookup(
                    "fishing_water_by_id",
                    "id",
                    NativeEnumLookupParameterKind::AsRefStr,
                ),
            ],
            secondary_crc_index: None,
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::FishingWaterDataManager",
            rust_type: "crate::FishingWaterDataManager",
            ghidra_functions: vec![
                "Javelin::FishingWaterDataManager::FishingWaterDataManager",
                "Javelin::FishingWaterDataManager::CacheAllDataTables",
            ],
        }),
    ]
}
