use super::super::*;

pub(super) fn specs() -> Vec<NativeManagerSpec> {
    vec![
        crc_projection(CrcProjectionSpec {
            module: "mount_data",
            table_name: "Mounts",
            row_type_name: "MountData",
            data_type: "MountData",
            entries_field: "mounts",
            index_field: "mounts_by_id",
            key_field: "mount_key",
            crc_field: "mount_id",
            key_column: "MountId",
            key_getter: "mount_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("mount_data_for_source_row"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "display_name_id",
                    "DisplayName",
                    "display_name",
                    NativeProjectionTransform::LowercaseCrcString,
                ),
                projection_field(
                    "display_name",
                    "DisplayName",
                    "display_name",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "mount_type_row",
                    "MountType",
                    "mount_type",
                    NativeProjectionTransform::ForeignKeyRow,
                ),
                projection_field(
                    "icon_path",
                    "IconPath",
                    "icon_path",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "hi_res_icon_path",
                    "HiResIconPath",
                    "hi_res_icon_path",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "mtx_icon_path",
                    "MtxIconPath",
                    "mtx_icon_path",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "display_priority",
                    "DisplayPriority",
                    "display_priority",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "sorted_order",
                    "SortedOrder",
                    "sorted_order",
                    NativeProjectionTransform::NonZeroU32,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "mount_data_from_id",
                    "mount_id",
                    NativeCrcIndexLookupParameterKind::IntoCrc32,
                ),
                lookup(
                    "mount_data",
                    "mount_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "mount_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::MountDataManager",
            rust_type: "crate::MountDataManager",
            ghidra_functions: vec![
                "Javelin::MountDataManager::MountDataManager",
                "Javelin::MountDataManager::CacheAllDataTables",
            ],
        }),
        crc_projection(CrcProjectionSpec {
            module: "mount_type_data",
            table_name: "MountTypes",
            row_type_name: "MountTypeData",
            data_type: "MountTypeData",
            entries_field: "mount_types",
            index_field: "mount_types_by_id",
            key_field: "mount_key",
            crc_field: "mount_id",
            key_column: "MountID",
            key_getter: "mount_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: true,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("mount_type_for_source_row"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "mount_hit_volume_prefab_id",
                    "MountHitVolumePrefab",
                    "mount_hit_volume_prefab",
                    NativeProjectionTransform::LowercaseCrcString,
                ),
                projection_field(
                    "mount_hit_volume_prefab",
                    "MountHitVolumePrefab",
                    "mount_hit_volume_prefab",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "container_definition",
                    "ContDef",
                    "cont_def",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "animation_database",
                    "ADB",
                    "adb",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "footstep_material",
                    "FootStepMat",
                    "foot_step_mat",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "tradeskill_progression_id",
                    "TradeskillProgressionId",
                    "tradeskill_progression_id",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "sorted_order",
                    "SortedOrder",
                    "sorted_order",
                    NativeProjectionTransform::NonZeroU32,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "mount_type_from_id",
                    "mount_id",
                    NativeCrcIndexLookupParameterKind::IntoCrc32,
                ),
                lookup(
                    "mount_type",
                    "mount_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "mount_type_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::MountTypeDataManager",
            rust_type: "crate::MountTypeDataManager",
            ghidra_functions: vec![
                "Javelin::MountTypeDataManager::MountTypeDataManager",
                "Javelin::MountTypeDataManager::CacheAllDataTables",
            ],
        }),
        schema_crc_projection(
            CrcProjectionSpec {
                module: "mount_movement_data",
                table_name: "MountsMovement",
                row_type_name: "MountMovementData",
                data_type: "MountMovementData",
                entries_field: "movements",
                index_field: "movements_by_id",
                key_field: "movement_key",
                crc_field: "movement_id",
                key_column: "Id",
                key_getter: "id",
                skip_empty_key: true,
                trim_key: false,
                reject_zero_crc: false,
                duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
                source_row_field: Some("source_row"),
                source_row_method: Some("mount_movement_for_source_row"),
                row_filters: Vec::new(),
                fields: Vec::new(),
                secondary_indexes: Vec::new(),
                lookup_methods: vec![
                    lookup(
                        "mount_movement_from_id",
                        "movement_id",
                        NativeCrcIndexLookupParameterKind::IntoCrc32,
                    ),
                    lookup(
                        "mount_movement",
                        "movement_id",
                        NativeCrcIndexLookupParameterKind::AsRefStr,
                    ),
                    lookup(
                        "mount_movement_by_key",
                        "key",
                        NativeCrcIndexLookupParameterKind::AsRefStr,
                    ),
                ],
                ids_method: None,
                rows_method: Some("rows"),
                len_method: Some("len"),
                is_empty_method: Some("is_empty"),
                ghidra_class: "Javelin::MountMovementDataManager",
                rust_type: "crate::MountMovementDataManager",
                ghidra_functions: vec![
                    "Javelin::MountMovementDataManager::MountMovementDataManager",
                    "Javelin::MountMovementDataManager::CacheAllDataTables",
                ],
            },
            NativeSchemaProjectionFields::all_non_key(),
        ),
        crc_projection(CrcProjectionSpec {
            module: "mount_dye_item_data",
            table_name: "MountDyeItemDefinitions",
            row_type_name: "MountDyeItemDefinitions",
            data_type: "MountDyeItemData",
            entries_field: "mount_dye_items",
            index_field: "rows_by_crc",
            key_field: "mount_dye_item_id",
            crc_field: "mount_dye_item_id_crc",
            key_column: "mount_dye_item_id",
            key_getter: "mount_dye_item_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::Error,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "color_index",
                    "color_index",
                    "color_index",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "name_note",
                    "name_note",
                    "name_note",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "bool_note",
                    "bool_note",
                    "bool_note",
                    NativeProjectionTransform::OptionalString,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "mount_dye_item_from_id",
                    "mount_dye_item_id",
                    NativeCrcIndexLookupParameterKind::IntoCrc32,
                ),
                lookup(
                    "mount_dye_item",
                    "mount_dye_item_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "mount_dye_item_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::MountDyeItemDataManager",
            rust_type: "crate::MountDyeItemDataManager",
            ghidra_functions: vec![
                "Javelin::MountDyeItemDataManager::MountDyeItemDataManager",
                "Javelin::MountDyeItemDataManager::CacheAllDataTables",
            ],
        }),
        crc_projection(CrcProjectionSpec {
            module: "mount_item_appearance_data",
            table_name: "MountItemAppearanceDefinitions",
            row_type_name: "MountItemAppearanceDefinitions",
            data_type: "MountItemAppearanceData",
            entries_field: "mount_item_appearances",
            index_field: "rows_by_crc",
            key_field: "appearance_id",
            crc_field: "appearance_id_crc",
            key_column: "MountItemAppearanceID",
            key_getter: "mount_item_appearance_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::Error,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "auto_flip_z_axis",
                    "AutoFlipZAxis",
                    "auto_flip_z_axis",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "mirror_item",
                    "MirrorItem",
                    "mirror_item",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "enable_light",
                    "EnableLight",
                    "enable_light",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "light_diffuse_multiplier",
                    "LightDiffuseMultiplier",
                    "light_diffuse_multiplier",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "light_max_distance",
                    "LightMaxDistance",
                    "light_max_distance",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "light_attenuation_bulb_size",
                    "LightAttenuationBulbSize",
                    "light_attenuation_bulb_size",
                    NativeProjectionTransform::U32,
                ),
                projection_field(
                    "light_color_override",
                    "LightColorOverride",
                    "light_color_override",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "light_position_override",
                    "LightPositionOverride",
                    "light_position_override",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "light_rotation_override",
                    "LightRotationOverride",
                    "light_rotation_override",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "enable_particle",
                    "EnableParticle",
                    "enable_particle",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "particle_effect",
                    "ParticleEffect",
                    "particle_effect",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "particle_color_override",
                    "ParticleColorOverride",
                    "particle_color_override",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "particle_position_override",
                    "ParticlePositionOverride",
                    "particle_position_override",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "particle_rotation_override",
                    "ParticleRotationOverride",
                    "particle_rotation_override",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "particle_scale_override",
                    "ParticleScaleOverride",
                    "particle_scale_override",
                    NativeProjectionTransform::OptionalF32,
                ),
                projection_field(
                    "icon_path",
                    "IconPath",
                    "icon_path",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "hi_res_icon_path",
                    "HiResIconPath",
                    "hi_res_icon_path",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "right_attachment_position",
                    "RightAttachmentPosition",
                    "right_attachment_position",
                    NativeProjectionTransform::F32ListDefaultEmpty,
                ),
                projection_field(
                    "right_attachment_rotation",
                    "RightAttachmentRotation",
                    "right_attachment_rotation",
                    NativeProjectionTransform::I32ListDefaultEmpty,
                ),
                projection_field(
                    "right_attachment_scale",
                    "RightAttachmentScale",
                    "right_attachment_scale",
                    NativeProjectionTransform::F32ListDefaultEmpty,
                ),
                projection_field(
                    "left_attachment_position",
                    "LeftAttachmentPosition",
                    "left_attachment_position",
                    NativeProjectionTransform::F32ListDefaultEmpty,
                ),
                projection_field(
                    "left_attachment_rotation",
                    "LeftAttachmentRotation",
                    "left_attachment_rotation",
                    NativeProjectionTransform::I32ListDefaultEmpty,
                ),
                projection_field(
                    "left_attachment_scale",
                    "LeftAttachmentScale",
                    "left_attachment_scale",
                    NativeProjectionTransform::F32ListDefaultEmpty,
                ),
                projection_field(
                    "left_on",
                    "LeftOn",
                    "left_on",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "right_off",
                    "RightOff",
                    "right_off",
                    NativeProjectionTransform::OptionalString,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "mount_item_appearance_from_id",
                    "appearance_id",
                    NativeCrcIndexLookupParameterKind::IntoCrc32,
                ),
                lookup(
                    "mount_item_appearance",
                    "appearance_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "mount_item_appearance_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::MountItemAppearanceDataManager",
            rust_type: "crate::MountItemAppearanceDataManager",
            ghidra_functions: vec![
                "Javelin::MountItemAppearanceDataManager::MountItemAppearanceDataManager",
                "Javelin::MountItemAppearanceDataManager::CacheAllDataTables",
            ],
        }),
        enum_projection(EnumProjectionSpec {
            module: "musical_scoring_data",
            table_name: "MusicalScoringTable",
            row_type_name: "MusicalScoring",
            data_type: "MusicalScoringData",
            entries_field: "scores",
            index_field: "scores_by_input_result",
            key_field: "input_result",
            key_column: "InputType",
            key_getter: "input_type",
            key_type: "newworld_plugin::game_data::MusicalPerformanceInputResult",
            key_type_alias: None,
            table_view_alias: None,
            expose_table_constructor: false,
            invalid_key_variants: Vec::new(),
            skip_empty_key: true,
            trim_key: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            fields: vec![
                projection_field(
                    "input_type",
                    "InputType",
                    "input_type",
                    NativeProjectionTransform::String,
                ),
                projection_field("points", "Points", "points", NativeProjectionTransform::U32),
            ],
            lookup_methods: vec![
                enum_lookup(
                    "musical_scoring",
                    "input_result",
                    NativeEnumLookupParameterKind::Enum,
                ),
                enum_lookup(
                    "musical_scoring_by_input_type",
                    "input_type",
                    NativeEnumLookupParameterKind::AsRefStr,
                ),
            ],
            secondary_crc_index: None,
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::MusicalScoringDataManager",
            rust_type: "crate::MusicalScoringDataManager",
            ghidra_functions: vec![
                "Javelin::MusicalScoringDataManager::MusicalScoringDataManager",
                "Javelin::MusicalScoringDataManager::CacheAllDataTables",
            ],
        }),
        musical_ranking_data_manager_spec(),
        crc_projection(CrcProjectionSpec {
            module: "notification_data",
            table_name: "Notifications",
            row_type_name: "NotificationData",
            data_type: "NotificationData",
            entries_field: "notifications",
            index_field: "rows_by_notification_id",
            key_field: "notification_id",
            crc_field: "notification_id_crc",
            key_column: "NotificationId",
            key_getter: "notification_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::Overwrite,
            source_row_field: Some("source_row"),
            source_row_method: None,
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "display_title",
                    "DisplayTitle",
                    "display_title",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "display_text",
                    "DisplayText",
                    "display_text",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "secondary_text",
                    "SecondaryText",
                    "secondary_text",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "icon_path",
                    "IconPath",
                    "icon_path",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "max_display_count",
                    "MaxDisplayCount",
                    "max_display_count",
                    NativeProjectionTransform::I32,
                ),
                projection_field(
                    "notification_type",
                    "NotificationType",
                    "notification_type",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "track_display_count",
                    "TrackDisplayCount",
                    "track_display_count",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "duration_override",
                    "DurationOverride",
                    "duration_override",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "cooldown_seconds",
                    "CooldownSeconds",
                    "cooldown_seconds",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "keybind",
                    "Keybind",
                    "keybind",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "keybind_action_map",
                    "KeybindActionmap",
                    "keybind_actionmap",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "number_fields",
                    "NumberFields",
                    "number_fields",
                    NativeProjectionTransform::OptionalCrcListDefaultEmpty,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "notification_data",
                    "notification_id",
                    NativeCrcIndexLookupParameterKind::IntoCrc32,
                ),
                lookup(
                    "notification_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("notifications"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::NotificationDataManager",
            rust_type: "crate::NotificationDataManager",
            ghidra_functions: vec![
                "Javelin::NotificationDataManager::FUN_7ff6044580c0",
                "Javelin::NotificationDataManager::FUN_7ff60445bbc0",
            ],
        }),
        npc_data_manager_spec(),
        simple_tree_category_data_manager_spec(),
        weapon_appearance_data_manager_spec(),
        weapon_item_data_manager_spec(),
        weapon_ref_data_manager_spec(),
        title_data_manager_spec(),
        story_progress_data_manager_spec(),
        currency_exchange_mapping_manager_spec(),
        vitals_modifier_mapping_manager_spec(),
        combat_profiles_data_manager_spec(),
        elemental_mutation_static_data_manager_spec(),
    ]
}
