use super::super::*;

pub(super) fn specs() -> Vec<NativeManagerSpec> {
    vec![
        one_table_crc(OneTableCrcSpec {
            module: "ai_targeting_data",
            table_name: "AITargeting",
            row_type_name: "AITargetingData",
            row_alias: "AITargetingDataRow",
            table_field: "table",
            key_column: "CreatureType",
            key_getter: "creature_type",
            lookup_methods: vec![
                lookup(
                    "ai_targeting_data",
                    "creature_type",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
                lookup(
                    "ai_targeting_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
            ],
            ghidra_class: "Javelin::AITargetingDataManager",
            rust_type: "crate::AITargetingDataManager",
            ghidra_functions: vec![
                "Javelin::AITargetingDataManager::AITargetingDataManager",
                "Javelin::AITargetingDataManager::CacheAllDataTables",
            ],
            ..OneTableCrcSpec::default()
        }),
        table_family_crc_projection(TableFamilyCrcProjectionSpec {
            module: "ammo_item_definitions",
            table_module: None,
            tables: vec![
                TableFamilyTableSpec {
                    variant: "AmmoItemDefinitions".to_owned(),
                    table_name: "AmmoItemDefinitions",
                    row_type_name: "AmmoItemDefinitions",
                },
                TableFamilyTableSpec {
                    variant: "IsleOfNight".to_owned(),
                    table_name: "AmmoItemDefinitions_IsleOfNight",
                    row_type_name: "AmmoItemDefinitions",
                },
            ],
            tables_type: "AmmoItemDefinitionsTables",
            table_type: "AmmoItemDefinitionsTable",
            handle_type: "AmmoItemDefinitionsHandle",
            row_alias: "AmmoItemDefinitionsRow",
            data_type: "AmmoItemData",
            entries_field: "ammo_items",
            index_field: "rows_by_crc",
            key_field: "ammo_id",
            crc_field: "ammo_id_crc",
            key_column: "AmmoID",
            key_getter: "ammo_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::Error,
            source_row_field: Some("source_row"),
            source_row_method: None,
            source_row_by_crc_method: None,
            source_handle_field: None,
            source_handle_method: None,
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "ammo_type",
                    "AmmoType",
                    "ammo_type",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "damage_modifier",
                    "DamageModifier",
                    "damage_modifier",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "stagger_damage_modifier",
                    "StaggerDamageModifier",
                    "stagger_damage_modifier",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "ammo_prefab_path",
                    "AmmoPrefabPath",
                    "ammo_prefab_path",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "ammo_whiz_by_trigger",
                    "AmmoWhizByTrigger",
                    "ammo_whiz_by_trigger",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "mesh_override",
                    "MeshOverride",
                    "mesh_override",
                    NativeProjectionTransform::OptionalString,
                ),
            ],
            table_indexes: Vec::new(),
            field_lookup_methods: Vec::new(),
            store_key_text: true,
            lookup_methods: vec![
                lookup(
                    "ammo_item_from_id",
                    "ammo_id",
                    NativeCrcIndexLookupParameterKind::IntoCrc32,
                ),
                lookup(
                    "ammo_item",
                    "ammo_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "ammo_item_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::AmmoItemDataManager",
            rust_type: "crate::AmmoItemDataManager",
            ghidra_functions: vec![
                "Javelin::AmmoItemDataManager::AmmoItemDataManager",
                "Javelin::AmmoItemDataManager::CacheAllDataTables",
            ],
        }),
        owned_string(OwnedStringSpec {
            module: "appearance_transform_data",
            table_name: "DefaultAppearanceTransforms",
            row_type_name: "AppearanceTransforms",
            row_alias: "AppearanceTransformDataRow",
            table_field: "table",
            indexes_field: "transforms",
            indexed_type: "IndexedAppearanceTransform",
            indexes_type: "AppearanceTransformIndexes",
            indexed_key_field: "old_appearance_id",
            key_column: "oldAppearanceId",
            key_getter: "old_appearance_id",
            skip_empty_key: true,
            duplicate_manager_label: "AppearanceTransformDataManager",
            duplicate_key_label: "oldAppearanceId",
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            lookup_methods: vec![
                lookup(
                    "appearance_transform",
                    "old_appearance_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "appearance_transform_by_key",
                    "old_appearance_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "appearance_transform_from_id",
                    "old_appearance_id",
                    NativeCrcIndexLookupParameterKind::IntoCrc32,
                ),
            ],
            source_row_method: Some("source_row"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::AppearanceTransformDataManager",
            rust_type: "crate::AppearanceTransformDataManager",
            ghidra_functions: vec![
                "Javelin::AppearanceTransformDataManager::AppearanceTransformDataManager",
                "Javelin::AppearanceTransformDataManager::CacheAllDataTables",
            ],
            ..OwnedStringSpec::default()
        }),
        one_table_crc(OneTableCrcSpec {
            module: "beam_data",
            table_name: "Beams",
            row_type_name: "BeamData",
            row_alias: "BeamDataRow",
            table_field: "table",
            key_column: "BeamID",
            key_getter: "beam_id",
            lookup_methods: vec![
                lookup(
                    "beam_data",
                    "beam_id",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
                lookup(
                    "beam_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
            ],
            ghidra_class: "Javelin::BeamDataManager",
            rust_type: "crate::BeamDataManager",
            ghidra_functions: vec![
                "Javelin::BeamDataManager::BeamDataManager",
                "Javelin::BeamDataManager::CacheAllDataTables",
            ],
            ..OneTableCrcSpec::default()
        }),
        crc_projection(CrcProjectionSpec {
            module: "blueprint_item_data",
            table_name: "Blueprint",
            row_type_name: "BlueprintItemDefinitions",
            data_type: "BlueprintItemData",
            entries_field: "blueprint_items",
            index_field: "rows_by_crc",
            key_field: "blueprint_id",
            crc_field: "blueprint_id_crc",
            key_column: "BlueprintID",
            key_getter: "blueprint_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::Error,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field("name", "Name", "name", NativeProjectionTransform::String),
                projection_field(
                    "display_class",
                    "DisplayClass",
                    "display_class",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "attachment_categories",
                    "AttachmentCategories",
                    "attachment_categories",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "use_reduced_build_mode_ui",
                    "UseReducedBuildModeUI",
                    "use_reduced_build_mode_ui",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "is_camp",
                    "IsCamp",
                    "is_camp",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "is_pvp_camp",
                    "IsPvPCamp",
                    "is_pv_p_camp",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "pvp_camp_variant_id",
                    "PvPCampVariantID",
                    "pv_p_camp_variant_id",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "is_deployable",
                    "IsDeployable",
                    "is_deployable",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "is_siege_weapon",
                    "IsSiegeWeapon",
                    "is_siege_weapon",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "tradeskill_level",
                    "TradeskillLevel",
                    "tradeskill_level",
                    NativeProjectionTransform::U32,
                ),
                projection_field(
                    "war_points",
                    "WarPoints",
                    "war_points",
                    NativeProjectionTransform::U32,
                ),
                projection_field("hp", "HP", "hp", NativeProjectionTransform::U32),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "blueprint_item",
                    "blueprint_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "blueprint_item_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "blueprint_item_from_id",
                    "blueprint_id",
                    NativeCrcIndexLookupParameterKind::IntoCrc32,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::BlueprintItemDataManager",
            rust_type: "crate::BlueprintItemDataManager",
            ghidra_functions: vec![
                "Javelin::BlueprintItemDataManager::BlueprintItemDataManager",
                "Javelin::BlueprintItemDataManager::CacheAllDataTables",
            ],
        }),
        camp_skin_data_manager_spec(),
        camera_shake_data_manager_spec(),
        dye_color_data_manager_spec(),
        emote_data_manager_spec(),
        experience_data_manager_spec(),
        store_category_data_manager_spec(),
        store_product_data_manager_spec(),
        reward_track_item_data_manager_spec(),
        post_skill_cap_progression_data_manager_spec(),
        quick_course_data_manager_spec(),
        rotational_queue_data_manager_spec(),
        whisper_data_manager_spec(),
        world_event_rule_data_manager_spec(),
        crc_projection(CrcProjectionSpec {
            module: "vitals_category_data",
            table_name: "VitalsCategories",
            row_type_name: "VitalsCategoryData",
            data_type: "VitalsCategoryData",
            entries_field: "categories",
            index_field: "rows_by_crc",
            key_field: "vitals_category_id",
            crc_field: "vitals_category_id_crc",
            key_column: "VitalsCategoryID",
            key_getter: "vitals_category_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: true,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "display_name",
                    "DisplayName",
                    "display_name",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "icon",
                    "Icon",
                    "icon",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "location_hint",
                    "LocationHint",
                    "location_hint",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "schedule_vcs",
                    "ScheduleVCs",
                    "schedule_v_cs",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "loc_string_generation_helper",
                    "LocStringGenerationHelper",
                    "loc_string_generation_helper",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "group_vitals_category_id",
                    "GroupVitalsCategoryId",
                    "group_vitals_category_id",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "is_named",
                    "IsNamed",
                    "is_named",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "is_dynamic_poi_target",
                    "IsDynamicPoiTarget",
                    "is_dynamic_poi_target",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "loot_drop_chance_override",
                    "LootDropChanceOverride",
                    "loot_drop_chance_override",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "progression_currency_ids",
                    "ProgressionCurrencyIds",
                    "progression_currency_ids",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "mtl_override",
                    "MtlOverride",
                    "mtl_override",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "female_mtl_override",
                    "FemaleMtlOverride",
                    "female_mtl_override",
                    NativeProjectionTransform::OptionalString,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "vitals_category_data_from_id",
                    "category_id",
                    NativeCrcIndexLookupParameterKind::IntoCrc32,
                ),
                lookup(
                    "vitals_category_data",
                    "category_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "vitals_category_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("categories"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::VitalsCategoryDataManager",
            rust_type: "crate::VitalsCategoryDataManager",
            ghidra_functions: vec![
                "Javelin::VitalsCategoryDataManager::VitalsCategoryDataManager",
                "Javelin::VitalsCategoryDataManager::CacheAllDataTables",
            ],
        }),
        owned_string(OwnedStringSpec {
            module: "armor_appearance_data",
            table_name: "ArmorAppearances",
            row_type_name: "ArmorAppearanceDefinitions",
            row_alias: "ArmorAppearanceDataRow",
            table_field: "table",
            indexes_field: "armor_appearances",
            indexed_type: "IndexedArmorAppearance",
            indexes_type: "ArmorAppearanceIndexes",
            indexed_key_field: "item_id",
            key_column: "ItemID",
            key_getter: "item_id",
            skip_empty_key: true,
            duplicate_manager_label: "ArmorAppearanceDataManager",
            duplicate_key_label: "ItemID",
            lookup_methods: vec![
                lookup(
                    "armor_appearance",
                    "item_id",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
                lookup(
                    "armor_appearance_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::StrRef,
                ),
            ],
            source_row_method: Some("source_row"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::ArmorAppearanceDataManager",
            rust_type: "crate::ArmorAppearanceDataManager",
            ghidra_functions: vec![
                "Javelin::ArmorAppearanceDataManager::ArmorAppearanceDataManager",
                "Javelin::ArmorAppearanceDataManager::CacheAllDataTables",
            ],
            ..OwnedStringSpec::default()
        }),
        one_table_crc(OneTableCrcSpec {
            module: "game_mode_data",
            table_name: "GameModes",
            row_type_name: "GameModeData",
            row_alias: "GameModeData",
            table_field: "table",
            key_column: "GameModeId",
            key_getter: "game_mode_id",
            row_key_method: None,
            row_crc_method: Some("game_mode_id_crc"),
            hash_policy: NativeCrcHashPolicy::Lowercase,
            reject_zero_crc: true,
            lookup_methods: vec![
                lookup(
                    "game_mode",
                    "id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "game_mode_from_id",
                    "id",
                    NativeCrcIndexLookupParameterKind::IntoCrc32,
                ),
            ],
            source_row_method: Some("source_row"),
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::GameModeDataManager",
            rust_type: "crate::GameModeDataManager",
            ghidra_functions: vec![
                "Javelin::GameModeDataManager::GameModeDataManager",
                "Javelin::GameModeDataManager::CacheAllDataTables",
                "Javelin::GameModeDataManager::FindGameSystemDataByKey",
                "Javelin::GameModeDataManager::GetGameSystemData",
            ],
        }),
        one_table_crc(OneTableCrcSpec {
            module: "game_mode_map_data",
            table_name: "GameModeMap",
            row_type_name: "GameModeMapData",
            row_alias: "GameModeMapData",
            table_field: "table",
            key_column: "GameModeMapId",
            key_getter: "game_mode_map_id",
            row_key_method: None,
            row_crc_method: Some("game_mode_map_id_crc"),
            hash_policy: NativeCrcHashPolicy::Lowercase,
            reject_zero_crc: true,
            lookup_methods: vec![
                lookup(
                    "game_mode_map",
                    "id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "game_mode_map_from_id",
                    "id",
                    NativeCrcIndexLookupParameterKind::IntoCrc32,
                ),
            ],
            source_row_method: Some("source_row"),
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::GameModeMapDataManager",
            rust_type: "crate::GameModeMapDataManager",
            ghidra_functions: vec!["Javelin::GameModeMapDataManager::GameModeMapDataManager"],
        }),
        crc_projection(CrcProjectionSpec {
            module: "generic_invite_static_data",
            table_name: "GenericInvites",
            row_type_name: "GenericInviteData",
            data_type: "GenericInviteStaticData",
            entries_field: "invites",
            index_field: "rows_by_activity_crc",
            key_field: "activity_key",
            crc_field: "activity_crc",
            key_column: "ActivityCrc",
            key_getter: "activity_crc",
            skip_empty_key: true,
            trim_key: true,
            reject_zero_crc: true,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: None,
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "activity_type",
                    "ActivityType",
                    "activity_type",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "duration_sec",
                    "DurationSec",
                    "duration_sec",
                    NativeProjectionTransform::F32,
                ),
                projection_field("teams", "Teams", "teams", NativeProjectionTransform::U32),
                projection_field(
                    "min_level",
                    "MinLevel",
                    "min_level",
                    NativeProjectionTransform::U32,
                ),
                projection_field(
                    "max_level",
                    "MaxLevel",
                    "max_level",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "faction_type",
                    "FactionType",
                    "faction_type",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "min_distance",
                    "MinDistance",
                    "min_distance",
                    NativeProjectionTransform::OptionalF32,
                ),
                projection_field(
                    "max_distance",
                    "MaxDistance",
                    "max_distance",
                    NativeProjectionTransform::F32,
                ),
                projection_field(
                    "allow_in_sanctuary",
                    "AllowInSanctuary",
                    "allow_in_sanctuary",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "allow_in_ftue",
                    "AllowInFtue",
                    "allow_in_ftue",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "allow_in_war_prep",
                    "AllowInWarPrep",
                    "allow_in_war_prep",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "allow_in_war",
                    "AllowInWar",
                    "allow_in_war",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "allow_in_arena",
                    "AllowInArena",
                    "allow_in_arena",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "allow_in_ffa",
                    "AllowInFFA",
                    "allow_in_ffa",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "allow_accept_while_pvp_flagged",
                    "AllowAcceptWhilePvpFlagged",
                    "allow_accept_while_pvp_flagged",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "disallow_in_game_mode_rows",
                    "DisallowInGameModes",
                    "disallow_in_game_modes",
                    NativeProjectionTransform::ForeignKeyRowList,
                ),
                projection_field(
                    "disallowed_water_depths",
                    "DisallowedWaterDepths",
                    "disallowed_water_depths",
                    NativeProjectionTransform::OptionalString,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "generic_invite_static_data",
                    "activity_crc",
                    NativeCrcIndexLookupParameterKind::IntoCrc32,
                ),
                lookup(
                    "generic_invite_static_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("invites"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::GenericInviteStaticDataManager",
            rust_type: "crate::GenericInviteStaticDataManager",
            ghidra_functions: vec![
                "Javelin::GenericInviteStaticDataManager::GenericInviteStaticDataManager",
            ],
        }),
    ]
}
