use super::super::*;

pub(super) fn specs() -> Vec<NativeManagerSpec> {
    vec![
        promotion_mutation_static_data_manager_spec(),
        status_effect_data_manager_spec(),
        musical_rewards_data_manager_spec(),
        item_data_manager_spec(),
        item_conversion_data_manager_spec(),
        item_transform_data_manager_spec(),
        crc_projection(CrcProjectionSpec {
            module: "perk_bucket_data",
            table_name: "PerkBuckets",
            row_type_name: "PerkBucketData",
            data_type: "StaticPerkBucketData",
            entries_field: "buckets",
            index_field: "buckets_by_id",
            key_field: "perk_bucket_id",
            crc_field: "perk_bucket_id_crc",
            key_column: "PerkBucketId",
            key_getter: "perk_bucket_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "ignore_exclusive_label_weights",
                    "IgnoreExclusiveLabelWeights",
                    "ignore_exclusive_label_weights",
                    NativeProjectionTransform::OptionalBool,
                ),
                projection_field(
                    "disable_perk_biasing",
                    "DisablePerkBiasing",
                    "disable_perk_biasing",
                    NativeProjectionTransform::OptionalBool,
                ),
                projection_field(
                    "perk_type",
                    "PerkType",
                    "perk_type",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "perk_chance",
                    "PerkChance",
                    "perk_chance",
                    NativeProjectionTransform::OptionalF32,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "perk_bucket_data_from_id",
                    "perk_bucket_id",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "perk_bucket_data",
                    "perk_bucket_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "perk_bucket_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: Some("perk_bucket_ids"),
            rows_method: Some("buckets"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::PerkBucketDataManager",
            rust_type: "crate::PerkBucketDataManager",
            ghidra_functions: vec![
                "Javelin::PerkBucketDataManager::CachePerkBucketDataTables",
                "Javelin::PerkBucketDataManager::FindBucket",
                "Javelin::PerkBucketDataManager::CollectPerksFromBucket",
                "Javelin::PerkBucketDataManager::CollectWeightedPerksFromBucket",
                "Javelin::PerkBucketDataManager::FindValidPerkForItem",
            ],
        }),
        replication_data_manager_spec(),
        progression_point_data_manager_spec(),
        reward_track_data_manager_spec(),
        loot_bucket_data_manager_spec(),
        entitlement_data_manager_spec(),
        equipment_set_data_manager_spec(),
        territory_definitions_data_manager_spec(),
        seasons_rewards_data_manager_spec(),
        seasons_tracked_stat_data_manager_spec(),
        stat_modifier_data_manager_spec(),
        recipe_data_manager_spec(),
        gatherable_data_manager_spec(),
        governance_data_manager_spec(),
        schedule_data_manager_spec(),
        meta_achievement_data_manager_spec(),
        static_backstory_data_manager_spec(),
        mutation_difficulty_static_data_manager_spec(),
        seasons_rewards_activities_tasks_data_manager_spec(),
        seasons_rewards_activities_config_data_manager_spec(),
        seasons_rewards_task_data_manager_spec(),
        seasons_rewards_season_data_manager_spec(),
        seasons_rewards_battle_pass_data_manager_spec(),
        seasons_rewards_card_data_manager_spec(),
        seasons_rewards_card_template_data_manager_spec(),
        tradeskill_rank_data_manager_spec(),
        seasons_rewards_chapter_data_manager_spec(),
        seasons_rewards_journey_data_manager_spec(),
        song_book_sheet_data_manager_spec(),
        song_book_data_manager_spec(),
        shop_data_manager_spec(),
        static_tradeskill_rank_data_mapping_manager_spec(),
    ]
}
