use super::super::*;

pub(super) fn specs() -> Vec<NativeManagerSpec> {
    vec![
        crc_projection(CrcProjectionSpec {
            module: "fish_behavior_data",
            table_name: "FishingBehaviorsMastersheet",
            row_type_name: "FishingBehaviorsData",
            data_type: "FishBehaviorData",
            entries_field: "behaviors",
            index_field: "behaviors_by_crc",
            key_field: "id",
            crc_field: "id_crc32",
            key_column: "Id",
            key_getter: "id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "fish_behavior_pattern",
                    "FishBehaviorPattern",
                    "fish_behavior_pattern",
                    NativeProjectionTransform::U32,
                ),
                projection_field(
                    "fish_behavior_localization_key",
                    "FishBehaviorLocalizationKey",
                    "fish_behavior_localization_key",
                    NativeProjectionTransform::String,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "fish_behavior",
                    "id",
                    NativeCrcIndexLookupParameterKind::IntoCrc32,
                ),
                lookup(
                    "fish_behavior_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::FishBehaviorDataManager",
            rust_type: "crate::FishBehaviorDataManager",
            ghidra_functions: vec!["Javelin::FishBehaviorDataManager::CacheAllDataTables"],
        }),
        crc_projection_with_options(
            CrcProjectionSpec {
                module: "fishing_bait_data",
                table_name: "FishingBaitMastersheet",
                row_type_name: "FishingBaitData",
                data_type: "FishingBaitData",
                entries_field: "rows",
                index_field: "rows_by_crc32",
                key_field: "bait_id",
                crc_field: "bait_crc32",
                key_column: "Id",
                key_getter: "id",
                skip_empty_key: true,
                trim_key: true,
                reject_zero_crc: false,
                duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
                source_row_field: Some("source"),
                source_row_method: Some("source_row"),
                row_filters: Vec::new(),
                fields: vec![
                    projection_field(
                        "fish_rarity_roll_modifier",
                        "FishRarityRollModifier",
                        "fish_rarity_roll_modifier",
                        NativeProjectionTransform::F32,
                    ),
                    projection_field(
                        "fish_size_roll_modifier",
                        "FishSizeRollModifier",
                        "fish_size_roll_modifier",
                        NativeProjectionTransform::F32,
                    ),
                    projection_field(
                        "summer_fish_rarity_roll_modifier",
                        "SummerFishRarityRollModifier",
                        "summer_fish_rarity_roll_modifier",
                        NativeProjectionTransform::F32,
                    ),
                    projection_field(
                        "water_tag_requirements",
                        "RequiredWaterTags",
                        "required_water_tags",
                        NativeProjectionTransform::TrimmedLowercaseCrcStringList,
                    ),
                    projection_field(
                        "active_at_dawn",
                        "ActiveAtDawn",
                        "active_at_dawn",
                        NativeProjectionTransform::Bool,
                    ),
                    projection_field(
                        "active_at_daytime",
                        "ActiveAtDaytime",
                        "active_at_daytime",
                        NativeProjectionTransform::Bool,
                    ),
                    projection_field(
                        "active_at_dusk",
                        "ActiveAtDusk",
                        "active_at_dusk",
                        NativeProjectionTransform::Bool,
                    ),
                    projection_field(
                        "active_at_night",
                        "ActiveAtNight",
                        "active_at_night",
                        NativeProjectionTransform::Bool,
                    ),
                    projection_field(
                        "loot_table_id",
                        "LootTableId",
                        "loot_table_id",
                        NativeProjectionTransform::OptionalTrimmedLowercaseCrcStringDefaultZero,
                    ),
                    projection_field(
                        "time_to_nibble_seconds_multiplier",
                        "TimeToNibbleSecondsMultiplier",
                        "time_to_nibble_seconds_multiplier",
                        NativeProjectionTransform::F32,
                    ),
                ],
                secondary_indexes: Vec::new(),
                lookup_methods: vec![
                    lookup(
                        "fishing_bait",
                        "bait_id",
                        NativeCrcIndexLookupParameterKind::AsRefStr,
                    ),
                    lookup(
                        "fishing_bait_by_crc32",
                        "bait_id",
                        NativeCrcIndexLookupParameterKind::IntoCrc32,
                    ),
                ],
                ids_method: None,
                rows_method: Some("rows"),
                len_method: Some("len"),
                is_empty_method: Some("is_empty"),
                ghidra_class: "Javelin::FishingBaitDataManager",
                rust_type: "crate::FishingBaitDataManager",
                ghidra_functions: vec!["Javelin::FishingBaitDataManager::FishingBaitDataManager"],
            },
            NativeCrcHashPolicy::Lowercase,
            Some("FishingBaitDataHandle"),
        ),
        crc_projection(CrcProjectionSpec {
            module: "twitch_drops_stat_data",
            table_name: "TwitchDropsStatDefinitions",
            row_type_name: "TwitchDropsStatDefinitions",
            data_type: "TwitchDropsStatData",
            entries_field: "rows",
            index_field: "rows_by_id",
            key_field: "twitch_drop_id",
            crc_field: "twitch_drop_id_crc32",
            key_column: "TwitchDropId",
            key_getter: "twitch_drop_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: true,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            row_filters: Vec::new(),
            fields: vec![projection_field(
                "rule_key_event",
                "RuleKeyEvent",
                "rule_key_event",
                NativeProjectionTransform::String,
            )],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "twitch_drops_stat_data_from_id",
                    "twitch_drop_id",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "twitch_drops_stat_data",
                    "twitch_drop_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::TwitchDropsStatDataManager",
            rust_type: "crate::TwitchDropsStatDataManager",
            ghidra_functions: vec![
                "Javelin::TwitchDropsStatDataManager::FindGameSystemDataByKey",
                "Javelin::TwitchDropsStatDataManager::Get",
            ],
        }),
        crc_projection(CrcProjectionSpec {
            module: "lore_item_data",
            table_name: "LoreItemDefinitions",
            row_type_name: "LoreItemDefinitions",
            data_type: "LoreItemData",
            entries_field: "lore_items",
            index_field: "rows_by_crc",
            key_field: "lore_item_id",
            crc_field: "lore_item_id_crc",
            key_column: "LoreItemID",
            key_getter: "lore_item_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::Error,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            row_filters: Vec::new(),
            fields: vec![projection_field(
                "lore_id",
                "LoreID",
                "lore_id",
                NativeProjectionTransform::String,
            )],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "lore_item",
                    "lore_item_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "lore_item_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "lore_item_from_id",
                    "lore_item_id",
                    NativeCrcIndexLookupParameterKind::IntoCrc32,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::LoreItemDataManager",
            rust_type: "crate::LoreItemDataManager",
            ghidra_functions: vec![
                "Javelin::LoreItemDataManager::LoreItemDataManager",
                "Javelin::LoreItemDataManager::CacheAllDataTables",
            ],
        }),
        crc_projection(CrcProjectionSpec {
            module: "input_profile_data",
            table_name: "InputProfiles",
            row_type_name: "InputProfileData",
            data_type: "InputProfileData",
            entries_field: "input_profiles",
            index_field: "rows_by_crc",
            key_field: "display_name",
            crc_field: "display_name_crc",
            key_column: "DisplayName",
            key_getter: "display_name",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: true,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: None,
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "path",
                    "Path",
                    "path",
                    NativeProjectionTransform::NonEmptyString,
                ),
                projection_field(
                    "display_string",
                    "DisplayString",
                    "display_string",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "rebindable",
                    "Rebindable",
                    "rebindable",
                    NativeProjectionTransform::Bool,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "input_profile_data_from_id",
                    "display_name",
                    NativeCrcIndexLookupParameterKind::Crc32,
                ),
                lookup(
                    "input_profile_data",
                    "display_name",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "input_profile_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("input_profiles"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::InputProfileDataManager",
            rust_type: "crate::InputProfileDataManager",
            ghidra_functions: vec![
                "Javelin::InputProfileDataManager::InputProfileDataManager",
                "Javelin::InputProfileDataManager::CacheAllDataTables",
            ],
        }),
        crc_projection(CrcProjectionSpec {
            module: "combat_settings_data",
            table_name: "CombatSettingsDataTable",
            row_type_name: "CombatSettingsData",
            data_type: "CombatSettingsData",
            entries_field: "entries",
            index_field: "rows_by_profile_name",
            key_field: "profile_name",
            crc_field: "profile_name_crc",
            key_column: "ProfileName",
            key_getter: "profile_name",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("source_row"),
            row_filters: Vec::new(),
            fields: Vec::new(),
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "combat_settings_data",
                    "profile_name",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
                lookup(
                    "combat_settings_data_by_key",
                    "key",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("entries"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::CombatSettingsDataManager",
            rust_type: "crate::CombatSettingsDataManager",
            ghidra_functions: vec![
                "Javelin::CombatSettingsDataManager::CombatSettingsDataManager",
                "Javelin::CombatSettingsDataManager::CacheAllDataTables",
            ],
        }),
        crc_projection(CrcProjectionSpec {
            module: "dungeon_cluster_static_data",
            table_name: "DungeonCluster",
            row_type_name: "DungeonClusterStaticData",
            data_type: "DungeonClusterStaticData",
            entries_field: "rows",
            index_field: "rows_by_cluster_id",
            key_field: "cluster_key",
            crc_field: "cluster_id",
            key_column: "ClusterId",
            key_getter: "cluster_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("dungeon_cluster_static_data_for_source_row"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "feature_id",
                    "FeatureId",
                    "feature_id",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "seed_graph",
                    "SeedGraph",
                    "seed_graph",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "weight",
                    "Weight",
                    "weight",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "theme",
                    "Theme",
                    "theme",
                    NativeProjectionTransform::OptionalString,
                ),
                projection_field(
                    "replacement_count",
                    "ReplacementCount",
                    "replacement_count",
                    NativeProjectionTransform::NonZeroU32,
                ),
                projection_field(
                    "comment",
                    "Comment",
                    "comment",
                    NativeProjectionTransform::OptionalString,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "dungeon_cluster_static_data",
                    "cluster_id",
                    NativeCrcIndexLookupParameterKind::IntoCrc32,
                ),
                lookup(
                    "dungeon_cluster_static_data_by_key",
                    "cluster_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::PCG::DungeonClusterStaticDataManager",
            rust_type: "crate::DungeonClusterStaticDataManager",
            ghidra_functions: vec![
                "Javelin::PCG::DungeonClusterStaticDataManager::DungeonClusterStaticDataManager",
                "Javelin::PCG::DungeonClusterStaticDataManager::CacheAllDataTables",
            ],
        }),
        dungeon_tile_static_data_manager_spec(),
        crc_projection(CrcProjectionSpec {
            module: "dungeon_grammar_static_data",
            table_name: "DungeonGrammar",
            row_type_name: "DungeonGrammarStaticData",
            data_type: "DungeonGrammarStaticData",
            entries_field: "rows",
            index_field: "rows_by_grammar_replacement_id",
            key_field: "grammar_replacement_key",
            crc_field: "grammar_replacement_id",
            key_column: "GrammaReplacementId",
            key_getter: "gramma_replacement_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("dungeon_grammar_static_data_for_source_row"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "feature_id",
                    "FeatureId",
                    "feature_id",
                    NativeProjectionTransform::Crc32,
                ),
                projection_field(
                    "seed_graph",
                    "SeedGraph",
                    "seed_graph",
                    NativeProjectionTransform::String,
                ),
                projection_field(
                    "min_depth",
                    "MinDepth",
                    "min_depth",
                    NativeProjectionTransform::OptionalU8DefaultZero,
                ),
                projection_field(
                    "max_depth",
                    "MaxDepth",
                    "max_depth",
                    NativeProjectionTransform::OptionalU8DefaultMax,
                ),
                projection_field(
                    "theme_tags",
                    "ThemeTags",
                    "theme_tags",
                    NativeProjectionTransform::OptionalCrcListDefaultEmpty,
                ),
                projection_field("weight", "Weight", "weight", NativeProjectionTransform::U32),
                projection_field(
                    "grammar_replacements",
                    "GrammarReplacements",
                    "grammar_replacements",
                    NativeProjectionTransform::CrcList,
                ),
                projection_field(
                    "comments",
                    "Comments",
                    "comments",
                    NativeProjectionTransform::OptionalString,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "dungeon_grammar_static_data",
                    "grammar_replacement_id",
                    NativeCrcIndexLookupParameterKind::IntoCrc32,
                ),
                lookup(
                    "dungeon_grammar_static_data_by_key",
                    "grammar_replacement_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::PCG::DungeonGrammarStaticDataManager",
            rust_type: "crate::DungeonGrammarStaticDataManager",
            ghidra_functions: vec![
                "Javelin::PCG::DungeonGrammarStaticDataManager::DungeonGrammarStaticDataManager",
                "Javelin::PCG::DungeonGrammarStaticDataManager::CacheAllDataTables",
            ],
        }),
        crc_projection(CrcProjectionSpec {
            module: "dungeon_room_static_data",
            table_name: "DungeonRoom",
            row_type_name: "DungeonRoomStaticData",
            data_type: "DungeonRoomStaticData",
            entries_field: "rows",
            index_field: "rows_by_room_id",
            key_field: "room_key",
            crc_field: "room_id",
            key_column: "RoomId",
            key_getter: "room_id",
            skip_empty_key: true,
            trim_key: false,
            reject_zero_crc: false,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("dungeon_room_static_data_for_source_row"),
            row_filters: Vec::new(),
            fields: vec![
                projection_field(
                    "feature_id",
                    "FeatureId",
                    "feature_id",
                    NativeProjectionTransform::Crc32,
                ),
                projection_field(
                    "room_type",
                    "RoomType",
                    "room_type",
                    NativeProjectionTransform::Crc32,
                ),
                projection_field(
                    "starting_state",
                    "StartingState",
                    "starting_state",
                    NativeProjectionTransform::Crc32,
                ),
                projection_field(
                    "alias_category1",
                    "AliasCategory1",
                    "alias_category1",
                    NativeProjectionTransform::Crc32,
                ),
                projection_field(
                    "alias_tag1",
                    "AliasTag1",
                    "alias_tag1",
                    NativeProjectionTransform::OptionalCrcListDefaultEmpty,
                ),
                projection_field(
                    "alias_category2",
                    "AliasCategory2",
                    "alias_category2",
                    NativeProjectionTransform::OptionalCrc32,
                ),
                projection_field(
                    "alias_tag2",
                    "AliasTag2",
                    "alias_tag2",
                    NativeProjectionTransform::OptionalCrcListDefaultEmpty,
                ),
                projection_field(
                    "alias_category3",
                    "AliasCategory3",
                    "alias_category3",
                    NativeProjectionTransform::OptionalCrc32,
                ),
                projection_field(
                    "alias_tag3",
                    "AliasTag3",
                    "alias_tag3",
                    NativeProjectionTransform::OptionalCrcListDefaultEmpty,
                ),
                projection_field(
                    "alias_category4",
                    "AliasCategory4",
                    "alias_category4",
                    NativeProjectionTransform::OptionalCrc32,
                ),
                projection_field(
                    "alias_tag4",
                    "AliasTag4",
                    "alias_tag4",
                    NativeProjectionTransform::OptionalCrcListDefaultEmpty,
                ),
                projection_field(
                    "is_room_passable",
                    "IsRoomPassable",
                    "is_room_passable",
                    NativeProjectionTransform::Bool,
                ),
                projection_field(
                    "room_passthrough_cost",
                    "RoomPassthroughCost",
                    "room_passthrough_cost",
                    NativeProjectionTransform::F32,
                ),
            ],
            secondary_indexes: Vec::new(),
            lookup_methods: vec![
                lookup(
                    "dungeon_room_static_data",
                    "room_id",
                    NativeCrcIndexLookupParameterKind::IntoCrc32,
                ),
                lookup(
                    "dungeon_room_static_data_by_key",
                    "room_id",
                    NativeCrcIndexLookupParameterKind::AsRefStr,
                ),
            ],
            ids_method: None,
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::PCG::DungeonRoomStaticDataManager",
            rust_type: "crate::DungeonRoomStaticDataManager",
            ghidra_functions: vec![
                "Javelin::PCG::DungeonRoomStaticDataManager::DungeonRoomStaticDataManager",
                "Javelin::PCG::DungeonRoomStaticDataManager::CacheAllDataTables",
            ],
        }),
        numeric_projection(NumericProjectionSpec {
            module: "static_gear_score_upgrade_data",
            table_name: "GearScoreUpgrade",
            row_type_name: "GearScoreUpgradeDefinition",
            data_type: "StaticGearScoreUpgradeData",
            entries_field: "rows",
            index_field: "rows_by_level",
            key_field: "level",
            key_column: "Level",
            key_getter: "level",
            key_type: NativeNumericKeyType::U16FromNonZeroU32,
            duplicate_key_policy: NativeDuplicateKeyPolicy::FirstWins,
            source_row_field: Some("source_row"),
            source_row_method: Some("gear_score_upgrade_data_for_source_row"),
            fields: vec![
                projection_field(
                    "required_currency_id",
                    "RequiredCurrencyId",
                    "required_currency_id",
                    NativeProjectionTransform::LowercaseCrcString,
                ),
                projection_field(
                    "required_currency_quantity",
                    "RequiredCurrencyQuantity",
                    "required_currency_quantity",
                    NativeProjectionTransform::NonZeroU32,
                ),
            ],
            lookup_methods: vec![numeric_lookup(
                "gear_score_upgrade_data",
                "level",
                NativeNumericLookupParameterKind::U16,
            )],
            rows_method: Some("rows"),
            len_method: Some("len"),
            is_empty_method: Some("is_empty"),
            ghidra_class: "Javelin::StaticGearScoreUpgradeDataManager",
            rust_type: "crate::StaticGearScoreUpgradeDataManager",
            ghidra_functions: vec![
                "Javelin::StaticGearScoreUpgradeDataManager::StaticGearScoreUpgradeDataManager",
                "Javelin::StaticGearScoreUpgradeDataManager::CacheAllDataTables",
            ],
        }),
    ]
}
